### ISSUE TITLE
KeyError: 'trainable_weights'

### ISSUE THREAD

**Issue by fanchunpeng** [google/automl#1016]
Traceback (most recent call last):
  File "train_RGB_softmax.py", line 351, in <module>
    tf.app.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_RGB_softmax.py", line 194, in main
    logits = build_model(images_batch)
  File "train_RGB_softmax.py", line 126, in build_model
    model = effnetv2_model.EffNetV2Model(model_Dict["model_name"], model_Dict)
  File "D:\TF_EfficientNet\EfficientNetV2\EfficientNetV2_fancp\effnetv2_model.py", line 534, in __init__
    self.cfg = cfg
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\network.py", line 335, in __setattr__
    or checkpointable_layer_utils.has_weights(value)):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\training\checkpointable\layer_utils.py", line 36, in has_weights
    return (hasattr(obj, "trainable_weights")
  File "D:\TF_EfficientNet\EfficientNetV2\EfficientNetV2_fancp\hparams.py", line 56, in __getattr__
    return self.__dict__[k]
KeyError: 'trainable_weights'

**Comment by mingxingtan** [comment]
Could you paste the full command line? I don't understand your question.
