### ISSUE TITLE
Clear instructions for efficientdet-lite tflite conversion and tflite evaluation

### ISSUE THREAD

**Issue by ameyparanjape** [google/automl#1047]
I am having hard time converting and evaluating the `efficientdet-lite2` tflite model trained on custom data. I tried to follow the directions from readme as well as some of the issues. Could anyone please explain the process start to end from conversion of the efficientdet-lite checkpoint to tflite and succesfully evaluating the tflite on validation/test data?
Here is what I have (and that does not work well)
For conversion of model ckpt to tflite:
```linux
python -m keras.inspector --mode=export --model_name=efficientdet-lite2 
--model_dir=<path to pretrained model ckpt for efficientdet-lite2> 
--export_ckpt=<path to archive directory> 
--saved_model_dir=saved_models/lite2_v1/saved_model --only_network 
--tflite=INT8 --hparams=configs/lite2_v1.yaml
```

I am getting following error:
`ValueError: Shape mismatch: class_net/class-predict/pointwise_kernel`

I'm not sure if I correctly understand the input arguments of the conversion script, thank you in advance!

**Comment by ameyparanjape** [comment]
@fsx950223 I saw a few of your comments and PRs around this. Do you mind helping me out here, thank you!

**Comment by fsx950223** [comment]
check num_classes

**Comment by ameyparanjape** [comment]
`--hparams=configs/lite2_v1.yaml` takes care of the `num_classes`

Here is how my `configs/lite2_v1.yaml` looks like
```
num_classes: 5
label_map: {1:'alpha',2:'beta',3:'gamma',4:'delta'}
moving_average_decay: 0
aspect_ratios:
- 0.3937
- 0.8348
- 1.7368
mixed_precision: False
name: 'efficientdet-lite1'
image_size: 384
backbone_name: efficientnet-lite1
anchor_scale: 2.0
tflite_max_detections: 50
autoaugment_policy: v1
```

**Comment by fsx950223** [comment]
Could you print the mismatched shape?

**Comment by ameyparanjape** [comment]
```
I0707 06:12:22.707607 139778170529600 util_keras.py:206] Init efficientnet-lite2/blocks_1/depthwise_conv2d/depthwise_kernel:0 from efficientnet-lite2/blocks_1/depthwise_conv2d/depthwise_kernel (gs://**********/efficientdet-lite2/model)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/automl/efficientdet/keras/inspector.py", line 192, in <module>
    app.run(main)
  File "/home/jupyter/tf2.5/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/jupyter/tf2.5/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/jupyter/automl/efficientdet/keras/inspector.py", line 96, in main
    FLAGS.num_calibration_steps)
  File "/home/jupyter/automl/efficientdet/keras/infer_lib.py", line 353, in export
    export_model, input_spec = self._get_model_and_spec(tflite)
  File "/home/jupyter/automl/efficientdet/keras/infer_lib.py", line 321, in _get_model_and_spec
    export_model = ExportNetwork(self.model)
  File "/home/jupyter/automl/efficientdet/keras/infer_lib.py", line 192, in model
    self.build()
  File "/home/jupyter/automl/efficientdet/keras/infer_lib.py", line 214, in build
    skip_mismatch=False)
  File "/home/jupyter/automl/efficientdet/keras/util_keras.py", line 201, in restore_ckpt
    raise ValueError(msg)
ValueError: Shape mismatch: class_net/class-predict/pointwise_kernel
```

Here is the complete error message, I do not specifically see a mismatched shape

**Comment by ameyparanjape** [comment]
I think I figured the conversion part out with this
```
python -m keras.inspector --mode=export --model_name=efficientdet-lite2 
--model_dir=<path to archive directory> 
--saved_model_dir=saved_models/lite2_v1/saved_model --only_network 
--tflite=INT8 --hparams=configs/lite2_v1.yaml
```
In the second part (using `eval_tflite.py`), I still get an error:
Command I'm using is:
```
python -m keras.eval_tflite --eval_samples=1000 
--val_file_pattern=gs://**********/val/*.tfrecord 
--model_name=efficientdet-lite2 --only_network 
--tflite_path=saved_model/int8.tflite --hparams=configs/lite2_v1.yaml
```

Error I am getting is:
```
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
2021-07-07 06:30:06.952350: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-07 06:30:06.954619: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199995000 Hz
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/automl/efficientdet/keras/eval_tflite.py", line 207, in <module>
    app.run(main)
  File "/home/jupyter/tf2.5/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/jupyter/tf2.5/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/jupyter/automl/efficientdet/keras/eval_tflite.py", line 177, in main
    cls_outputs, box_outputs = lite_runner.run(images)
  File "/home/jupyter/automl/efficientdet/keras/eval_tflite.py", line 83, in run
    signature_fn = interpreter.get_signature_runner()
  File "/home/jupyter/tf2.5/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 750, in get_signature_runner
    len(self._signature_defs)))
ValueError: SignatureDef method_name is None and model has 0 Signatures. None is only allowed when the model has 1 SignatureDef
```

**Comment by drahmad89** [comment]
Is it possible to export efficientdet-d2 into full int8 and run inference? 
I have did this and managed to get my int8 tflite but the inference not showing any error and any outputs and kept running for ever

**Comment by fsx950223** [comment]
Follow my turtorial https://colab.research.google.com/drive/13_XLWNDYV9IAZMAmu8pxmdTNbwaoPI-a?usp=sharing

**Comment by ameyparanjape** [comment]
@drahmad89 the tutorial that @fsx950223 has attached is very comprehensive, great work! Since int8 export requires you to add `num_calibration_steps` it may take a while to get the calibration done and export the int8 tflite model. Maybe try reducing the steps (default=2000) to 10, to check if you are running into any errors. With less steps, it should export fairly quicker.

**Comment by drahmad89** [comment]
> @drahmad89 the tutorial that @fsx950223 has attached is very comprehensive, great work! Since int8 export requires you to add `num_calibration_steps` it may take a while to get the calibration done and export the int8 tflite model. Maybe try reducing the steps (default=2000) to 10, to check if you are running into any errors. With less steps, it should export fairly quicker.

Sorry maybe I was not clear. I managed to obtain my int8.tflite and completed the calibration but the inference was hanging forever when it comes to efficientdet-d{0,1,2,3,4,5} but with efficientdet-lite it worked. For my task efficientdet-lite is not enough to get good performance so I need to run int8 version of efficientdet-d2. To mention that I visualize on netron the model graph of lite version and they have lot of difference in the architecture (did not find any Mul operation and logistic operation) so maybe the D2 has non supported operations!

**Comment by chinmayapatnayak** [comment]
> Follow my turtorial https://colab.research.google.com/drive/13_XLWNDYV9IAZMAmu8pxmdTNbwaoPI-a?usp=sharing

Thanks a lot, @fsx950223! The link seems dead?
