### ISSUE TITLE
About training custom data on efficientNet v2-s

### ISSUE THREAD

**Issue by hsysfan** [google/automl#1051]
Hi

i made tfrecord dataset for training

the datasets made by tfslim code which is download_and_convert_data.py and custom python files.

so i have tfrecord files but this is grayscale datasets and i have a problems with loading datasets

i use [python main.py --mode=train --model_dir=summary --data_dir=efficientnetv2\data] <- my datasets in this folder

but it shows me the type error.

**Traceback (most recent call last):
  File "main.py", line 502, in <module>
    app.run(main)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 494, in main
    est.train(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3110, in train
    rendezvous.raise_errors()
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\tpu\error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3100, in train
    return super(TPUEstimator, self).train(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1201, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1037, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3062, in _call_input_fn
    return input_fn(**kwargs)
  File "E:\automl-master\efficientnetv2\datasets.py", line 399, in input_fn
    return self._input_fn(batch_size, current_host, num_hosts)
  File "E:\automl-master\efficientnetv2\datasets.py", line 403, in _input_fn
    dataset = self.make_source_dataset(current_host, num_hosts)
  File "E:\automl-master\efficientnetv2\datasets.py", line 363, in make_source_dataset
    dataset = dataset.interleave(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2834, in interleave
    super(DatasetV1, self).interleave(map_func, cycle_length, block_length,
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2067, in interleave
    return ParallelInterleaveDataset(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4642, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3712, in __init__
    self._function = fn_factory()
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 3134, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 3100, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3687, in wrapped_fn
    ret = wrapper_helper(*args)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3617, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\autograph\impl\api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    E:\automl-master\efficientnetv2\datasets.py:333 fetch_dataset  *
        dataset = tf.data.TFRecordDataset(filename, buffer_size=buffer_size)
    C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\readers.py:454 __init__  **
        wrapped = TFRecordDatasetV2(filenames, compression_type, buffer_size,
    C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\readers.py:412 __init__
        filenames = _create_or_validate_filenames_dataset(filenames)
    C:\Users\viewon\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\readers.py:68 _create_or_validate_filenames_dataset
        raise TypeError(

    TypeError: `filenames` must be a `tf.Tensor` of dtype `tf.string` dtype. Got <dtype: 'float32'>**

i cant understand about the error...

please could somebody help me?

thanks for reading

**Comment by mingxingtan** [comment]
It says you passed a wrong file name, could you debug it by adding "print(filename)" right before E:\automl-master\efficientnetv2\datasets.py:333?

**Comment by hsysfan** [comment]
@mingxingtan
i checked print(filename). and the result is Tensor("args_0:0", shape=(), dtype=float32).
so i tried to find out where the function fetch_dataset start but i couldnt find.

**Comment by SuperSaid09** [comment]
@hsysfan 

Have u find a solution?

**Comment by mingxingtan** [comment]
Hi, we assume the file patterns are something like "train-xxx" and "eval-xxx", but you can change them here: https://github.com/google/automl/blob/0fb012a80487f0defa4446957c8faf878cd9b75b/efficientnetv2/datasets.py#L85
