### ISSUE TITLE
KeyError: 'try_gcs'

### ISSUE THREAD

**Issue by riaqn** [google/automl#1054]
```
Traceback (most recent call last):
  File "/root/automl/efficientnetv2/main.py", line 502, in <module>
    app.run(main)
  File "/usr/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/automl/efficientnetv2/main.py", line 445, in main
    est.train(
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3110, in train
    rendezvous.raise_errors()
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/lib/python3.9/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3100, in train
    return super(TPUEstimator, self).train(
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1201, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1037, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3062, in _call_input_fn
    return input_fn(**kwargs)
  File "/root/automl/efficientnetv2/datasets.py", line 399, in input_fn
    return self._input_fn(batch_size, current_host, num_hosts)
  File "/root/automl/efficientnetv2/datasets.py", line 534, in _input_fn
    self.cfg.tfds_name, split=self.cfg.splits[self.split]['tfds_split'], try_gcs=self.cfg.try_gcs)
  File "/root/automl/efficientnetv2/hparams.py", line 54, in __getattr__
    return self.__dict__[k]
KeyError: 'try_gcs'
```
I'm on latest commit 9c58b0b487995d5e6b95ba366cb56cff8f17cd26. Python `3.9.6`. Command called is 
```
python main.py --mode=train  --model_name=efficientnetv2-s  --dataset_cfg=imagenetFt --model_dir=model --hparam_str="train.ft_init_ckpt=efficientnetv2-s.tgz" --use_tpu=False
```

**Comment by mingxingtan** [comment]
the default try_gcs is missing. Should be fixed now.
