### ISSUE TITLE
Efficientdet h5 model can't be loaded

### ISSUE THREAD

**Issue by fsx950223** [google/automl#1058]
```
Traceback (most recent call last):
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2335, in load_weights
    hdf5_format.load_model_weights_from_hdf5_group(f, self, by_name, skip_mismatch)
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 733, in load_model_weights_from_hdf5_group
    f, model.layers, skip_mismatch=skip_mismatch)
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 822, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #3 (named "fpn_cells"), weight <tf.Variable 'fpn_cells/cell_0/fnode0/WSM:0' shape=() dtype=float32, numpy=1.0> has shape (), but the saved weight has shape (3, 3, 64, 1).
```
```python
import hparams_config
from keras import efficientdet_keras

config = hparams_config.get_efficientdet_config('efficientdet-d0')
config.is_training_bn = False
model = efficientdet_keras.EfficientDetModel(config=config)
model.build((None, 512, 512, 3))
model.load_weights('/media/fangsixie/data/download/efficientdet-d0.h5', by_name=True)
```

**Comment by muhamedsahin** [comment]
.

**Comment by stuurgurs** [comment]
@fsx950223 Have you solved this?
