### ISSUE TITLE
tutorial.ipynb: ModuleNotFoundError: No module named 'keras.api'

### ISSUE THREAD

**Issue by qkum** [google/automl#1073]
Hello dear maintainers and veteran programmers :) 

I'm not a veteran yet, but I hope a nice soul can help me and others out who hit this error.

I have not found a fix after like 3-4 hours of Google/StackOverflow/GitHub issues search.

I get this `tutorial.ipynb: ModuleNotFoundError: No module named 'keras.api'` error.

![No Module named ´keras api´](https://user-images.githubusercontent.com/40965179/130297408-ab71cab1-f611-4ab2-a7b5-01b4ccfac3df.PNG)

i'm using Google Colab and just running the tutorial.ipynb file as it is.

I also get this error "No dashboards are active for the current data set." but from what I figured out it is just some sort of historical stats log thing and not important.

![No Dashboards are active](https://user-images.githubusercontent.com/40965179/130297651-5d40ce8d-7e49-43f9-8f6a-82b62df3b5d6.PNG)

print(tf.__version__) == 2.6.0
python == 3.7

I hope that is enough info to figure out what is wrong.

Thanks for your time & help 🥇

**Comment by kartik4949** [comment]
Python is looking for api module in your keras(tensorflow) not in local repository (keras/api)

**Comment by rajeshpt** [comment]
Experiencing same issue on Colab. Notebook was working fine couple of days ago and now getting -

ModuleNotFoundError: No module named 'keras.api'

-Tensorflow version on Colab hasn't changed 2.6.0
- Python version 3.7 (not sure if this version has changed??)
- Keras version 2.6.0

Any ideas? 
Thanks for your help.

**Comment by rajeshpt** [comment]
Getting the same error(shown below) with just a simple training run on custom data(worked fine till 2 days ago). Have tried upgrading/downgrading various packages(tf, keras, etc) on colab but nothing works. @kartik4949 any suggestions on how to make python look for keras.api in the correct place?

Completely stuck. Thanks for any help...

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/vehicle_counting/automl/efficientdet/main.py", line 24, in <module>
    import dataloader
  File "/content/vehicle_counting/automl/efficientdet/dataloader.py", line 19, in <module>
    import utils
  File "/content/vehicle_counting/automl/efficientdet/utils.py", line 167, in <module>
    class TpuBatchNormalization(tf2.keras.layers.BatchNormalization):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'keras.api'

**Comment by rajeshpt** [comment]
Got it working by installing pyhton 3.8, TF 2.4.1 and Keras 2.4.0 in colab. Not sure if this is the best way but for now it works.

!sudo add-apt-repository ppa:deadsnakes/ppa
!sudo apt-get update
!sudo apt-get install python3.8
!sudo apt install python3.8-distutils
!sudo apt install python3.8-venv python3.8-dev
!sudo apt-get install python3-pip
!python3.8 -m pip install -U pip setuptools

!pip install tensorflow==2.4.1
!pip install keras==2.4

**Comment by fsx950223** [comment]
https://colab.research.google.com/drive/13_XLWNDYV9IAZMAmu8pxmdTNbwaoPI-a?usp=sharing

**Comment by rajeshpt** [comment]
> It is caused by package naming conflict: one of our folder name is keras, which has conflict with the internal keras package.
> I have renamed it to tf2 in #be5340b and the colab runs well now.

Thank you @mingxingtan. Really appreciate your help/support.
