### ISSUE TITLE
Why can't I convert a data set in coco format to tfrecord?

### ISSUE THREAD

**Issue by wangtianlong1994** [google/automl#109]
> PYTHONPATH=".:$PYTHONPATH" python dataset/create_coco_tfrecord.py 
> --image_dir=VOCdevkit_COCO/images 
> --caption_annotations_file=VOCdevkit_COCO/annotations/train2017.json 
> --output_file_prefix=tfrecord/train --num_shards=100
Show the following errors：
```
2020-03-31 10:43:15.478439: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-31 10:43:15.478502: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-31 10:43:15.478511: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "create_coco_tfrecord.py", line 43, in <module>
    from dataset import label_map_util
ModuleNotFoundError: No module named 'dataset'
```
But the file is here. Why can't I find it?
```
automl/efficientdet/dataset$ ls
create_coco_tfrecord.py  create_coco_tfrecord_test.py  __init__.py  label_map_util.py  README.md  tfrecord_util.py

```

**Comment by Guzaiwang** [comment]
> > PYTHONPATH=".:$PYTHONPATH" python dataset/create_coco_tfrecord.py
> > --image_dir=VOCdevkit_COCO/images
> > --caption_annotations_file=VOCdevkit_COCO/annotations/train2017.json
> > --output_file_prefix=tfrecord/train --num_shards=100
> > Show the following errors：
> 
> ```
> 2020-03-31 10:43:15.478439: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
> 2020-03-31 10:43:15.478502: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
> 2020-03-31 10:43:15.478511: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> Traceback (most recent call last):
>   File "create_coco_tfrecord.py", line 43, in <module>
>     from dataset import label_map_util
> ModuleNotFoundError: No module named 'dataset'
> ```
> 
> But the file is here. Why can't I find it?
> 
> ```
> automl/efficientdet/dataset$ ls
> create_coco_tfrecord.py  create_coco_tfrecord_test.py  __init__.py  label_map_util.py  README.md  tfrecord_util.py
I met the same issue. my solution is to directly "import label_map_util" rather than "from dataset import label_map_util".

**Comment by wangtianlong1994** [comment]
@Guzaiwang Thank you very much. Your suggestion is very effective
