### ISSUE TITLE
FAIL: test_eager_output (__main__.EfficientDetKerasTest)

### ISSUE THREAD

**Issue by danielTobon43** [google/automl#1097]
Hi there,

I just run the test for the efficientdet keras test and don't know why the test is not ok. I mean, I have not changed anything in the code. Is this working properly? 

```
(pop-env) daniel_tobon@efficientdet-training1:~/automl_v2/efficientdet_aituring/test$ python efficientdet_keras_test.py 
Running tests under Python 3.8.10: /home/daniel_tobon/pop-env/bin/python
[ RUN      ] EfficientDetKerasTest.test_build_feature_network
/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/keras/legacy_tf_layers/convolutional.py:414: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  warnings.warn('`tf.layers.conv2d` is deprecated and '
/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/keras/legacy_tf_layers/convolutional.py:1100: UserWarning: `tf.layers.separable_conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.SeparableConv2D` instead.
  warnings.warn('`tf.layers.separable_conv2d` is deprecated and '
/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/keras/legacy_tf_layers/pooling.py:310: UserWarning: `tf.layers.max_pooling2d` is deprecated and will be removed in a future version. Please use `tf.keras.layers.MaxPooling2D` instead.
  warnings.warn('`tf.layers.max_pooling2d` is deprecated and '
[       OK ] EfficientDetKerasTest.test_build_feature_network
[ RUN      ] EfficientDetKerasTest.test_eager_output
/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1331: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '
[  FAILED  ] EfficientDetKerasTest.test_eager_output
[ RUN      ] EfficientDetKerasTest.test_irregular_shape
[       OK ] EfficientDetKerasTest.test_irregular_shape
[ RUN      ] EfficientDetKerasTest.test_model_output
[  FAILED  ] EfficientDetKerasTest.test_model_output
[ RUN      ] EfficientDetKerasTest.test_model_variables
[       OK ] EfficientDetKerasTest.test_model_variables
[ RUN      ] EfficientDetKerasTest.test_resample_feature_map
/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:2183: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
[       OK ] EfficientDetKerasTest.test_resample_feature_map
[ RUN      ] EfficientDetKerasTest.test_resample_var_names
[       OK ] EfficientDetKerasTest.test_resample_var_names
[ RUN      ] EfficientDetKerasTest.test_session
[  SKIPPED ] EfficientDetKerasTest.test_session
======================================================================
FAIL: test_eager_output (__main__.EfficientDetKerasTest)
EfficientDetKerasTest.test_eager_output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "efficientdet_keras_test.py", line 104, in test_eager_output
    self.assertAllClose(
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 1253, in decorated
    return f(*args, **kwds)
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2743, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2697, in _assertAllCloseRecursive
    self._assertArrayLikeAllClose(
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2637, in _assertArrayLikeAllClose
    np.testing.assert_allclose(
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001
Mismatched value: a is different from b. 
not close where = (array([0, 0, 0, ..., 0, 0, 0]), array([ 0,  0,  0, ..., 63, 63, 63]), array([50, 50, 50, ..., 63, 63, 63]), array([ 45, 127, 193, ..., 802, 803, 804]))
not close lhs = [-4.5524106 -4.588805  -4.598505  ... -4.674649  -4.764421  -4.681866 ]
not close rhs = [-4.5531044 -4.5893683 -4.597792  ... -4.6754327 -4.763472  -4.682454 ]
not close dif = [0.0006938  0.00056314 0.00071287 ... 0.00078392 0.00094891 0.00058794]
not close tol = [0.00055531 0.00055894 0.00055978 ... 0.00056754 0.00057635 0.00056825]
dtype = float32, shape = (1, 64, 64, 810)
Mismatched elements: 563854 / 3317760 (17%)
Max absolute difference: 0.01580191
Max relative difference: 0.00358715
 x: array([[[[-4.602575, -4.591611, -4.602432, ..., -4.594164, -4.604189,
          -4.570268],
         [-4.598552, -4.600404, -4.596635, ..., -4.5907  , -4.592386,...
 y: array([[[[-4.602561, -4.591618, -4.602396, ..., -4.594115, -4.604177,
          -4.570265],
         [-4.598516, -4.600399, -4.59657 , ..., -4.590657, -4.592408,...

======================================================================
FAIL: test_model_output (__main__.EfficientDetKerasTest)
EfficientDetKerasTest.test_model_output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "efficientdet_keras_test.py", line 79, in test_model_output
    self.assertAllClose(
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 1253, in decorated
    return f(*args, **kwds)
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2743, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2677, in _assertAllCloseRecursive
    self._assertArrayLikeAllClose(
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2637, in _assertArrayLikeAllClose
    np.testing.assert_allclose(
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/daniel_tobon/pop-env/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001
Mismatched value: a is different from b. 
not close where = (array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([  0,   0,   0, ..., 511, 511, 511]), array([  0,   0,   0, ..., 511, 511, 511]), array([0, 1, 2, ..., 0, 1, 2]))
not close lhs = [ 320.33173   67.01773 -125.85033 ... -305.35666  114.28272  314.14648]
not close rhs = [ 320.06573    66.8384   -125.82448  ... -305.0253    114.220764
  312.3825  ]
not close dif = [0.2659912  0.17932892 0.02584839 ... 0.33135986 0.06195831 1.763977  ]
not close tol = [0.03210657 0.00678384 0.01268245 ... 0.03060253 0.01152208 0.03133825]
dtype = float32, shape = (1, 1, 512, 512, 3)
Mismatched elements: 720474 / 786432 (91.6%)
Max absolute difference: 97.34375
Max relative difference: 569.0571
 x: array([[[[[ 3.203317e+02,  6.701773e+01, -1.258503e+02],
          [-1.630482e+02,  9.449451e+01, -1.250932e+02],
          [-7.673403e+01, -3.545425e+02,  1.222264e+02],...
 y: array([[[[[ 3.200657e+02,  6.683840e+01, -1.258245e+02],
          [-1.629712e+02,  9.441557e+01, -1.249740e+02],
          [-7.654548e+01, -3.541984e+02,  1.223090e+02],...

----------------------------------------------------------------------
Ran 8 tests in 116.941s

FAILED (failures=2, skipped=1)
```

**Comment by fsx950223** [comment]
I have fix the test case in my branch https://github.com/google/automl/pull/1036

**Comment by danielTobon43** [comment]
Hi @fsx950223, thanks for your answer. So, that means the test cases in the original repository are not properly set.
