### ISSUE TITLE
Training EfficientNetV2 from scratch with synthetic data throws NaN error

### ISSUE THREAD

**Issue by mandy-li** [google/automl#1126]
We tried training EfficientNetV2 from scratch with synthetic data on different HW to measure the performance, but encounter NaN issue. The problem can be worked around by passing the chkpt file.

To reproduce on an GPU machine, start the training with a command like this:

python3 main.py --mode=train --model_name=efficientnetv2-b0 --dataset_cfg=imagenet --hparam_str="runtime.strategy=None,train.batch_size=1024,train.epochs=1,runtime.mixed_precision=True" --model_dir=/workspace/tmp --use_tpu=False

```
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
I1203 19:27:08.196098 140413810333504 basic_session_run_hooks.py:625] Calling checkpoint listeners after saving checkpoint 0...
2021-12-03 19:27:08.497475: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-12-03 19:27:12.547871: I tensorflow/stream_executor/cuda/cuda_dnn.cc:381] Loaded cuDNN version 8204
ERROR:tensorflow:Model diverged with loss = NaN.
E1203 19:27:17.862431 140413810333504 basic_session_run_hooks.py:770] Model diverged with loss = NaN.
INFO:tensorflow:training_loop marked as finished
I1203 19:27:18.163163 140413810333504 error_handling.py:115] training_loop marked as finished

WARNING:tensorflow:Reraising captured error
W1203 19:27:18.163361 140413810333504 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "main.py", line 504, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 496, in main
    est.train(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3102, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3092, in train
    return super(TPUEstimator, self).train(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 350, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1176, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1207, in _train_model_default
    return self._train_with_estimator_spec(estimator_spec, worker_hooks,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1523, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 775, in run
    return self._sess.run(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1280, in run
    return self._sess.run(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1385, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1370, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1446, in run
    hook.after_run(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 771, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by mingxingtan** [comment]
The synthetic data is just to verify the datasets pipeline is working (no syntax/compile error). It is expected to generate NaN.

The reason is that our current synthetic data is simply {x: all_zero, y: all_zero}, so there is no meaningful inputs or labels (none of the class is true), so it won't learn anything.

You should get non-NaN if using the true datasets.
