### ISSUE TITLE
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 26622 batches). You may need to use the repeat() function when building your dataset.

### ISSUE THREAD

**Issue by exx8** [google/automl#1155]
I've tried to run `main_tf2.py` off efficientnetv2 with the following parameters:
`python3 main_tf2.py --mode=train  --model_name=efficientnetv2-s  --dataset_cfg=imagenet --model_dir=~/effi/models/efficientnetv2 --use_tpu=False --data_dir=/sda/Eran/downloads/TFrecords/train 
`
and the attached hparameters (I use 2 GPUs), 

[hparams.py.txt](https://github.com/google/automl/files/8629537/hparams.py.txt)

and I've gotten the following error:
```
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 26622 batches). You may need to use the repeat() function when building your dataset.
W0505 10:58:02.812526 139786442524480 data_adapter.py:1230] Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 26622 batches). You may need to use the repeat() function when building your dataset.
Traceback (most recent call last):
  File "main_tf2.py", line 312, in <module>
    app.run(main)
  File "/home/eran/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/eran/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "main_tf2.py", line 277, in main
    model.fit(
  File "/home/eran/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/eran/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1395, in fit
    raise ValueError('Unexpected result of `train_function` '
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```

What is the problem?

**Comment by exx8** [comment]
It seems the problem exists no matter what steps_per_epoch , epochs  are (even as low as 1,1).
Trying to convert `get_dataset(training=True, image_size=train_size, config=config)` to list ended with `[]` so probably there is an error parsing the files.
@fsx950223  Can you give it a try?
Thanks!

**Comment by exx8** [comment]
The problem was that the tfrecords generating script, doesn't handle an edge case that leads to empty files. As the problem is not with the code of this project, I close it.
