### ISSUE TITLE
Unable to Visualize Model Inference

### ISSUE THREAD

**Issue by edsumpena** [google/automl#1176]
Upon running:

```
!python -m tf2.inspector --mode=infer \
    --model_name={MODEL}  \
    --saved_model_dir='{model_dir}'  \
    --input_image={TEMP_FILE} --output_image_dir='/content/output/'
```

I receive the following error message. Please let me know if there something I'm missing here.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/automl/efficientdet/tf2/inspector.py", line 198, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/automl/efficientdet/tf2/inspector.py", line 113, in main
    img = driver.visualize(
  File "/content/automl/efficientdet/tf2/infer_lib.py", line 178, in visualize
    return visualize_image(image, boxes, classes.astype(int), scores,
  File "/content/automl/efficientdet/tf2/infer_lib.py", line 66, in visualize_image
    img = vis_utils.visualize_boxes_and_labels_on_image_array(
  File "/content/automl/efficientdet/visualize/vis_utils.py", line 896, in visualize_boxes_and_labels_on_image_array
    draw_bounding_box_on_image_array(
  File "/content/automl/efficientdet/visualize/vis_utils.py", line 156, in draw_bounding_box_on_image_array
    draw_bounding_box_on_image(image_pil, ymin, xmin, ymax, xmax, color,
  File "/content/automl/efficientdet/visualize/vis_utils.py", line 215, in draw_bounding_box_on_image
    display_str_heights = [font.getbbox(ds)[3] - font.getbbox(ds)[1] for ds in display_str_list]
  File "/content/automl/efficientdet/visualize/vis_utils.py", line 215, in <listcomp>
    display_str_heights = [font.getbbox(ds)[3] - font.getbbox(ds)[1] for ds in display_str_list]
AttributeError: 'ImageFont' object has no attribute 'getbbox'
```

**Comment by fsx950223** [comment]
Upgrade pillow.
