### ISSUE TITLE
 Training failure with   coco2014 datasets  on  two GPUs.

### ISSUE THREAD

**Issue by molyswu** [google/automl#122]
Hi, 
Tried to training failure with   coco2014 datasets  on  two GPUs,
 $ python main.py --training_file_pattern=./tfrecord/train* \  --model_name=$MODEL \  --model_dir=/tmp/$MODEL \ --hparams="use_bfloat16=false" --use_tpu=False

Traceback (most recent call last):
  File "main.py", line 385, in <module>
    tf.app.run(main)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 247, in main
    FLAGS.train_batch_size))
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/yy/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Reciprocal' OpKernel for 'CPU' devices compatible with node {{node ConstantFolding/gradients/efficientnet-b0/model/blocks_15/se/Mean_grad/truediv_recip}}
         (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_BFLOAT16, _device="/job:localhost/replica:0/task:0/device:CPU:0"
        .  Registered:  device='XLA_GPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]

         [[ConstantFolding/gradients/efficientnet-b0/model/blocks_15/se/Mean_grad/truediv_recip]]

Thank you for your help!

**Comment by YangZhang-mizzou** [comment]
Similar error but using 1 gpu

**Comment by molyswu** [comment]
Tried to using 1 gpu,Same issues.

**Comment by mingxingtan** [comment]
Are you using the latest tensorflow version?

**Comment by molyswu** [comment]
tensorflow  1.15.2

**Comment by molyswu** [comment]
Treid to using tensorflow 2.2.0-rc-1   
CUDA_VISIBLE_DEVICES=0 python main.py --training_file_pattern=./tfrecord/train* \  --model_name=$MODEL \   --model_dir=/tmp/$MODEL \ --hparams="use_bfloat16=false" --use_tpu=false
error as following 
Traceback (most recent call last):
  File "/home/yy.local/lib/python3.6/site-packages/tensorflow/python/client/ses                                                                                                                     sion.py", line 1365, in _do_call
    return fn(*args)
  File "/home/yy/.local/lib/python3.6/site-packages/tensorflow/python/client/ses                                                                                                                     sion.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/yy/.local/lib/python3.6/site-packages/tensorflow/python/client/ses                                                                                                                     sion.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s)                                                                                                                      found.
  (0) Failed precondition: tfrecord/train; Is a directory
         [[{{node IteratorGetNext}}]]
  (1) Failed precondition: tfrecord/train; Is a directory
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_15329]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Thanks for your help!

**Comment by mingxingtan** [comment]
Training on multiple GPUs should be fine (as shown in README instructions).
