### ISSUE TITLE
No module named 'tensorflow.compat.v2'

### ISSUE THREAD

**Issue by KaqiKaqi** [google/automl#14]
Hello, i'm using tf.1.13.1 and I have the following error:
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    import det_model_fn
  File "/data01/wens/workspace/project/automl/efficientdet/det_model_fn.py", line 28, in <module>
    import efficientdet_arch
  File "/data01/wens/workspace/project/automl/efficientdet/efficientdet_arch.py", line 31, in <module>
    import utils
  File "/data01/wens/workspace/project/automl/efficientdet/utils.py", line 26, in <module>
    import tensorflow.compat.v2 as tf2
ModuleNotFoundError: No module named 'tensorflow.compat.v2'

Which version of tf shold I use? Thanks a lot.

**Comment by mingxingtan** [comment]
Please install the latest TF 2.x version.
