### ISSUE TITLE
autogragh ERROR:raise NotImplementedError('exceptions are not yet supported')

### ISSUE THREAD

**Issue by 15241192958** [google/automl#143]
my TF version is 1.3.0,is the version not true?
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    import dataloader
  File "/jiangzhixin002/label_dataset/automl/efficientdet/dataloader.py", line 23, in <module>
    import anchors
  File "/jiangzhixin002/label_dataset/automl/efficientdet/anchors.py", line 114, in <module>
    @tf.autograph.to_graph
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 418, in to_graph
    include_source_map=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/pyct/compiler.py", line 130, in ast_to_object
    compiled_nodes = imp.load_source(module_name, f.name)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "/tmp/tmpm3_x5ck_.py", line 3, in <module>
    @tf.autograph.to_graph
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 409, in to_graph
    arg_values, arg_types)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/conversion.py", line 137, in entity_to_graph
    node, name, ns = function_to_graph(o, program_ctx, arg_values, arg_types)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/conversion.py", line 337, in function_to_graph
    node = node_to_graph(node, context)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/conversion.py", line 375, in node_to_graph
    node = converter.standard_analysis(node, context, is_initial=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/core/converter.py", line 471, in standard_analysis
    graphs = cfg.build(node)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/pyct/cfg.py", line 821, in build
    visitor.visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/pyct/cfg.py", line 674, in visit_FunctionDef
    self.visit(stmt)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/pyct/cfg.py", line 802, in visit_Try
    raise NotImplementedError('exceptions are not yet supported')
NotImplementedError: exceptions are not yet supported

**Comment by Gynii** [comment]
i solved this issue by installing tensorflow 2.1

**Comment by 15241192958** [comment]
> i solved this issue by installing tensorflow 2.1

thank u very much.

**Comment by 15241192958** [comment]
> i solved this issue by installing tensorflow 2.1

i have update the tensorflow version,but some bugs come out.have you ever do it ?

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0406 14:46:06.496922 140102098593600 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From /jiangzhixin002/label_dataset/automl/efficientdet/det_model_fn.py:316: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0406 14:46:25.736443 140102098593600 deprecation.py:323] From /jiangzhixin002/label_dataset/automl/efficientdet/det_model_fn.py:316: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /jiangzhixin002/label_dataset/automl/efficientdet/anchors.py:602: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
W0406 14:46:25.761807 140102098593600 deprecation.py:323] From /jiangzhixin002/label_dataset/automl/efficientdet/anchors.py:602: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
