### ISSUE TITLE
Modification of hparams_config.min_level

### ISSUE THREAD

**Issue by RoyceMao** [google/automl#144]
**Now, in my custom dataset, the target is relatively small, and I want to assign anchors based on a lower downsampling feature map, so that there will be a little more positive samples. I have tried to modify parameter - hparams_config.min_level to 2, but encountered an error during training as follows:** 

`I0403 15:35:56.160760 139820064028480 error_handling.py:108] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0403 15:35:56.160930 139820064028480 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3032, in train
    rendezvous.record_error('training_loop', sys.exc_info())
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 81, in record_error
    if value and value.op and value.op.type == _CHECK_NUMERIC_OP_NAME:
AttributeError: 'KeyError' object has no attribute 'op'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 391, in <module>
    tf.app.run(main)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 256, in main
    FLAGS.train_batch_size))
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1194, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1152, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/root/anaconda3/envs/efficientdet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1994, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/home/ld/automl/efficientdet/det_model_fn.py", line 609, in efficientdet_model_fn
    model=efficientdet_arch.efficientdet)
  File "/home/ld/automl/efficientdet/det_model_fn.py", line 412, in _model_fn
    cls_outputs, box_outputs = _model_outputs()
  File "/home/ld/automl/efficientdet/det_model_fn.py", line 402, in _model_outputs
    return model(features, config=hparams_config.Config(params))
  File "/home/ld/automl/efficientdet/efficientdet_arch.py", line 557, in efficientdet
    fpn_feats = build_feature_network(features, config)
  File "/home/ld/automl/efficientdet/efficientdet_arch.py", line 403, in build_feature_network
    config.min_level, config.max_level + 1)
  File "/home/ld/automl/efficientdet/efficientdet_arch.py", line 402, in <listcomp>
    for level in range(
KeyError: 2`

**So, what else modification is needed for normally operation？Thanks！**

**Comment by RoyceMao** [comment]
Especially in script **efficientdet_arch**.bifpn_sum_config()

**Comment by mingxingtan** [comment]
Hi @RoyceMao , you can temporary use the following solution if you wan to use level 2 to 7:

def bifpn_l2to7_config():
  """BiFPN config with level 2 to 7."""
  p = hparams_config.Config()
  p.nodes = [
      {'width_ratio': F(6), 'inputs_offsets': [4, 5]},
      {'width_ratio': F(5), 'inputs_offsets': [3, 6]},
      {'width_ratio': F(4), 'inputs_offsets': [2, 7]},
      {'width_ratio': F(3), 'inputs_offsets': [1, 8]},
      {'width_ratio': F(2), 'inputs_offsets': [0, 9]},
      {'width_ratio': F(3), 'inputs_offsets': [1, 9, 10]},
      {'width_ratio': F(4), 'inputs_offsets': [2, 8, 11]},
      {'width_ratio': F(5), 'inputs_offsets': [3, 7, 12]},
      {'width_ratio': F(6), 'inputs_offsets': [0, 6, 13]},
      {'width_ratio': F(7), 'inputs_offsets': [7, 14]},
  ]
  p.weight_method = 'fastattn'
  return p

I will try to add a generic function that can be adapted to different min_level and mix_level.

**Comment by RoyceMao** [comment]
@mingxingtan really appreciate.

**Comment by mingxingtan** [comment]
Now you can use hparams="fpn_name=bifpn_dyn", which would automatically adapts to any min/max level.
