### ISSUE TITLE
some bugs in inference.py when run model_inspection.py

### ISSUE THREAD

**Issue by qtw1998** [google/automl#150]
when I run 
`python model_inspect.py --runmode=infer --model_name=efficientdet-d1 --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 --ckpt_path=/cluster/home/qiaotianwei/automl/efficientdet/save/efficientdet-d1 --input_image=img.jpg --output_image_dir=/tmp`
###################################################################
ERROR INFROMAITON:
```bash
Traceback (most recent call last):
  File "model_inspect.py", line 383, in <module>
    tf.app.run(main)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 377, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 340, in run_model
    **config_dict)
  File "model_inspect.py", line 220, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
File "/cluster/home/qiaotianwei/automl/efficientdet/inference.py", line 509, in inference                                                            
    **self.params)                                                                                                                                     
  File "/cluster/home/qiaotianwei/automl/efficientdet/inference.py", line 95, in build_model                                                               class_outputs, box_outputs = model_arch(inputs, model_name, **kwargs)                                                                              
  File "/cluster/home/qiaotianwei/automl/efficientdet/efficientdet_arch.py", line 551, in efficientdet                                                 
    features = build_backbone(features, config)                                                                                                        
  File "/cluster/home/qiaotianwei/automl/efficientdet/efficientdet_arch.py", line 329, in build_backbone                                               
    override_params=override_params)
  File "/cluster/home/qiaotianwei/automl/efficientdet/backbone/efficientnet_builder.py", line 324, in build_model_base
    features = model(images, training=training, features_only=True)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __ca
ll__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

ValueError: in converted code:

    /cluster/home/qiaotianwei/automl/efficientdet/backbone/efficientnet_model.py:637 call  *
        outputs = self._relu_fn(
    /cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py:547 __call__
        outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
    /cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:737 __call__
        self.name)
    /cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_spec.py:177 assert_input_compat
ibility
        str(x.shape.as_list()))

    ValueError: Input 0 of layer conv2d_1 is incompatible with the layer: expected ndim=4, found ndim=1. Full shape received: [0]
```

**Comment by mingxingtan** [comment]
It is most likely your input file doesn't exist  (change img.jpg to img.png?)

I have added a check to the code. It would report error now for this case.
