### ISSUE TITLE
AttributeError: module 'gast' has no attribute 'Num'

### ISSUE THREAD

**Issue by vamshi-vk** [google/automl#152]
Traceback (most recent call last):
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 524, in to_graph
    return conversion.convert(entity, program_ctx)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 306, in convert
    entity, program_ctx, free_nonglobal_var_names)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 229, in _convert_with_cache
    entity, program_ctx)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 431, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 624, in convert_func_to_ast
    node = node_to_graph(node, context)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 657, in node_to_graph
    node = converter.standard_analysis(node, context, is_initial=True)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/core/converter.py", line 354, in standard_analysis
    node = qual_names.resolve(node)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 254, in resolve
    return QnResolver().visit(node)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 326, in generic_visit
    value = self.visit(value)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 326, in generic_visit
    value = self.visit(value)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 335, in generic_visit
    new_node = self.visit(old_value)
  File "/data/anaconda/envs/inventory/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 236, in visit_Subscript
    if isinstance(s.value, gast.Num):
AttributeError: module 'gast' has no attribute 'Num'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    import dataloader
  File "/data/home/vishwam/mountpoint/Inventory_Management/automl/efficientdet/dataloader.py", line 23, in <module>
    import anchors
  File "/data/home/vishwam/mountpoint/Inventory_Management/automl/efficientdet/anchors.py", line 114, in <module>
    @tf.autograph.to_graph
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 600, in to_graph_v1
    experimental_optional_features=experimental_optional_features)
  File "/data/anaconda/envs/inventory/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 528, in to_graph
    entity, e.__class__.__name__, str(e)))
tensorflow.python.autograph.impl.api.ConversionError: converting <function nms_tf at 0x7f0b33889710>: AttributeError: module 'gast' has no attribute 'Num'

**Environment** 
absl-py==0.9.0
astor==0.8.0
attrs==19.3.0
certifi==2019.11.28
contextlib2==0.6.0.post1
cycler==0.10.0
Cython==0.29.15
decorator==4.4.2
gast==0.3.3
google-pasta==0.2.0
grpcio==1.27.2
h5py==2.8.0
importlab==0.5.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
lxml==4.5.0
Markdown==3.1.1
matplotlib==3.2.1
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.4
ninja==1.9.0.post1
numpy==1.18.1
olefile==0.46
Pillow==7.0.0
protobuf==3.11.4
pycocotools==2.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytype==2020.3.19
PyYAML==5.3.1
scipy==1.4.1
six==1.14.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
typed-ast==1.4.1
Werkzeug==1.0.0
wrapt==1.12.1

**Command** 
python main.py --training_file_pattern=Efficient_Det_Data_format/tf_records/train*.tfrecord  --validation_file_pattern=Efficient_Det_Data_format/tf_records/eval*.tfrecord --val_json_file=Efficient_Det_Data_format/annotations/eval.json  --ckpt=efficientdet-d0/ --model_name=efficientdet-d0 --model_dir=/tmp/eff_d0_data_v2 --num_classes=1 --use_tpu=False --train_batch_size=8 --eval_batch_size=1 --eval_samples=80 --num_examples_per_epoch=720 --mode=train_and_eval --hparams="use_bfloat16=false" --num_epochs=100

**Comment by vamshi-vk** [comment]
Worked 
! pip3 install 'gast==0.2.2'
