### ISSUE TITLE
Requested more than 0 entries, but params is empty

### ISSUE THREAD

**Issue by deepakcrk** [google/automl#16]
Hi, 
I am using tensorflow 1.14.0, I am getting following error, while running in eval mode:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 383, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/deepak/.local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/deepak/.local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 316, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2897, in evaluate
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 131, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2892, in evaluate
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 477, in evaluate
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 519, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 508, in _evaluate
    output_dir=self.eval_dir(name))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1609, in _evaluate_run
    config=self._session_config)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
	 [[{{node parser/GatherNd_1}}]]
	 [[IteratorGetNext]]
```

**Comment by KaqiKaqi** [comment]
I got same error in train mode.

**Comment by deepakcrk** [comment]
Resolved after upgrading to tensorflow 2.x

**Comment by KaqiKaqi** [comment]
> Resolved after upgrading to tensorflow 2.x

Hello, I still got the same error with tensorflow2.1.0, mode=eval. Could you please tell me which version of tensorflow you are using and how you get tfrecord files? Actually, I don't know what causes this error.

**Comment by deepakcrk** [comment]
> > Resolved after upgrading to tensorflow 2.x
> 
> Hello, I still got the same error with tensorflow2.1.0, mode=eval. Could you please tell me which version of tensorflow you are using and how you get tfrecord files? Actually, I don't know what causes this error.

I am not getting this error after upgrading to  **2.0.0-beta0**

But now I am getting this error: https://github.com/google/automl/issues/15

**Comment by KaqiKaqi** [comment]
> > > Resolved after upgrading to tensorflow 2.x
> > 
> > 
> > Hello, I still got the same error with tensorflow2.1.0, mode=eval. Could you please tell me which version of tensorflow you are using and how you get tfrecord files? Actually, I don't know what causes this error.
> 
> I am not getting this error after upgrading to **2.0.0-beta0**
> 
> But now I am getting this error: #15
> 
> Created TF records using this: https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py
> 
> (but dont know whether what I am doing is right)

I had that NoneType error too. After deleting ".value" in "return self.data['boxes'].get_shape()[0].value" in object_detection/box_list.py, that NoneType error disappered and this error appeared instead.

I created the coco tfrecord in the same way.

**Comment by CraigWang1** [comment]
I have had the same problem. I'm using tensorflow 2.1.0, and I created tfrecords. However, I still got 
`AttributeError: 'NoneType' object has no attribute 'value'`

This was my command:
`
# train model!
# paste tpu name (eg. grpc://10.83..23...etc) to --tpu flag
!python main.py \
    --tpu=grpc://10.118.75.178:8470 \
    --data_dir=/content/TF_records \
    --model_dir=models \
    --mode='train' \
    --training_file_pattern='/content/TF_records/coco_train*' \
    --model_name=efficientdet-d0
`
