### ISSUE TITLE
Unable to evaluate | KeyError: 'categories'

### ISSUE THREAD

**Issue by ggaziv** [google/automl#160]
When running the command:
```
# Evalute on validation set
!python main.py --mode=eval  \
    --model_name={MODEL}  --model_dir={ckpt_path}  \
    --validation_file_pattern=/data/guyga/datasets/coco/tfrecord/val*  \
    --val_json_file=/data/guyga/datasets/coco/annotations/captions_val2017.json  \
    --hparams="use_bfloat16=false" --use_tpu=False
```
I run into KeyError: 'categories' under `pycocotools/coco.py`, line 332, in loadRes
```
...
I0406 13:38:07.643917 140020211447552 session_manager.py:502] Done running local_init_op.
I0406 13:40:28.930046 140020211447552 evaluation.py:167] Evaluation [500/5000]
I0406 13:42:46.103284 140020211447552 evaluation.py:167] Evaluation [1000/5000]
I0406 13:45:05.809685 140020211447552 evaluation.py:167] Evaluation [1500/5000]
I0406 13:47:25.500318 140020211447552 evaluation.py:167] Evaluation [2000/5000]
I0406 13:49:50.431703 140020211447552 evaluation.py:167] Evaluation [2500/5000]
I0406 13:52:15.627047 140020211447552 evaluation.py:167] Evaluation [3000/5000]
I0406 13:54:38.845531 140020211447552 evaluation.py:167] Evaluation [3500/5000]
I0406 13:57:04.133928 140020211447552 evaluation.py:167] Evaluation [4000/5000]
I0406 13:59:38.447332 140020211447552 evaluation.py:167] Evaluation [4500/5000]
I0406 14:02:06.983489 140020211447552 evaluation.py:167] Evaluation [5000/5000]
Loading and preparing results...
Converting ndarray to lists...
(500000, 7)
0/500000
2020-04-06 14:02:09.454124: W tensorflow/core/framework/op_kernel.cc:1610] Unknown: KeyError: 'categories'
Traceback (most recent call last):

  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/data/guyga/PycharmProjects/automl/efficientdet/coco_metric.py", line 135, in _evaluate
    coco_dt = self.coco_gt.loadRes(detections)

  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/pycocotools/coco.py", line 332, in loadRes
    res.dataset['categories'] = copy.deepcopy(self.dataset['categories'])

KeyError: 'categories'


E0406 14:02:09.538412 140020211447552 error_handling.py:75] Error recorded from evaluation_loop: KeyError: 'categories'
Traceback (most recent call last):
```

(*) System information:
Python version: 3.5
pycocotools: 2.0 (according to instructions)
tensorflow: 2.0.0               
tensorflow-estimator: 2.0.1

**Comment by mingxingtan** [comment]
Hi @ggaziv, as shown in our tutorial, you need to use "--val_json_file=annotations/instances_val2017.json" instead of "--val_json_file=/data/guyga/datasets/coco/annotations/captions_val2017.json"
