### ISSUE TITLE
autoaugment_policy crash

### ISSUE THREAD

**Issue by chentairan** [google/automl#161]
Hi,

When I try to use data augmentation, set `h.autoaugment_policy = 'v1'` or `h.autoaugment_policy = 'v2'`, running `main.py` crash. 

Here is the error information:

```
Traceback (most recent call last):
  File "main.py", line 390, in <module>
    tf.app.run(main)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 255, in main
    FLAGS.train_batch_size))
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/mist/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: 2 root error(s) found.
  (0) Unimplemented: 2 root error(s) found.
  (0) Unimplemented:  Depthwise convolution on CPU is only supported for NHWC format
         [[{{node parser/cond_18/then/_91/cond_1/then/_11/depthwise}}]]
         [[parser/cond_18/then/_91/cond_1/then/_11/Cast_1/_22]]
  (1) Unimplemented:  Depthwise convolution on CPU is only supported for NHWC format
         [[{{node parser/cond_18/then/_91/cond_1/then/_11/depthwise}}]]
0 successful operations.
0 derived errors ignored.
         [[IteratorGetNext]]
  (1) Unimplemented: 2 root error(s) found.
  (0) Unimplemented:  Depthwise convolution on CPU is only supported for NHWC format
         [[{{node parser/cond_18/then/_91/cond_1/then/_11/depthwise}}]]
         [[parser/cond_18/then/_91/cond_1/then/_11/Cast_1/_22]]
  (1) Unimplemented:  Depthwise convolution on CPU is only supported for NHWC format
         [[{{node parser/cond_18/then/_91/cond_1/then/_11/depthwise}}]]
0 successful operations.
0 derived errors ignored.
         [[IteratorGetNext]]
         [[IteratorGetNext/_15329]]
0 successful operations.
0 derived errors ignored.
```

Best,
Tairan

**Comment by xiaovirgo** [comment]
metoo,but i can't find what's wrong,i test the program efficientdet/aug/autoaugment_test.py,it's ok.

**Comment by chentairan** [comment]
Hi @xiaovirgo ,
Have you tested the latest code? It seems the author @mingxingtan  made a little modification two days ago.

**Comment by xiaovirgo** [comment]
i have,i have updated today.

**Comment by chentairan** [comment]
Thx, I see. So it's a bug.

**Comment by xiaovirgo** [comment]
maybe i know the problem,you should modify the prob of  the 'Sharpness'  both in v1,v2,v3 to 0.0,because in the function sharpness in line 1112 of aug/autoaugment.py ,tf.nn.depthwise_conv2d in line 1125,it don't suport NCHW on cpu,so change prob to 0.0 to disable it.

**Comment by xiaovirgo** [comment]
@mingxingtan I have installed the tfa,but also have problem,I have notice the erro info, ''Depthwise convolution on CPU is only supported for NHWC format'',I found that in the file ''aug/autoaugment.py'',on line 1114, in the function sharpness(image, factor),it use "tf.nn.depthwise_conv2d",i found this op don't suport cpu when the image format is NCHW,but the estimator will change the fomat from NHWC to NCHW.when i use "policy_v3",i change the prob of the "Sharpness" to 0.0 in line 143 and use tf1.15,it's ok.but i don't know how to make it work without change the prob.

**Comment by sx8ac0t6** [comment]
@chentairan 
The workaround discussed [here](https://github.com/tensorflow/tensorflow/issues/22145#issuecomment-432962172) seems to work in our case as well. I simply added a line `with tf.device('/cpu:0'):` to `aug/autoaugment.py` as below, then I could run `main.py` with `--hparams="autoaugment_policy=v2"` successfully. I'm using tf2.1.0. Hope this helps.

```
def sharpness(image, factor):
  ..
  strides = [1, 1, 1, 1]
  with tf.device('/cpu:0'):
    degenerate = tf.nn.depthwise_conv2d(
        image, kernel, strides, padding='VALID', rate=[1, 1])
  degenerate = tf.clip_by_value(degenerate, 0.0, 255.0)
  ..
```
