### ISSUE TITLE
NameError: name 'unicode' is not defined in colab after 'Loading and preparing results'...

### ISSUE THREAD

**Issue by lessw2020** [google/automl#178]
I ran the coco eval (5000) exactly per the readme:
https://github.com/google/automl/tree/master/efficientdet#5-eval-on-coco-2017-val-or-test-dev

 to test out running in colab and hit an issue I did not hit running on my regular salamander.ai server.  Eval went fine until prepping results...
(note I am running on 2.2.0-rc2'.  I used efficientdet-d0' checkpoint.)

`I0408 02:57:12.755542 140562127026048 evaluation.py:167] Evaluation [5000/5000]
Loading and preparing results...
2020-04-08 02:57:13.133729: W tensorflow/core/framework/op_kernel.cc:1740] Unknown: NameError: name 'unicode' is not defined
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/content/automl/efficientdet/coco_metric.py", line 135, in _evaluate
    coco_dt = self.coco_gt.loadRes(detections)

  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:

NameError: name 'unicode' is not defined

INFO:tensorflow:evaluation_loop marked as finished
I0408 02:57:13.273718 140562127026048 error_handling.py:115] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0408 02:57:13.273960 140562127026048 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: NameError: name 'unicode' is not defined
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/content/automl/efficientdet/coco_metric.py", line 135, in _evaluate
    coco_dt = self.coco_gt.loadRes(detections)

  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:

NameError: name 'unicode' is not defined

	 [[{{node coco_metric/PyFunc_1}}]]
  (1) Unknown: NameError: name 'unicode' is not defined
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/content/automl/efficientdet/coco_metric.py", line 135, in _evaluate
    coco_dt = self.coco_gt.loadRes(detections)

  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:

NameError: name 'unicode' is not defined

	 [[{{node coco_metric/PyFunc_1}}]]
	 [[coco_metric/PyFunc_1/_4349]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 390, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 319, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3104, in evaluate
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3099, in evaluate
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 468, in evaluate
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 511, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 500, in _evaluate
    output_dir=self.eval_dir(name))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1643, in _evaluate_run
    config=self._session_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 885, in __exit__
    self._close_internal(exception_type)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 918, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 961, in end
    self._final_ops, feed_dict=self._final_ops_feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: NameError: name 'unicode' is not defined
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/content/automl/efficientdet/coco_metric.py", line 135, in _evaluate
    coco_dt = self.coco_gt.loadRes(detections)

  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:

NameError: name 'unicode' is not defined

	 [[node coco_metric/PyFunc_1 (defined at /content/automl/efficientdet/coco_metric.py:220) ]]
  (1) Unknown: NameError: name 'unicode' is not defined
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/content/automl/efficientdet/coco_metric.py", line 135, in _evaluate
    coco_dt = self.coco_gt.loadRes(detections)

  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:

NameError: name 'unicode' is not defined

	 [[node coco_metric/PyFunc_1 (defined at /content/automl/efficientdet/coco_metric.py:220) ]]
	 [[coco_metric/PyFunc_1/_4349]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'coco_metric/PyFunc_1':
  File "main.py", line 390, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 319, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3099, in evaluate
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 468, in evaluate
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 511, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 493, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1535, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1571, in _call_model_fn_eval
    config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2915, in _call_model_fn
    config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1170, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3173, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2043, in _call_model_fn
    return estimator_spec.as_estimator_spec()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 379, in as_estimator_spec
    host_call_ret = _OutfeedHostCall.create_cpu_hostcall(self._host_calls)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2119, in create_cpu_hostcall
    ret[name] = host_fn(**tensors)
  File "/content/automl/efficientdet/det_model_fn.py", line 515, in metric_fn
    params['val_json_file'], **kwargs)
  File "/content/automl/efficientdet/det_model_fn.py", line 366, in coco_metric_fn
    kwargs['groundtruth_data'])
  File "/content/automl/efficientdet/coco_metric.py", line 220, in estimator_metric_fn
    metrics = tf.py_func(_evaluate, [], tf.float32)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 555, in py_func
    return py_func_common(func, inp, Tout, stateful, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 537, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 345, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 149, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()
`

**Comment by wangtianlong1994** [comment]
File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 308, in loadRes
`if type(resFile) == str or type(resFile) == unicode:`
modify
`if type(resFile) == str or type(resFile) == bytes:`

**Comment by lessw2020** [comment]
Thanks very much @wangtianlong1994  - that fixed it!

**Comment by c04022004** [comment]
You probably missed a line in the [tutorial](https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb):

```
# The default pycocotools doesn't work for python3: https://github.com/cocodataset/cocoapi/issues/49
!pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
```

**Comment by lessw2020** [comment]
Thanks @c04022004  - I did blow right past that and on my salamander server I already had the updated pycoco...so it only appeared for me after running in colab. 
Anyway, I've set that as part of the load environ and all good now.  
Thanks for pointing this out and thanks again to @wangtianlong1994  for the code fix as well!
