### ISSUE TITLE
ValueError: Dimensions must be equal, but are 256 and 3 for 'sub' (op: 'Sub') with input shapes: [256,256], [1,1,3].

### ISSUE THREAD

**Issue by xiaopojizu123** [google/automl#208]
step1 ：I use the creat_pascal_tfrecord.py  creat my own dataset. 
step2：And train the model use follow command:
python main.py --mode=train \
    --training_file_pattern=E:/DATA/VOCdevkit*.tfrecord \
    --validation_file_pattern=E:/DATA/VOCdevkit*.tfrecord \
    --val_json_file=E:/DATA/json_VOCdevkit.json \
    --model_name=efficientdet-d0 \
    --model_dir=E:/automl-master/efficientdet/tmp/weight  \
    --train_batch_size=4 \
    --eval_batch_size=4 --eval_samples=512 \
    --num_examples_per_epoch=5717 --num_epochs=1  \
    --hparams="use_bfloat16=false,num_classes=20,moving_average_decay=0" \
    --use_tpu=False
step3：Then inference ，use the setp2 ‘s ckpt file，
python model_inspect.py --runmode=infer --model_name=efficientdet-d0 \
  --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --num_classes=2
  --ckpt_path=E:/automl-master/efficientdet/tmp/weight  --input_image=E:/DATA/test.jpg --output_image_dir=E:/DATA
and the following error occurred 
D:\Anaconda3\python.exe E:/automl-master/efficientdet/model_inspect.py
WARNING:tensorflow:From D:\Anaconda3\lib\site-packages\tensorflow\python\compat\v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-04-11 16:46:51.809423: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2020-04-11 16:46:52.076770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:05:00.0
2020-04-11 16:46:52.077626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:06:00.0
2020-04-11 16:46:52.078474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:09:00.0
2020-04-11 16:46:52.079308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:0a:00.0
2020-04-11 16:46:52.079720: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-11 16:46:52.083833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2020-04-11 16:46:52.084367: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-11 16:46:52.485445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:05:00.0
2020-04-11 16:46:52.486270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:06:00.0
2020-04-11 16:46:52.487091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:09:00.0
2020-04-11 16:46:52.487904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:0a:00.0
2020-04-11 16:46:52.488316: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-11 16:46:52.492062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2020-04-11 16:46:54.613972: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-11 16:46:54.614274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 2 3 
2020-04-11 16:46:54.614455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N N N N 
2020-04-11 16:46:54.614636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   N N N N 
2020-04-11 16:46:54.614817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 2:   N N N N 
2020-04-11 16:46:54.615176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 3:   N N N N 
2020-04-11 16:46:54.618110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9717 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0, compute capability: 5.2)
2020-04-11 16:46:54.620574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9717 MB memory) -> physical GPU (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0, compute capability: 5.2)
2020-04-11 16:46:54.624339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 9717 MB memory) -> physical GPU (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0, compute capability: 5.2)
2020-04-11 16:46:54.627687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 9717 MB memory) -> physical GPU (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:0a:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 256 and 3 for 'sub' (op: 'Sub') with input shapes: [256,256], [1,1,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/automl-master/efficientdet/model_inspect.py", line 384, in <module>
    tf.app.run(main)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "E:/automl-master/efficientdet/model_inspect.py", line 378, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "E:/automl-master/efficientdet/model_inspect.py", line 350, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "E:/automl-master/efficientdet/model_inspect.py", line 228, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "E:\automl-master\efficientdet\inference.py", line 542, in inference
    params['image_size'])
  File "E:\automl-master\efficientdet\inference.py", line 94, in build_inputs
    image, scale = image_preprocess(image, image_size)
  File "E:\automl-master\efficientdet\inference.py", line 70, in image_preprocess
    input_processor.normalize_image()
  File "E:\automl-master\efficientdet\dataloader.py", line 60, in normalize_image
    self._image -= offset
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 11575, in sub
    "Sub", x=x, y=y, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2027, in __init__
    control_input_ops)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 256 and 3 for 'sub' (op: 'Sub') with input shapes: [256,256], [1,1,3].

Process finished with exit code 1
how to solve this problem？ thanks a lot ！

**Comment by egardn33** [comment]
How was this solved?

**Comment by TechnikEmpire** [comment]
@xiaopojizu123 Can you share your solution?

**Comment by TechnikEmpire** [comment]
@egardn33 The issue is solved by ensuring that you pass the same hparams to every phase. Training, evaluation, export, etc. Every one of the scripts has hard-coded hparam values, so once you override them in one place, you have to override them exactly the same way everywhere else.

**Comment by xiaopojizu123** [comment]
> @xiaopojizu123 Can you share your solution?

I change the training datasets，single channel to RGB image.

**Comment by xiaopojizu123** [comment]
> How was this solved?

 sorry!! I forget reply you for so long , see here https://github.com/google/automl/issues/208#issuecomment-625591263

**Comment by juanmanuelrq** [comment]
Hi, how was the solution?, I have the same problem 

`   raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 64 and 4 for 'focal_loss/mul_5' (op: 'Mul') with input shapes: [4,64,64,180], [4,64,64].
`
when I run this code:

`python main.py --mode=train_and_eval \
    --training_file_pattern=/media/inn/Files/d33p/tfrecord/pascal*.tfrecord \
    --validation_file_pattern=/media/inn/Files/d33p/tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=/media/inn/Files/d33p/efficientdet_pascal  \
    --backbone_ckpt=/media/inn/Files/20200617_automl/efficientdet/efficientnet-b0 \
    --train_batch_size=4 \
    --eval_batch_size=4 --eval_samples=56  \
    --num_examples_per_epoch=56  --num_epochs=1  \
    --hparams="num_classes=20,moving_average_decay=0,mixed_precision=true"`
