### ISSUE TITLE
Shape mismatch when running model_inspect.py on a custom dataset

### ISSUE THREAD

**Issue by sx8ac0t6** [google/automl#218]
I encounter a tensor shape mismatch error as below when I run model_inspect.py on my own custom dataset.

Command 1 (--runmode=saved_model):
```
python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d2 --ckpt_path=efficientdet-d2-scratch \
  --input_image_size=1024 --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --saved_model_dir=/tmp/saved_model \
  --num_classes=6
```

Command 2 (--runmode=saved_model_infer):
```
python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d2   --ckpt_path=efficientdet-d2-scratch \
  --input_image_size=1024   --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --saved_model_dir=/tmp/saved_model \
  --input_image=my.jpg --output_image_dir=/tmp/ \
  --line_thickness=4 \
  --num_classes=6
```

Error raised for Command 2:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 884736 values, but the requested shape requires a multiple of 90
	 [[{{node Reshape}}]]
	 [[cond_88/while/Identity/_7860]]
  (1) Invalid argument: Input to reshape is a tensor with 884736 values, but the requested shape requires a multiple of 90
	 [[{{node Reshape}}]]
0 successful operations.
0 derived errors ignored.
```

I suspect that `num_classes` needs to be passed to `inference.ServingDriver` when it is called from `model_inspect.ModelInspector.export_saved_model`. When I add 'num_classes=self.num_classes' to the args passed to `inference.ServingDriver` as below, Command 2 can run successfully.

```
  def export_saved_model(self, **kwargs):
    """Export a saved model for inference."""
    tf.enable_resource_variables()
    driver = inference.ServingDriver(
        self.model_name,
        self.ckpt_path,
        self.image_size,
        num_classes=self.num_classes,
        enable_ema=self.enable_ema)
```

I'd appreciate if you could validate the change and incorporate it in the future release. Thank you.

**Comment by sourabhyadav** [comment]
@mingxingtan  and @sx8ac0t6 Please suggest on #248
