### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.compat.v1.data' has no attribute 'repeat'

### ISSUE THREAD

**Issue by xiaopojizu123** [google/automl#220]
I use the follow command 

python model_inspect.py --runmode=saved_model \
  --model_name=efficientdet-d0 --ckpt_path=r'E:\automl-master\efficientdet\tmp\weight-voc2'\
  --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 \
  --saved_model_dir=E:/automl-master/efficientdet/tmp/saved_model 
 
The following error occurred

Traceback (most recent call last):
  File "F:/automl-master/efficientdet/model_inspect.py", line 384, in <module>
    tf.app.run(main)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "F:/automl-master/efficientdet/model_inspect.py", line 378, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "F:/automl-master/efficientdet/model_inspect.py", line 352, in run_model
    self.export_saved_model(**config_dict)
  File "F:/automl-master/efficientdet/model_inspect.py", line 146, in export_saved_model
    max_boxes_to_draw=kwargs.get('max_boxes_to_draw', 50))
  File "F:\automl-master\efficientdet\inference.py", line 384, in build
    max_boxes_to_draw=max_boxes_to_draw)
  File "F:\automl-master\efficientdet\inference.py", line 209, in det_post_process
    disable_pyfun=params.get('disable_pyfun'))
  File "F:\automl-master\efficientdet\anchors.py", line 598, in generate_detections
    max_boxes_to_draw=max_boxes_to_draw)
  File "F:\automl-master\efficientdet\anchors.py", line 361, in _generate_detections_tf
    lambda id=c, id_cls=indices_cls: _else(detections, id, id_cls))
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1988, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1814, in BuildCondBranch
    original_result = fn()
  File "F:\automl-master\efficientdet\anchors.py", line 361, in <lambda>
    lambda id=c, id_cls=indices_cls: _else(detections, id, id_cls))
  File "F:\automl-master\efficientdet\anchors.py", line 345, in _else
    tf.data.repeat(image_id, tf.size(top_detection_idx)), tf.float32),
AttributeError: module 'tensorflow._api.v1.compat.v1.data' has no attribute 'repeat'

Process finished with exit code 1

I try to upgrade my tf version ，but cudnn version don‘t match， how to solve this problem without upgrade the tf version ？ Thanks a lot ！！

**Comment by sourabhyadav** [comment]
HI @xiaopojizu123 
I am also facing the same issue. Can you please explain how did you resolve this? 
Thanks

**Comment by xiaopojizu123** [comment]
> HI @xiaopojizu123
> I am also facing the same issue. Can you please explain how did you resolve this?
> Thanks

I did't solve this problem,but I used the following method instead:
when you set 
python  main.py  --model=train_and_eval \
                            ----model_dir=/tmp/efficientdet-d0-scratch  \
it will automatically generate the saved model in  `/tmp/efficientdet-d0-scratch/archive ` ，so you can use this saved model to infer. 
Hope it can help you.

**Comment by sourabhyadav** [comment]
> > HI @xiaopojizu123
> > I am also facing the same issue. Can you please explain how did you resolve this?
> > Thanks
> 
> I did't solve this problem,but I used the following method instead:
> when you set
> python main.py --model=train_and_eval
> ----model_dir=/tmp/efficientdet-d0-scratch
> it will automatically generate the saved model in `/tmp/efficientdet-d0-scratch/archive ` ，so you can use this saved model to infer.
> Hope it can help you.

I tried this command of infer, 
```python3 model_inspect.py --runmode=infer --model_name=efficientdet-d1  --ckpt_path=trained_models/efficientdet-d1-scratch_person20/archive --input_image=testimg/1_1_crop_00355.jpg --output_image_dir=testimg/```

It throws the error:
```E0414 09:28:54.674325 139649877100352 checkpoint_management.py:346] Couldn't match files for checkpoint /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/trained_models/efficientdet-d1-scratch_person20/archive/../../../model.ckpt-2856
W0414 09:28:54.684453 139649877100352 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Traceback (most recent call last):
  File "model_inspect.py", line 377, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 371, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 342, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 220, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/inference.py", line 537, in inference
    restore_ckpt(sess, self.ckpt_path, enable_ema=True, export_ckpt=None)
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/inference.py", line 143, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
```  
Any suggestion.

**Comment by yumaofan** [comment]
I have the same error.
