### ISSUE TITLE
Issue on exporting the trained model for inference

### ISSUE THREAD

**Issue by sourabhyadav** [google/automl#221]
Did anyone get below error during the saved model inference command?
 
Step 1: Finetuned d1 on a custom dataset
Trained a model on the custom dataset, with num_class=1. Used Pascal VOC way given in Readme.

Step 2: Export the model for inference
```
python3 model_inspect.py --runmode=saved_model \  
 --model_name=efficientdet-d1 \  
 --ckpt_path=trained_models/efficientdet-d1-scratch_1class \  
--input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 \  
--saved_model_dir=/tmp/saved_model
```  

I get the following error:

```
WARNING: Logging before flag parsing goes to stderr.
W0413 14:42:51.612848 140079773054784 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-04-13 14:42:51.614577: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-13 14:42:51.656438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:17:00.0
2020-04-13 14:42:51.657192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: Quadro P2000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:65:00.0
2020-04-13 14:42:51.657378: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-13 14:42:51.658381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-13 14:42:51.659217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-13 14:42:51.659433: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-13 14:42:51.660487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-13 14:42:51.661290: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-13 14:42:51.663864: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-13 14:42:51.666590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2020-04-13 14:42:51.666906: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-04-13 14:42:51.676075: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4008355000 Hz
2020-04-13 14:42:51.676560: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58c5090 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-13 14:42:51.676589: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-13 14:42:51.893158: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5840190 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-13 14:42:51.893197: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-04-13 14:42:51.893208: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): Quadro P2000, Compute Capability 6.1
2020-04-13 14:42:51.894510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:17:00.0
2020-04-13 14:42:51.895218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: Quadro P2000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:65:00.0
2020-04-13 14:42:51.895268: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-13 14:42:51.895292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-13 14:42:51.895312: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-13 14:42:51.895331: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-13 14:42:51.895349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-13 14:42:51.895370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-13 14:42:51.895394: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-13 14:42:51.900221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2020-04-13 14:42:51.900283: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-13 14:42:51.902475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-13 14:42:51.902494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2020-04-13 14:42:51.902505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N
2020-04-13 14:42:51.902515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N
2020-04-13 14:42:51.904977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10311 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:17:00.0, compute capability: 7.5)
2020-04-13 14:42:51.906113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 4263 MB memory) -> physical GPU (device: 1, name: Quadro P2000, pci bus id: 0000:65:00.0, compute capability: 6.1)
W0413 14:42:51.973446 140079773054784 deprecation.py:323] From /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/dataloader.py:100: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0413 14:42:51.975900 140079773054784 deprecation.py:323] From /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/dataloader.py:102: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0413 14:42:53.495911 140079773054784 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1633: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0413 14:42:57.877375 140079773054784 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/profiler/internal/flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
W0413 14:42:58.204317 140079773054784 deprecation.py:323] From /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/efficientdet_arch.py:95: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0413 14:42:58.204822 140079773054784 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/layers/convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0413 14:42:58.237066 140079773054784 deprecation.py:323] From /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/efficientdet_arch.py:119: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0413 14:42:58.252906 140079773054784 deprecation.py:323] From /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/efficientdet_arch.py:520: separable_conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
W0413 14:43:02.196734 140079773054784 deprecation.py:323] From /data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/det_model_fn.py:316: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Traceback (most recent call last):
  File "model_inspect.py", line 376, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 370, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 344, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 142, in export_saved_model
    max_boxes_to_draw=kwargs.get('max_boxes_to_draw', 50))
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/inference.py", line 381, in build
    max_boxes_to_draw=max_boxes_to_draw)
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/inference.py", line 209, in det_post_process
    disable_pyfun=params.get('disable_pyfun'))
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/anchors.py", line 597, in generate_detections
    max_boxes_to_draw=max_boxes_to_draw)
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/anchors.py", line 361, in _generate_detections_tf
    lambda id=c, id_cls=indices_cls: _else(detections, id, id_cls))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1235, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1061, in BuildCondBranch
    original_result = fn()
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/anchors.py", line 361, in <lambda>
    lambda id=c, id_cls=indices_cls: _else(detections, id, id_cls))
  File "/data/sourabh/Play_n_n_Learn/CV_DL/automl/efficientdet/anchors.py", line 345, in _else
    tf.repeat(image_id, tf.size(top_detection_idx)), tf.float32),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 169, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'repeat'
```  

System setup:
tensorflow-gpu==2.0.0a0
Cuda version: 10.0
Cuda Driver: 440.33
GPU: Nvidia RTX 2080 Ti

How to solve above issue? Please guide.

**Comment by sourabhyadav** [comment]
Below worked for me: 

In anchors.py file, do import:
```from tensorflow.python.ops.ragged.ragged_util import repeat```

and wherever there is ```tf.repeat``` replace it with ```repeat```. It might ask for an additional argument, so please prvide ```axis=0```.
