### ISSUE TITLE
video input

### ISSUE THREAD

**Issue by czy112** [google/automl#243]
How to test video data input？
Has anyone done it, please?

**Comment by WonTaeYeon** [comment]
#43

**Comment by InfiniteLife** [comment]
You should just extract inference code for export model:

```
input_size = 1920
num_classes = hparams_config.get_detection_config(model_name).num_classes
#enable_ema = hparams_config.get_detection_config(model_name).enable_ema
min_score_thresh = 0.2
max_boxes_to_draw = 120
line_thickness = 4

tf.saved_model.load(sess, ['serve'], ckpt_path)

driver = inference.ServingDriver(
                            model_name,
                            ckpt_path,
                            input_size,
                            enable_ema=True)
```
and simply run your own cycle

```
        while True:
            result, frame = vid.read()
            if result is True:
                print('Processing frame: ', counter)
                raw_images = []
                raw_images.append(np.array(frame[:,:,::-1]))
                detections_bs = sess.run('detections:0', {'image_arrays:0': raw_images})
                counter += 1

                for i, detections in enumerate(detections_bs):
                # print('detections[:10]=', detections[:10])
                    img = driver.visualize(raw_images[i], detections,min_score_thresh=0.2,max_boxes_to_draw=120,line_thickness=4)
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break
            else:
                break
```

**Comment by RoboEvangelist** [comment]
> > You should just extract inference code for export model:
> > ```
> > input_size = 1920
> > num_classes = hparams_config.get_detection_config(model_name).num_classes
> > #enable_ema = hparams_config.get_detection_config(model_name).enable_ema
> > min_score_thresh = 0.2
> > max_boxes_to_draw = 120
> > line_thickness = 4
> > 
> > tf.saved_model.load(sess, ['serve'], ckpt_path)
> > 
> > driver = inference.ServingDriver(
> >                             model_name,
> >                             ckpt_path,
> >                             input_size,
> >                             enable_ema=True)
> > ```
> > 
> > 
> > and simply run your own cycle
> > ```
> >         while True:
> >             result, frame = vid.read()
> >             if result is True:
> >                 print('Processing frame: ', counter)
> >                 raw_images = []
> >                 raw_images.append(np.array(frame[:,:,::-1]))
> >                 detections_bs = sess.run('detections:0', {'image_arrays:0': raw_images})
> >                 counter += 1
> > 
> >                 for i, detections in enumerate(detections_bs):
> >                 # print('detections[:10]=', detections[:10])
> >                     img = driver.visualize(raw_images[i], detections,min_score_thresh=0.2,max_boxes_to_draw=120,line_thickness=4)
> >                 if cv2.waitKey(1) & 0xFF == ord('q'):
> >                     break
> >             else:
> >                 break
> > ```
> 
> Hi, @InfiniteLife
> 
> could you please, write the complete code?:
> 
> I am trying this, but I have this error:
> `line 16, in <module> tf.saved_model.load(sess, ['serve'], ckpt_path) NameError: name 'sess' is not defined `
> 
> `
> import hparams_config
> import tensorflow.compat.v1 as tf
> 
> model_name = 'efficientdet-d0'
> ckpt_path = '/home/automl/efficientdet/efficientdet-d0'
> 
> input_size = 1920
> num_classes = hparams_config.get_detection_config(model_name).num_classes
> #enable_ema = hparams_config.get_detection_config(model_name).enable_ema
> min_score_thresh = 0.2
> max_boxes_to_draw = 120
> line_thickness = 4
> 
> tf.saved_model.load(sess, ['serve'], ckpt_path)
> 
> driver = inference.ServingDriver(
> model_name,
> ckpt_path,
> input_size,
> enable_ema=True)
> 
> image_image_path = "/home/sistemasinteligentesmaps/Downloads/DJI_0001.MP4"
> 
> cap = cv2.VideoCapture(image_image_path)
> 
> while True:
> result, frame = vid.read()
> if result is True:
> print('Processing frame: ', counter)
> raw_images = []
> raw_images.append(np.array(frame[:,:,::-1]))
> detections_bs = sess.run('detections:0', {'image_arrays:0': raw_images})
> counter += 1
> 
> ```
>     for i, detections in enumerate(detections_bs):
>     # print('detections[:10]=', detections[:10])
>         img = driver.visualize(raw_images[i], detections,min_score_thresh=0.2,max_boxes_to_draw=120,line_thickness=4)
>     if cv2.waitKey(1) & 0xFF == ord('q'):
>         break
> else:
>     break
> ```
> 
> `

It seems you are missing the session initialization:
`with tf.Session() as sess:`

**Comment by mingxingtan** [comment]
I have updated the README and Tutorial to show how to run inference with video input.

I am going to close this issue for now, but feel free to reopen it if you still have questions or problems.

**Comment by MRLoghmani** [comment]
Hi @mingxingtan ,
I have tried to run the tutorial on the README step-by-step on the suggested input video, but I get the following shape-related error:
```
Invalid argument: Input to reshape is a tensor with 3317760 values, but the requested shape requires a multiple of 21
	 [[{{node Reshape}}]]

```
Here is the full log:

```
2021-05-28 15:01:38.934122: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-28 15:01:40.157450: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-28 15:01:40.160249: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-28 15:01:40.160985: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-05-28 15:01:40.652308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:88:00.0 name: NVIDIA Quadro RTX 6000 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 72 deviceMemorySize: 22.17GiB deviceMemoryBandwidth: 581.23GiB/s
2021-05-28 15:01:40.653204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:89:00.0 name: NVIDIA Quadro RTX 6000 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 72 deviceMemorySize: 22.17GiB deviceMemoryBandwidth: 581.23GiB/s
2021-05-28 15:01:40.654057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 2 with properties: 
pciBusID: 0000:b1:00.0 name: NVIDIA Quadro RTX 6000 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 72 deviceMemorySize: 22.17GiB deviceMemoryBandwidth: 581.23GiB/s
2021-05-28 15:01:40.654882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 3 with properties: 
pciBusID: 0000:b2:00.0 name: NVIDIA Quadro RTX 6000 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 72 deviceMemorySize: 22.17GiB deviceMemoryBandwidth: 581.23GiB/s
2021-05-28 15:01:40.654915: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-28 15:01:40.656702: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-05-28 15:01:40.656765: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-05-28 15:01:40.657493: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-05-28 15:01:40.657702: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-05-28 15:01:40.659413: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-05-28 15:01:40.659819: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-05-28 15:01:40.659966: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-05-28 15:01:40.666259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1, 2, 3
2021-05-28 15:01:40.666289: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-05-28 15:01:42.036286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-28 15:01:42.036340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 2 3 
2021-05-28 15:01:42.036347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N Y Y Y 
2021-05-28 15:01:42.036351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   Y N Y Y 
2021-05-28 15:01:42.036370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 2:   Y Y N Y 
2021-05-28 15:01:42.036374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 3:   Y Y Y N 
2021-05-28 15:01:42.041564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21045 MB memory) -> physical GPU (device: 0, name: NVIDIA Quadro RTX 6000, pci bus id: 0000:88:00.0, compute capability: 7.5)
2021-05-28 15:01:42.043591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 21045 MB memory) -> physical GPU (device: 1, name: NVIDIA Quadro RTX 6000, pci bus id: 0000:89:00.0, compute capability: 7.5)
2021-05-28 15:01:42.045481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 21045 MB memory) -> physical GPU (device: 2, name: NVIDIA Quadro RTX 6000, pci bus id: 0000:b1:00.0, compute capability: 7.5)
2021-05-28 15:01:42.047364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 21045 MB memory) -> physical GPU (device: 3, name: NVIDIA Quadro RTX 6000, pci bus id: 0000:b2:00.0, compute capability: 7.5)
WARNING:tensorflow:From /data/mohammad/repos/efficientdet/efficientdet/inference.py:546: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W0528 15:01:42.050496 139750432184128 deprecation.py:339] From /data/mohammad/repos/efficientdet/efficientdet/inference.py:546: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
2021-05-28 15:01:44.595043: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-05-28 15:01:45.152637: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3100000000 Hz
2021-05-28 15:01:47.780892: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-05-28 15:01:49.395144: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-05-28 15:01:49.766262: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 3317760 values, but the requested shape requires a multiple of 21
	 [[{{node Reshape}}]]
	 [[strided_slice_18/_2871]]
  (1) Invalid argument: Input to reshape is a tensor with 3317760 values, but the requested shape requires a multiple of 21
	 [[{{node Reshape}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 471, in run_model
    **config_dict)
  File "model_inspect.py", line 241, in saved_model_video
    detections_bs = driver.serve_images(raw_frames)
  File "/data/mohammad/repos/efficientdet/efficientdet/inference.py", line 530, in serve_images
    feed_dict={self.signitures['image_arrays']: image_arrays})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 3317760 values, but the requested shape requires a multiple of 21
	 [[node Reshape (defined at /data/mohammad/repos/efficientdet/efficientdet/inference.py:546) ]]
	 [[strided_slice_18/_2871]]
  (1) Invalid argument: Input to reshape is a tensor with 3317760 values, but the requested shape requires a multiple of 21
	 [[node Reshape (defined at /data/mohammad/repos/efficientdet/efficientdet/inference.py:546) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'Reshape':
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 471, in run_model
    **config_dict)
  File "model_inspect.py", line 221, in saved_model_video
    driver.load(self.saved_model_dir)
  File "/data/mohammad/repos/efficientdet/efficientdet/inference.py", line 546, in load
    saved_model_dir_or_frozen_graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 340, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 300, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 453, in load
    **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 383, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1485, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/meta_graph.py", line 804, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 538, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 513, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3680, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3680, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3561, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()
````
