### ISSUE TITLE
Issue in custom trained model: tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 225 values, but the requested shape requires a multiple of 20

### ISSUE THREAD

**Issue by sourabhyadav** [google/automl#248]
1. I finetuned a model with 1-class using coco tfrecord style.
2. Exported the model:
```
python3 model_inspect.py --num_classes 1 \  
 --hparams="use_bfloat16=false,num_classes=1,moving_average_decay=0,enable_ema=False"   \  
--runmode=saved_model  --model_name=efficientdet-d1 --ckpt_path=trained_models/efficientdet-d1-scratch_coco_1class_5epoch/model.ckpt-856  \  
--saved_model_dir=coco_model_export
```
3. Inference the saved model:
```python3 model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d1 --ckpt_path=trained_models/efficientdet-d1-scratch_coco_1class_5epoch/model.ckpt-856 --saved_model_dir=coco_model_export --num_classes 1 --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2  --line_thickness=4  --hparams="use_bfloat16=false,num_classes=1,moving_average_decay=0,enable_ema=False" --input_image=img.png --output_image_dir=coco_model_export```

I get this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 225 values, but the requested shape requires a multiple of 20
         [[{{node Reshape_8}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 390, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 384, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 361, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 163, in saved_model_inference
    detections_bs = sess.run('detections:0', {'image_arrays:0': raw_images})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 225 values, but the requested shape requires a multiple of 20
         [[node Reshape_8 (defined at model_inspect.py:159) ]]

Original stack trace for 'Reshape_8':
  File "model_inspect.py", line 390, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 384, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 361, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 159, in saved_model_inference
    tf.saved_model.load(sess, ['serve'], self.saved_model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/meta_graph.py", line 797, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 513, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3459, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3459, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3347, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()
```

I tried #218 but it did not help.

**Comment by DamGameHero** [comment]
Hi @sourabhyadav,
There is no flag `--hparams` in model_inspect.py.
Maybe try `--enable_ema=False` when exporting the model.

**Comment by sourabhyadav** [comment]
> Hi @sourabhyadav,
> There is no flag `--hparams` in model_inspect.py.
> Maybe try `--enable_ema=False` when exporting the model.

Thanks for pointing the mistake out. It worked.

**Comment by danirisdiandita** [comment]
I got the same error but now we don't have `--enable_ema` flag anymore
