### ISSUE TITLE
I could made pb file but could not infer with it

### ISSUE THREAD

**Issue by co2rico** [google/automl#283]
My status for now is below.
1. trained well and the could infer with the trained ckpt
2. exported pb file but could infer with the pb file

So I want to get correct pb file and infer with it.

I hope I can get some advise to solve this issue.

<environment>
windows 10
tensorflow 1 , tensorflow 2

----[log] make saved_mode -------------------------------------------------------------------------

(tensorflow) C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet>python model_inspect.py --runmode=saved_model --model_name=efficientdet-d2 --ckpt_path=./tmp/ckpt-254 --input_image_size=1920 --max_boxes_to_draw=100   --min_score_thresh=0.2 --saved_model_dir=./tmp/saved_model --num_classes=1
2020-04-20 17:34:39.451172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-04-20 17:35:14.980259: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-04-20 17:35:15.000676: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-20 17:35:15.070481: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-4K9SHLH
2020-04-20 17:35:15.089327: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-4K9SHLH
2020-04-20 17:35:15.119525: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\dataloader.py:100: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0420 17:35:15.278134  9660 deprecation.py:323] From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\dataloader.py:100: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\dataloader.py:102: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0420 17:35:15.285820  9660 deprecation.py:323] From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\dataloader.py:102: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0420 17:35:18.956191  9660 deprecation.py:506] From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\profiler\internal\flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
W0420 17:35:30.604042  9660 deprecation.py:323] From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\profiler\internal\flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
WARNING:tensorflow:From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\efficientdet_arch.py:94: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0420 17:35:32.095865  9660 deprecation.py:323] From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\efficientdet_arch.py:94: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\layers\convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0420 17:35:32.103848  9660 deprecation.py:323] From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\layers\convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\efficientdet_arch.py:121: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0420 17:35:32.213550  9660 deprecation.py:323] From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\efficientdet_arch.py:121: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
WARNING:tensorflow:From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\efficientdet_arch.py:516: separable_conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.
W0420 17:35:32.293337  9660 deprecation.py:323] From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\efficientdet_arch.py:516: separable_conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
WARNING:tensorflow:From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\det_model_fn.py:316: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0420 17:35:45.024325  9660 deprecation.py:323] From C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet\det_model_fn.py:316: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0420 17:36:24.508257  9660 deprecation.py:323] From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\saved_model\signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
W0420 17:39:11.619870  9660 deprecation.py:323] From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\saved_model\signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.

(tensorflow) C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet>

----[log] infer with saved_mode -------------------------------------------------------------------------

(tensorflow) C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet>python model_inspect.py --runmode=saved_model_infer --model_name=efficientdet-d2   --ckpt_path=./ckpt-254  --input_image_size=1920  --max_boxes_to_draw=100   --min_score_thresh=0.2  --line_thickness=4 --saved_model_dir=./tmp/saved_model   --input_image=./bb-01.jpg  --output_image_dir=./imgout_export  --num_classes=1
2020-04-20 17:49:38.900888: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-04-20 17:52:53.716606: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-04-20 17:52:53.738429: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-20 17:52:53.816457: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-4K9SHLH
2020-04-20 17:52:53.834092: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-4K9SHLH
2020-04-20 17:52:53.882260: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From model_inspect.py:148: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W0420 17:52:53.955446 16252 deprecation.py:323] From model_inspect.py:148: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Traceback (most recent call last):
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2025 values, but the requested shape requires a multiple of 90
         [[{{node Reshape_8}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 376, in <module>
    tf.app.run(main)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\jslee\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\jslee\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 370, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 347, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 152, in saved_model_inference
    detections_bs = sess.run('detections:0', {'image_arrays:0': raw_images})
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2025 values, but the requested shape requires a multiple of 90
         [[node Reshape_8 (defined at C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'Reshape_8':
  File "model_inspect.py", line 376, in <module>
    tf.app.run(main)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\jslee\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\jslee\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 370, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 347, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 148, in saved_model_inference
    tf.saved_model.load(sess, ['serve'], self.saved_model_dir)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 422, in load
    **saver_kwargs)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3561, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\jslee\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

(tensorflow) C:\EfficientDet-tensorflow_google_automl-master_20200406_park_d2_only\efficientdet>

**Comment by co2rico** [comment]
I could solve this with a new version of the code.
Thanks a lot.
