### ISSUE TITLE
TensorRT error in efficientdet-d1

### ISSUE THREAD

**Issue by itsliupeng** [google/automl#300]
Hi @mingxingtan 
It runs ok using TensorRT in d0, but failed in d1 and d2...
Have you succeeded in running d1 using TensorRT?

env:  nvdia ngc docker tensoflow 20:03, cuda 10.2 , tf 2.1

> export MODEL=efficientdet-d0
> python model_inspect.py --runmode=bm --model_name=$MODEL --ckpt_path=ckpt/$MODEL --input_image_size 512x512 --bm_runs 1000 --warmup_runs 20 --tensorrt FP32 

> export MODEL=efficientdet-d1
> python model_inspect.py --runmode=bm --model_name=$MODEL --ckpt_path=ckpt/$MODEL --input_image_size 640x640 --bm_runs 1000 --warmup_runs 20  --tensorrt FP32

```
2020-04-23 19:21:41.184419: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2020-04-23 19:21:41.184566: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger INVALID_STATE: std::exception
2020-04-23 19:21:41.184595: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger INVALID_CONFIG: Deserialize the cuda engine failed.
2020-04-23 19:21:41.186341: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-23 19:21:41.189141: E tensorflow/stream_executor/cuda/cuda_dnn.cc:330] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-04-23 19:21:41.191894: E tensorflow/stream_executor/cuda/cuda_dnn.cc:330] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-04-23 19:21:41.192049: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at trt_engine_op.cc:318 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node fpn_cells/cell_1/fnode6/op_after_combine11/conv/separable_conv2d/depthwise}}]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node fpn_cells/cell_1/fnode6/op_after_combine11/conv/separable_conv2d/depthwise}}]]
	 [[import/Identity_2/_3657]]

During handling of the above exception, another exception occurred:
```

**Comment by suhyung-code42** [comment]
@itsliupeng  Have you solved the problem?
