### ISSUE TITLE
Add custom label for visualisation

### ISSUE THREAD

**Issue by bessszilard** [google/automl#334]
Where can I add custom labels for the visualization?
I didn't find any flags in model_inspect.py for this purpose. I realized that this is related to the `label_id_mapping` variable in inference.py, but I don't know how can I modify this with flags.

**Comment by mingxingtan** [comment]
you can save your label into a yaml file, such as new_label.yaml:

      1: cat
      2: dog

then you can pass in a flag like this:

--hparams='label_id_mapping=new_label.yaml'

**Comment by bessszilard** [comment]
Thanks for help @mingxingtan. I generated 'classes.yaml' file, with this content:
```
	1: RedStraightLeft
	2: Red
	3: GreenStraight
	4: GreenLeft
	5: Green
	6: GreenStraightLeft
	7: Yellow
	8: off
	9: RedLeft
	10: RedStraight
	11: GreenRight
	12: RedRight
	13: GreenStraightRight
```

And I called the model_inspect.py with this command:
```bash
$ python model_inspect.py --runmode=saved_model \
  --model_name={MODEL} --ckpt_path=/content/tmp/model_dir/efficientdet-d0-finetune/model.ckpt-24190 \
  --input_image_size=1280x720 --saved_model_dir={saved_model_dir} \
  --min_score_thresh=0.2 \
  --hparams='/content/classes.yaml' 
```

And I received this error:
```bash
2020-05-01 09:11:35.570918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "model_inspect.py", line 467, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 449, in main
    hparams=FLAGS.hparams)
  File "model_inspect.py", line 100, in __init__
    model_config.override(hparams)  # Add custom overrides
  File "/content/automl/efficientdet/hparams_config.py", line 110, in override
    self._update(config_dict, allow_new_keys=False)
  File "/content/automl/efficientdet/hparams_config.py", line 75, in _update
    raise KeyError('Key `{}` does not exist for overriding. '.format(k))
KeyError: 'Key `1` does not exist for overriding. '

```

**Comment by bessszilard** [comment]
Thanks for you help @mingxingtan. I created the `classes.yaml` file with this content:

```json
	1: RedStraightLeft
	2: Red
	3: GreenStraight
	4: GreenLeft
	5: Green
	6: GreenStraightLeft
	7: Yellow
	8: off
	9: RedLeft
	10: RedStraight
	11: GreenRight
	12: RedRight
	13: GreenStraightRight
```

I called the `model_inspect.py` file with this command:
```bash
!python model_inspect.py --runmode=saved_model \
  --model_name={MODEL} --ckpt_path=/content/tmp/model_dir/efficientdet-d0-finetune/model.ckpt-24190 \
  --input_image_size=1280x720 --saved_model_dir={saved_model_dir} \
  --min_score_thresh=0.2 \
  --hparams='num_classes=11,moving_average_decay=0,label_id_mapping=/content/classes.yaml' 
```

I received this error:
```bash
2020-05-01 09:31:46.291048: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "model_inspect.py", line 467, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 449, in main
    hparams=FLAGS.hparams)
  File "model_inspect.py", line 100, in __init__
    model_config.override(hparams)  # Add custom overrides
  File "/content/automl/efficientdet/hparams_config.py", line 98, in override
    config_dict = self.parse_from_yaml(config_dict_or_str)
  File "/content/automl/efficientdet/hparams_config.py", line 127, in parse_from_yaml
    config_dict = yaml.load(f, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: num_classes=11,moving_average_decay=0,label_id_mapping=/content/classes.yaml; No such file or directory
```

The `classes.yaml` path is valid, because:
```
$realpath classes.yaml
/content/classes.yaml
```

What causes the error?

**Comment by mingxingtan** [comment]
It was a bug, if the hparams ends with "yaml, it would treat the entire string as a file. You can use this for now (just add a ',' at the end of hparams"

    hparams='num_classes=11,moving_average_decay=0,label_id_mapping=/content/classes.yaml,' 

I will try to find a better solution later.

**Comment by mingxingtan** [comment]
Your original command should also work now.
