### ISSUE TITLE
eval error: TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by xiaopojizu123** [google/automl#385]
I trained my own datasets, it can work. But when i turn the mode to eval `mode=eval`,it can't work. The eval data use file `create_pascal_tfrecord.py`  created.  how can i solve it ? thanks!

2020-05-08 16:28:05.816585: W tensorflow/core/framework/op_kernel.cc:1643] Invalid argument: TypeError: object of type <class 'numpy.float64'> canno
t be safely interpreted as an integer.
Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
    ret = func(*args)

  File "E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py", line 136, in _evaluate
    coco_eval = COCOeval(self.coco_gt, coco_dt, iouType='bbox')

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)

  File "<__array_function__ internals>", line 6, in linspace

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))

TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

INFO:tensorflow:evaluation_loop marked as finished
I0508 16:28:06.091087 12468 error_handling.py:108] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0508 16:28:06.092084 12468 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 1367, in _do_call
    return fn(*args)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
    ret = func(*args)

  File "E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py", line 136, in _evaluate
    coco_eval = COCOeval(self.coco_gt, coco_dt, iouType='bbox')

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)

  File "<__array_function__ internals>", line 6, in linspace

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))

TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

         [[{{node coco_metric/PyFunc_1}}]]
         [[coco_metric/PyFunc_1/_5669]]
  (1) Invalid argument: TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
    ret = func(*args)

  File "E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py", line 136, in _evaluate
    coco_eval = COCOeval(self.coco_gt, coco_dt, iouType='bbox')

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)

  File "<__array_function__ internals>", line 6, in linspace

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))

TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

         [[{{node coco_metric/PyFunc_1}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 400, in <module>
    tf.app.run(main)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\anaconda3\envs\ssj\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\anaconda3\envs\ssj\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 329, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3056, in evaluate
    rendezvous.raise_errors()
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "D:\anaconda3\envs\ssj\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3051, in evaluate
    name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 484, in evaluate
    name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 526, in _actual_eval
    return _evaluate()
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 515, in _evaluate
    output_dir=self.eval_dir(name))
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1622, in _evaluate_run
    config=self._session_config)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\training\evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 885, in __exit__
    self._close_internal(exception_type)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 918, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\training\basic_session_run_hooks.py", line 959, in end
    self._final_ops, feed_dict=self._final_ops_feed_dict)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 960, in run
    run_metadata_ptr)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 1361, in _do_run
    run_metadata)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\client\session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
    ret = func(*args)

  File "E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py", line 136, in _evaluate
    coco_eval = COCOeval(self.coco_gt, coco_dt, iouType='bbox')

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)

  File "<__array_function__ internals>", line 6, in linspace

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))

TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

         [[node coco_metric/PyFunc_1 (defined at E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py:220) ]]
         [[coco_metric/PyFunc_1/_5669]]
  (1) Invalid argument: TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
    ret = func(*args)

  File "E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py", line 136, in _evaluate
    coco_eval = COCOeval(self.coco_gt, coco_dt, iouType='bbox')

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()

  File "D:\anaconda3\envs\ssj\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)

  File "<__array_function__ internals>", line 6, in linspace

  File "D:\anaconda3\envs\ssj\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))

TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

         [[node coco_metric/PyFunc_1 (defined at E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py:220) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'coco_metric/PyFunc_1':
  File "main.py", line 400, in <module>
    tf.app.run(main)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\anaconda3\envs\ssj\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\anaconda3\envs\ssj\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 329, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3051, in evaluate
    name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 484, in evaluate
    name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 526, in _actual_eval
    return _evaluate()
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 508, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1514, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1550, in _call_model_fn_eval
    features, labels, ModeKeys.EVAL, config)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1152, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2005, in _call_model_fn
    return estimator_spec.as_estimator_spec()
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 379, in as_estimator_spec
    host_call_ret = _OutfeedHostCall.create_cpu_hostcall(host_calls)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 2080, in create_cpu_hostcall
    ret[name] = host_fn(**tensors)
  File "E:\automl-master-5.7-agu\automl-master\efficientdet\det_model_fn.py", line 571, in metric_fn
    params['val_json_file'], **kwargs)
  File "E:\automl-master-5.7-agu\automl-master\efficientdet\det_model_fn.py", line 420, in coco_metric_fn
    kwargs['groundtruth_data'])
  File "E:\automl-master-5.7-agu\automl-master\efficientdet\coco_metric.py", line 220, in estimator_metric_fn
    metrics = tf.py_func(_evaluate, [], tf.float32)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 516, in py_func
    return py_func_common(func, inp, Tout, stateful, name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 498, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 321, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\ops\gen_script_ops.py", line 149, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "D:\anaconda3\envs\ssj\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by iamastar88** [comment]
The numpy version problem, you can change the version or set 'int'.

**Comment by zishanahmed08** [comment]
You missed these line in the tutorial


# The default pycocotools doesn't work for python3: https://github.com/cocodataset/cocoapi/issues/49
!pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

**Comment by xiaopojizu123** [comment]
> You missed these line in the tutorial
> 
> # The default pycocotools doesn't work for python3: [cocodataset/cocoapi#49](https://github.com/cocodataset/cocoapi/issues/49)
> !pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

thanks!!

**Comment by mingxingtan** [comment]
I assume upgrading pycocotools should have solved your problem. closing this issue now.

**Comment by dev-srikanth** [comment]
> The numpy version problem, you can change the version or set 'int' in np.linspace

I have the same issue, which numpy version would work?
i'm using 1.18.1 numpy version

**Comment by almajeas** [comment]
Issue is not with numpy. 
as indicated above, you may install the following package to get it to work

> You missed these line in the tutorial
> 
> # The default pycocotools doesn't work for python3: [cocodataset/cocoapi#49](https://github.com/cocodataset/cocoapi/issues/49)
> !pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
