### ISSUE TITLE
Invalid argument: scores has incompatible shape

### ISSUE THREAD

**Issue by wojiaohumaocheng** [google/automl#430]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: scores has incompatible shape
	 [[{{node non_max_suppression_with_scores/NonMaxSuppressionV5}}]]
	 [[non_max_suppression_with_scores/NonMaxSuppressionV5/_2757]]
  (1) Invalid argument: scores has incompatible shape
	 [[{{node non_max_suppression_with_scores/NonMaxSuppressionV5}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 491, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 485, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 444, in run_model
    kwargs['input_image'], kwargs['output_image_dir'], **config_dict)
  File "model_inspect.py", line 184, in saved_model_inference
    detections_bs = driver.serve_images(raw_images)
  File "/data/humaocheng/object_detection/EffecientDet_tf/automl-master/efficientdet/inference.py", line 672, in serve_images
    feed_dict={self.signitures['image_arrays']: image_arrays})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: scores has incompatible shape
	 [[node non_max_suppression_with_scores/NonMaxSuppressionV5 (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[non_max_suppression_with_scores/NonMaxSuppressionV5/_2757]]
  (1) Invalid argument: scores has incompatible shape
	 [[node non_max_suppression_with_scores/NonMaxSuppressionV5 (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.

**Comment by BruceZane1** [comment]
I encountered same issue. Looking for some help.

**Comment by mingxingtan** [comment]
Hi @wojiaohumaocheng and @BruceZane1 What's the command line to reproduce the issue?

**Comment by wojiaohumaocheng** [comment]
I have exported the savedModel and frozen graph successfully, then I run this command ``python3.5 model_inspect.py --runmode=saved_model_video --input_video=videos/IMG_1432.mov --model_name=efficientdet-d4 --saved_model_dir=saved_model_dir_d4 --output_video=output.mov. Could you help me solve this problem, please? thx

**Comment by wojiaohumaocheng** [comment]
我已经成功导出了saveModel和冻结图，然后运行以下命令`python3.5 model_inspect.py --runmode = saved_model_video --input_video = videos / IMG_1432.mov --model_name = efficientdet-d4 --saved_model_dir = saved_model_dir_d4- -output_video = output.mov`。您能帮我解决这个问题吗？谢谢

**Comment by wojiaohumaocheng** [comment]
> Hi @wojiaohumaocheng and @BruceZane1 What's the command line to reproduce the issue? I have exported saved_model and frozen graph successfully
, and run this command `python3.5 model_inspect.py --runmode=saved_model_video --input_video=videos/IMG_1432.mov --model_name=efficientdet-d4 --saved_model_dir=saved_model_dir_d4 --output_video=output.mov
` could u help me solve this problem? thx

**Comment by mingxingtan** [comment]
Hmm, this is a strange error. I tried to run this command on README with the testing video and it worked well.
Do you retrain your model with custom dataset? If so, you need to specify the same hparams for inference and training.

**Comment by BruceZane1** [comment]
> Hmm, this is a strange error. I tried to run this command on README with the testing video and it worked well.
> Do you retrain your model with custom dataset? If so, you need to specify the same hparams for inference and training.

I retrained with custom dataset and used mostly the same command line as  @wojiaohumaocheng  did. Hparams such as num_classes, moving_average_decay, image_size are kept same for both inference and training. What else shoud I pay attention to?

**Comment by ml5ah** [comment]
1. Go to inference.py and update the label id mapping according to your dataset
2. Give the voc_config.yaml file as a parameter to model_inspect.py the same way you do for training in main.py

**Comment by tricoffee** [comment]
File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  scores has incompatible shape
         [[node NonMaxSuppressionV5 (defined at load.py:18) ]]
  (1) Invalid argument:  scores has incompatible shape
         [[node NonMaxSuppressionV5 (defined at load.py:18) ]]
         [[NonMaxSuppressionV5/_45]]
