### ISSUE TITLE
Box IOU loss keeps zeros with custom dataset

### ISSUE THREAD

**Issue by hzhuangdy** [google/automl#455]
Hi,

I've trained the network using my own dataset for just 5 classes and I realize that the Box IOU loss on my tensorboard keeps zero like following.

All the setting remains the default setting in the repo. I just create the tfrecords.

The config is shown below:
CUDA_VISIBLE_DEVICES=0 python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord_with_sign/*.tfrecord \
    --validation_file_pattern=tfrecord_with_sign/*.tfrecord \
    --val_json_file=tfrecord_with_sign/json_pascal.json \
    --model_name=efficientdet-d2 \
    --model_dir=./tmp/efficientdet-d2-scratch-sign  \
    --backbone_ckpt=efficientdet-d2 \
    --train_batch_size=4 \
    --eval_batch_size=4 --eval_samples=608  \
    --num_examples_per_epoch=2800 --num_epochs=100
    --hparams=voc_config.yaml

![image](https://user-images.githubusercontent.com/36788357/83212995-92993500-a193-11ea-9cc1-a3cb79ac86b5.png)

**Comment by lyjslay** [comment]
same problem as yours

**Comment by mingxingtan** [comment]
This is expected, because no iou_loss is used in default (iou_loss is controlled by this flag: https://github.com/google/automl/blob/aff52f6fac580607d0982fcc2bd2747d33115fa1/efficientdet/hparams_config.py#L218)

I realized this is a little confusing, so I have removed iou_loss from tensorboard if iou_loss is not used. If you checkout the latest code, then box_iou_loss will not show up.

**Comment by DamGameHero** [comment]
Hello,

The code change created a problem on my side when I use iou_loss:

> I0602 12:11:19.479657 140491180799808 utils.py:394] Adding scale summary ('trainloss/reg_l2_loss', <tf.Tensor 'mul_425:0' shape=() dtype=float32>)
I0602 12:11:19.480292 140491180799808 utils.py:394] Adding scale summary ('trainloss/loss', <tf.Tensor 'add_50:0' shape=() dtype=float32>)
INFO:tensorflow:training_loop marked as finished
I0602 12:11:19.480943 140491180799808 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0602 12:11:19.481034 140491180799808 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "main.py", line 420, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 386, in main
    steps=int(FLAGS.num_examples_per_epoch / FLAGS.train_batch_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1211, in _train_model_default
    self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2915, in _call_model_fn
    config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1170, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3173, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/app/automl/efficientdet/det_model_fn.py", line 692, in efficientdet_model_fn
    variable_filter_fn=variable_filter_fn)
  **File "/app/automl/efficientdet/det_model_fn.py", line 503, in _model_fn
    if box_iou_loss:**
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 778, in __bool__
    self._disallow_bool_casting()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 548, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 537, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

The problem seems to be here:
https://github.com/google/automl/commit/aff52f6fac580607d0982fcc2bd2747d33115fa1#diff-986b5b50be6fcaa9c77b338bca7148f7R503-R504

I'm using iou_loss, so I deleted this line for a quick fix:
https://github.com/google/automl/blob/aff52f6fac580607d0982fcc2bd2747d33115fa1/efficientdet/det_model_fn.py#L503
