### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: efficientdet-d0

### ISSUE THREAD

**Issue by mkhoshle** [google/automl#467]
I need to export the model and get `.pb` file of the trained model and I do the following:
```
!rm  -rf savedmodeldir
!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
  --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite
```

But I get this error and I am not sure how to resolve it. Can someone please tell me what I need to do to resolve this?

```
WARNING:tensorflow:From /Users/mahzadkhoshlessan/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow_core/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0602 12:06:52.240016 4582165952 deprecation.py:323] From /Users/mahzadkhoshlessan/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow_core/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Traceback (most recent call last):
  File "model_inspect.py", line 490, in <module>
    app.run(main)
  File "/Users/mahzadkhoshlessan/miniconda3/envs/ml/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/mahzadkhoshlessan/miniconda3/envs/ml/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 437, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 146, in export_saved_model
    driver.build()
  File "/Users/mahzadkhoshlessan/Desktop/automl/efficientdet/inference.py", line 576, in build
    export_ckpt=None)
  File "/Users/mahzadkhoshlessan/Desktop/automl/efficientdet/inference.py", line 206, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "/Users/mahzadkhoshlessan/miniconda3/envs/ml/lib/python3.5/site-packages/tensorflow_core/python/training/saver.py", line 1282, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: efficientdet-d0
```

**Comment by mingxingtan** [comment]
Looks like it says it cannot find the checkpoint file. You need to download the ckpt and put into the folder specified by --ckpt_path=

**Comment by mkhoshle** [comment]
> Looks like it says it cannot find the checkpoint file. You need to download the ckpt and put into the folder specified by --ckpt_path=

Thank you!
