### ISSUE TITLE
ExponentialMovingAverage not found in checkpoint 

### ISSUE THREAD

**Issue by adarsh0906** [google/automl#472]
i finetuned my model and used those checkpoint for creating a pb file for video inference but when trying to create pb file i get this error

python model_inspect.py --runmode=saved_model --model_name=efficientdet-d1 --ckpt_path=Model/ --saved_model_dir=Model/savedmodel  --enable_ema=False
2020-06-03 17:40:02.575032: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
FATAL Flags parsing error: Unknown command line flag 'enable_ema'
Pass --helpshort or --helpfull to see help on flags.

D:\vehicle detection and counting\efficientdet>python model_inspect.py --runmode=saved_model --model_name=efficientdet-d1 --ckpt_path=Model/ --saved_model_dir=Model/savedmodel
2020-06-03 17:59:14.690288: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-06-03 17:59:25.322485: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-03 17:59:25.333180: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-03 17:59:25.657375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce 820M major: 2 minor: 1 memoryClockRate(GHz): 1.25
pciBusID: 0000:08:00.0
2020-06-03 17:59:25.682047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-06-03 17:59:25.711540: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-06-03 17:59:25.741022: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-06-03 17:59:25.764397: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-06-03 17:59:25.797880: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-06-03 17:59:25.827648: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-06-03 17:59:25.853482: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-06-03 17:59:25.882304: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-03 17:59:26.050608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-03 17:59:26.068699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-06-03 17:59:26.084927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
W0603 17:59:28.511603  1460 deprecation.py:506] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0603 17:59:35.341945  1460 deprecation.py:323] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\profiler\internal\flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
W0603 17:59:35.974794  1460 deprecation.py:323] From D:\vehicle detection and counting\efficientdet\efficientdet_arch.py:138: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0603 17:59:35.974794  1460 deprecation.py:323] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\layers\convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0603 17:59:36.028191  1460 deprecation.py:323] From D:\vehicle detection and counting\efficientdet\efficientdet_arch.py:164: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0603 17:59:36.075082  1460 deprecation.py:323] From D:\vehicle detection and counting\efficientdet\efficientdet_arch.py:682: separable_conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
W0603 17:59:46.178686  1460 deprecation.py:323] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
2020-06-03 18:00:16.105994: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[node save/RestoreV2 (defined at C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 148, in export_saved_model
    driver.build()
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 574, in build
    export_ckpt=None)
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 198, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 148, in export_saved_model
    driver.build()
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 574, in build
    export_ckpt=None)
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 204, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[node save/RestoreV2 (defined at C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 148, in export_saved_model
    driver.build()
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 574, in build
    export_ckpt=None)
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 198, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by Samjith888** [comment]
```
 num_classes: 20
  moving_average_decay: 0
```

add the above values into voc_config.yaml

**Comment by adarsh0906** [comment]
python model_inspect.py --runmode=saved_model --model_name=efficientdet-d1 --ckpt_path=Model/ --saved_model_dir=Model/savedmodel --hparams="num_classes=4,moving_average_decay=0"
2020-06-04 08:28:50.749850: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-06-04 08:30:18.286054: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-04 08:30:19.010543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-04 08:30:19.813886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce 820M major: 2 minor: 1 memoryClockRate(GHz): 1.25
pciBusID: 0000:08:00.0
2020-06-04 08:30:19.851154: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-06-04 08:30:20.187596: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-06-04 08:30:20.486298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-06-04 08:30:20.632077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-06-04 08:30:20.951583: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-06-04 08:30:21.150502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-06-04 08:30:21.188659: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-06-04 08:30:21.210094: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-04 08:30:21.472382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-04 08:30:21.493462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-06-04 08:30:21.508504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
W0604 08:30:25.235597 20540 deprecation.py:506] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0604 08:30:32.095798 20540 deprecation.py:323] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\profiler\internal\flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
W0604 08:30:33.220010 20540 deprecation.py:323] From D:\vehicle detection and counting\efficientdet\efficientdet_arch.py:138: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0604 08:30:33.220010 20540 deprecation.py:323] From C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\layers\convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0604 08:30:33.289018 20540 deprecation.py:323] From D:\vehicle detection and counting\efficientdet\efficientdet_arch.py:164: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0604 08:30:33.320275 20540 deprecation.py:323] From D:\vehicle detection and counting\efficientdet\efficientdet_arch.py:682: separable_conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
2020-06-04 08:30:50.810561: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key efficientnet-b1/blocks_0/conv2d/kernel not found in checkpoint
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key efficientnet-b1/blocks_0/conv2d/kernel not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key efficientnet-b1/blocks_0/conv2d/kernel not found in checkpoint
         [[node save/RestoreV2 (defined at C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 148, in export_saved_model
    driver.build()
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 574, in build
    export_ckpt=None)
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 198, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 148, in export_saved_model
    driver.build()
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 574, in build
    export_ckpt=None)
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 204, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key efficientnet-b1/blocks_0/conv2d/kernel not found in checkpoint
         [[node save/RestoreV2 (defined at C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Program Files\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 148, in export_saved_model
    driver.build()
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 574, in build
    export_ckpt=None)
  File "D:\vehicle detection and counting\efficientdet\inference.py", line 198, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()



i get this error i didn't add voc_config.yaml but i changed that in arguments itself

**Comment by mingxingtan** [comment]
You new log says "Key efficientnet-b1/blocks_0/conv2d/kernel not found in checkpoint".

Could you inspect your model to make sure it is indeed efficientdet-d1? (see this diiscussion on how to inspect checkpoint: https://stackoverflow.com/questions/41867191/how-does-one-inspect-variables-in-a-checkpoint-file-in-tensorflow-when-tensorflo)

**Comment by adarsh0906** [comment]
i couldn't use that to inspect my checkpoint 

and this is how i trained my model  in colab 


!python main.py --mode=train \
    --training_file_pattern=tfrecord/{file_pattern} \
    --validation_file_pattern=tfrecord/{file_pattern} \
    --val_json_file=tfrecord/json_pascal.json \
    --model_name={MODEL} \
    --model_dir=model_dir/{MODEL}-finetune \
    --ckpt={MODEL} \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples={images_per_epoch}  \
    --num_examples_per_epoch={images_per_epoch}  --num_epochs=2  \
    --hparams="num_classes=4,moving_average_decay=0" \
    --use_tpu=False

**Comment by adarsh0906** [comment]
> 
> 
> You new log says "Key efficientnet-b1/blocks_0/conv2d/kernel not found in checkpoint".
> 
> Could you inspect your model to make sure it is indeed efficientdet-d1? (see this diiscussion on how to inspect checkpoint: https://stackoverflow.com/questions/41867191/how-does-one-inspect-variables-in-a-checkpoint-file-in-tensorflow-when-tensorflo)

yes you are right the model is trained for d0 i used d1 in the argument
