### ISSUE TITLE
Win10: model_inspect error

### ISSUE THREAD

**Issue by github2016-yuan** [google/automl#473]
I am now in Win10 and I can run main.py very well. But when I run model_inspect.py,I get some error

Traceback (most recent call last):
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 35, in <module>
    import inference
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 42, in <module>
    from tensorflow.python.compiler.tensorrt import trt
ImportError: cannot import name **'trt'** from 'tensorflow.python.compiler.tensorrt' (D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\compiler\tensorrt\__init__.py)

So I do some changes in **inference.py**:
(1)line41: replace from tensorflow.python.compiler.tensorrt import trt 
                with **from tensorflow.python.compiler.tensorrt import trt_convert_windows**
(2)line747: replace  with trt.create_inference_graph(
                with **trt_convert_windows.create_inference_graph(**

In my opinion, trt_convert_windows is prepared for wins while trt is suitable for Linux.

Then I run model_inspect.py again.
It seems right at the beginning but then I get another error:

Parsing Inputs...
Incomplete shape.
Incomplete shape.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
...
...
2020-06-04 11:41:56.810133: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-04 11:41:56.810223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-06-04 11:41:56.810312: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
...
...
2020-06-04 11:42:04.583424: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-06-04 11:42:04.583515: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-04 11:42:04.583607: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: cond_21_true_7606
2020-06-04 11:42:04.583940: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-06-04 11:42:04.584033: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-04 11:42:04.584122: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: cond_692_true_18342
2020-06-04 11:42:04.584209: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-04 11:42:04.584298: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-04 11:42:04.584387: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: cond_399_true_13654
...
...
coreClock: 1.7845GHz coreCount: 15 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.66GiB/s
2020-06-04 11:42:06.880482: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-04 11:42:06.880575: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-06-04 11:42:06.880669: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-06-04 11:42:06.880968: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-06-04 11:42:06.881057: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-06-04 11:42:06.881145: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-06-04 11:42:06.881235: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-06-04 11:42:06.881558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-04 11:42:06.881667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-04 11:42:06.881763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-04 11:42:06.881819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-04 11:42:06.882112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6307 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-06-04 11:42:06.995842: E tensorflow/core/grappler/grappler_item_builder.cc:668] Init node efficientnet-b0/stem/conv2d/kernel/Assign doesn't exist in graph
Traceback (most recent call last):
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 490, in <module>
    app.run(main)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 437, in run_model
    self.export_saved_model(**config_dict)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 147, in export_saved_model
    driver.export(self.saved_model_dir, self.tflite_path, self.tensorrt)
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 747, in export
    trt_convert_windows.create_inference_graph(
AttributeError: module 'tensorflow.python.compiler.tensorrt.trt_convert_windows' has no attribute '**create_inference_graph**'

From info above, trt_convert_windows can not replace trt, but I can only import trt_convert_windows  in wins. Hope someone can give me some advice.

Here is part of **trt_convert_windows .py**
from tensorflow.python.util.tf_export import tf_export

if platform.system() != "Windows":
  raise RuntimeError(
      "This module is expected to be loaded only on **Windows platform**.")

class TrtPrecisionMode(object):
  FP32 = "FP32"
  FP16 = "FP16"
  INT8 = "INT8"

**Comment by mingxingtan** [comment]
I did not realized that trt has different libraries for windows and linux. I have make trt import optional now, and your issue should be gone.
