### ISSUE TITLE
Error when applying different aspect ratios and anchor_scale

### ISSUE THREAD

**Issue by Samjith888** [google/automl#475]
voc_config.yaml
```
num_classes: 1
moving_average_decay: 0
aspect_ratios: [(0.6, 1.6), (0.8, 1.3), (1.0, 1.0)]
anchor_scale: 5.0
```
command used :
`python main.py --mode=train_and_eval \--training_file_pattern=tfrecord/pascal*.tfrecord \--validation_file_pattern=tfrecord/pascal*.tfrecord  \--model_name=efficientdet-d0 --model_dir=checkpoints --ckpt=efficientdet-d0  --train_batch_size=16 --eval_batch_size=16 --eval_samples=12000 --num_examples_per_epoch=25000 --num_epochs=10000  --hparams="voc_config.yaml"`

While finetune from coco ckpt by using above --hparams="voc_config.yaml"  , i got the following error
```


WARNING:tensorflow:Reraising captured error
W0604 18:33:47.288236 140142279071552 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "main.py", line 420, in <module>
    app.run(main)
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 386, in main
    steps=int(FLAGS.num_examples_per_epoch / FLAGS.train_batch_size))
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1044, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/home/samjith/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in _call_input_fn
    return input_fn(**kwargs)
  File "/samjith/project/mpc/efficientdet_d0/dataloader.py", line 252, in __call__
    params['image_size'])
  File "/samjith/project/mpc/efficientdet_d0/anchors.py", line 459, in __init__
    self.boxes = self._generate_boxes()
  File "/samjith/project/mpc/efficientdet_d0/anchors.py", line 470, in _generate_boxes
    self.config)
  File "/samjith/project/mpc/efficientdet_d0/anchors.py", line 236, in _generate_anchor_boxes
    anchor_size_x_2 = base_anchor_size_x * aspect[0] / 2.0
TypeError: can't multiply sequence by non-int of type 'float'
```
Questions:

1) How to solve this ? (run without error when edit it in the hparams_config.py file)
2)  Is it possible to add a list of values as anchor scale instead of one ?(anchor_sclae: [0.4,0.518,0.671])

Note: i have anchors which are very  small

**Comment by mingxingtan** [comment]
Hi @Samjith888 

This is because yaml doesn't support tuple, you can simply change tuples to list as follows:

```
num_classes: 1
moving_average_decay: 0
aspect_ratios: [[0.6, 1.6], [0.8, 1.3], [1.0, 1.0]]
anchor_scale: 5.0
```

**Comment by Samjith888** [comment]
> Hi @Samjith888
> 
> This is because yaml doesn't support tuple, you can simply change tuples to list as follows:
> 
> ```
> num_classes: 1
> moving_average_decay: 0
> aspect_ratios: [[0.6, 1.6], [0.8, 1.3], [1.0, 1.0]]
> anchor_scale: 5.0
> ```

How to pass more anchor_scale ?

eg : 

`anchor_scale : [0.4, 1.5, 3.1,4.0]`

**Comment by Samjith888** [comment]
> > Hi @Samjith888
> > This is because yaml doesn't support tuple, you can simply change tuples to list as follows:
> > ```
> > num_classes: 1
> > moving_average_decay: 0
> > aspect_ratios: [[0.6, 1.6], [0.8, 1.3], [1.0, 1.0]]
> > anchor_scale: 5.0
> > ```
> 
> How to pass multiple anchor_scales ?
> 
> eg :
> 
> `anchor_scale : [0.4, 1.5, 3.1,4.0]`

@mingxingtan @fsx950223  any suggestions please
