### ISSUE TITLE
Train voc data well, model_inspect error

### ISSUE THREAD

**Issue by github2016-yuan** [google/automl#478]
I use **main.py** to train voc data for just one epoch.
**cmd line**:
--mode=train_and_eval   	--training_file_pattern=mytfrecord/pascal/*.tfrecord     --validation_file_pattern=mytfrecord/pascal/*.tfrecord     --model_name=efficientdet-d0     --model_dir=./tmp/efficientdet-d0-scratch  \     --backbone_ckpt=efficientnet-b0     --train_batch_size=8      --eval_batch_size=4 --eval_samples=1024     --num_examples_per_epoch=5717 --num_epochs=1   --hparams="num_classes=20,moving_average_decay=0"
Then I get some files in /tmp/efficientdet-d0-scratch
(1)checkpoint
(2)ckpt file

Next I use **model_inspect.py** to get pb file:
--runmode=saved_model --model_name=efficientdet-d0 \   --ckpt_path=./tmp/efficientdet-d0-scratch --saved_model_dir=savedmodeldir \   --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite

However I get some errors：
Parsing Inputs...
Incomplete shape.
Incomplete shape.
3 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
Incomplete shape.
WARNING:tensorflow:From D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0605 17:22:14.296783 17172 deprecation.py:323] From D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
2020-06-05 17:22:27.561866: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
Traceback (most recent call last):
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_79]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 1299, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at F:\PythonProgram\automl-master\efficientdet\inference.py:1037) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at F:\PythonProgram\automl-master\efficientdet\inference.py:1037) ]]
	 [[save/RestoreV2/_79]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 490, in <module>
    app.run(main)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 437, in run_model
    self.export_saved_model(**config_dict)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 146, in export_saved_model
    driver.build()
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 1393, in build
    export_ckpt=None)
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 1037, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 836, in __init__
    self.build()
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 886, in _build
    build_restore=build_restore)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 336, in _AddRestoreOps
    restore_sequentially)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1506, in restore_v2
    name=name)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\framework\ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\framework\ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 1309, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 1627, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 74, in get_tensor
    error_translator(e)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 490, in <module>
    app.run(main)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 437, in run_model
    self.export_saved_model(**config_dict)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 146, in export_saved_model
    driver.build()
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 1393, in build
    export_ckpt=None)
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 1043, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 1315, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at F:\PythonProgram\automl-master\efficientdet\inference.py:1037) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at F:\PythonProgram\automl-master\efficientdet\inference.py:1037) ]]
	 [[save/RestoreV2/_79]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 490, in <module>
    app.run(main)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Softwares\Python3.7.3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 437, in run_model
    self.export_saved_model(**config_dict)
  File "F:/PythonProgram/automl-master/efficientdet/model_inspect.py", line 146, in export_saved_model
    driver.build()
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 1393, in build
    export_ckpt=None)
  File "F:\PythonProgram\automl-master\efficientdet\inference.py", line 1037, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 836, in __init__
    self.build()
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 886, in _build
    build_restore=build_restore)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 336, in _AddRestoreOps
    restore_sequentially)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\training\saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1506, in restore_v2
    name=name)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\framework\ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "D:\Softwares\Python3.7.3\lib\site-packages\tensorflow\python\framework\ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

I fork the code this week and It should be the lastest version and the bug should fix in #168 and other problems  that are similar to mine but I still run into the question.

I almost check all the issues about it:#20,#319,#472 ... 

I then use the file here https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/efficientdet-d0.tar.gz
  instead of mine(checkpoint,ckpt files)
and I run the order again in **model_inspect.py**
--runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
  --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite

It works and I get **pb** file and frozen file in savedmodeldir. and the pb file can be used to infer.

It seems there is something wrong in my training voc data with d0. But I do get checkpoint and ckpt file after training. So it really confuses me.
Hope someone give me some advice about it ?

ps:flowchart
main.py->**checkpoint/ckpt file**->model_inspect.py-> **pb file**

**Comment by Samjith888** [comment]
create a voc_config.yaml file and add following content into it

```
 num_classes: 20
  moving_average_decay: 0
```

Add `--hparams='voc_config.yaml' i`nto your command


@mingxingtan @fsx950223  Please add  the above into the README.md

**Comment by mingxingtan** [comment]
Thanks @Samjith888   Updated README

**Comment by github2016-yuan** [comment]
@Samjith888 
Thanks，I test your solution and it really works and in voc_config.yaml file:
num_classes: 20
moving_average_decay: 0

No space required in line 2. 
More info can be found [https://github.com/google/automl/blob/master/efficientdet/README.md#8-finetune-on-pascal-voc-2012-with-detector-coco-ckpt](url)

**Comment by BernardinD** [comment]
I tried this. No luck

**Comment by danielTobon43** [comment]
@BernardinD same for me. I got `moving_average_decay: 0` and the output is  now:
`
2021-09-28 20:58:51.122438: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Not found: Key box_net/box-0-bn-3/beta not found in checkpoint`
