### ISSUE TITLE
Sequence of commands to infer custom image

### ISSUE THREAD

**Issue by ifahim** [google/automl#483]
I followed Colab ipython notebook and it works perfect on the COCO data. However, I am having issues with finetuning on my custom data with 7 classes. This is my sequence of commands:

```
MODEL = 'efficientdet-d0'
!python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/train-*.tfrecord  \
    --validation_file_pattern=tfrecord/valid-*.tfrecord  \
    --model_name={MODEL} \
    --model_dir=/tmp/model_dir/{MODEL}-finetune \
    --ckpt={MODEL} \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples={images_per_epoch}  \
    --num_examples_per_epoch={images_per_epoch}  --num_epochs=5  \
    --hparams="num_classes=8,moving_average_decay=0,precision=mixed_float16"
```

Lots of checkpointfiles are generated in the dir : `model_dir/efficientdet-d0-finetune/`. I can also see the learning graph in tensorboard using the following command:
%load_ext tensorboard
%tensorboard --logdir /tmp/model_dir/{MODEL}-finetune/

I am confused in the next steps. 

```
saved_model_dir = 'savedmodel'
!rm -rf {savedmodel}
!rm  -rf savedmodeldir
!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=model_dir/{MODEL}-finetune --saved_model_dir=savedmodeldir \
  --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite

```
I assume that the above command is correct but I keep getting error:

```
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.
Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 490, in <module>
    app.run(main)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 437, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 146, in export_saved_model
    driver.build()
  File "/mnt/sda1/intel_challenge/automl/efficientdet/inference.py", line 576, in build
    export_ckpt=None)
  File "/mnt/sda1/intel_challenge/automl/efficientdet/inference.py", line 200, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 836, in __init__
    self.build()
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 886, in _build
    build_restore=build_restore)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 336, in _AddRestoreOps
    restore_sequentially)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1506, in restore_v2
    name=name)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fahim/anaconda3/envs/automl/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  .....
....
....


```

For inference I am using this: 

```
!python model_inspect.py --runmode=saved_model_infer \
  --model_name= <<????What should be this entry????>> \
  --saved_model_dir= <<????What should be this entry????>> \
  --input_image=ep.jpg --output_image_dir=serve_image_out
```

Also, How to get the bounding boxes  from the holdout/test test*.tfrecord?

**Comment by Samjith888** [comment]
create a voc_config.yaml file and add following content into it

```
 num_classes: 20
  moving_average_decay: 0
```

Add `--hparams='voc_config.yaml' ` into your command

**Comment by fsx950223** [comment]
I assume that you know that you should change model dir when you train a new model?

**Comment by mingxingtan** [comment]
Yes, @Samjith888 is right, you need to use the same hparams for training and eval: specifically, since you training with moving_average_decay=0.0, there is no EMA variables in the checkpoints, but during eval, you did not set moving_average_decay=0.0, so it tries to read EMA variables, causing this error.

The simple way is to create a voc_config.yaml file, and use it for both training and eval.

@fsx950223 looks like he indeed specify a new model_dir.

**Comment by ifahim** [comment]
@Samjith888  and @mingxingtan, Thanks. It worked for me.

**Comment by fsx950223** [comment]
> Yes, @Samjith888 is right, you need to use the same hparams for training and eval: specifically, since you training with moving_average_decay=0.0, there is no EMA variables in the checkpoints, but during eval, you did not set moving_average_decay=0.0, so it tries to read EMA variables, causing this error.
> 
> The simple way is to create a voc_config.yaml file, and use it for both training and eval.
> 
> @fsx950223 looks like he indeed specify a new model_dir.

Wht moving_average_decay=0 when finetune VOC dataset.

**Comment by Samjith888** [comment]
> > Yes, @Samjith888 is right, you need to use the same hparams for training and eval: specifically, since you training with moving_average_decay=0.0, there is no EMA variables in the checkpoints, but during eval, you did not set moving_average_decay=0.0, so it tries to read EMA variables, causing this error.
> > The simple way is to create a voc_config.yaml file, and use it for both training and eval.
> > @fsx950223 looks like he indeed specify a new model_dir.
> 
> Why set moving_average_decay=0 when finetune VOC dataset.

Then what value should assign for `moving_average_decay`

**Comment by fsx950223** [comment]
> > > Yes, @Samjith888 is right, you need to use the same hparams for training and eval: specifically, since you training with moving_average_decay=0.0, there is no EMA variables in the checkpoints, but during eval, you did not set moving_average_decay=0.0, so it tries to read EMA variables, causing this error.
> > > The simple way is to create a voc_config.yaml file, and use it for both training and eval.
> > > @fsx950223 looks like he indeed specify a new model_dir.
> > 
> > 
> > Why set moving_average_decay=0 when finetune VOC dataset.
> 
> Then what value should assign for `moving_average_decay`

Is it something wrong with default moving_average_decay when the repo trains with VOC dataset. Could it keep same with other train scripts?
