### ISSUE TITLE
got this error when training

### ISSUE THREAD

**Issue by qtw1998** [google/automl#495]
```shell
INFO:tensorflow:examples/sec: 22.5404
I0610 01:14:19.767547 46924377788096 tpu_estimator.py:2351] examples/sec: 22.5404
INFO:tensorflow:global_step/sec: 3.42475
I0610 01:14:20.058923 46924377788096 tpu_estimator.py:2350] global_step/sec: 3.42475
INFO:tensorflow:examples/sec: 23.9733
I0610 01:14:20.059304 46924377788096 tpu_estimator.py:2351] examples/sec: 23.9733
INFO:tensorflow:training_loop marked as finished
I0610 01:14:31.062654 46924377788096 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0610 01:14:31.063207 46924377788096 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 430, in <module>
    app.run(main)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 287, in main
    FLAGS.train_batch_size))
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1518, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
	 [[node IteratorGetNext (defined at /cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py:61) ]]

Errors may have originated from an input operation.
Input Source operations connected to node IteratorGetNext:
 IteratorV2 (defined at /cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py:59)

Original stack trace for 'IteratorGetNext':
  File "main.py", line 430, in <module>
    app.run(main)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 287, in main
    FLAGS.train_batch_size))
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1044, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py", line 61, in parse_input_fn_result
    result = iterator.get_next()
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 427, in get_next
    name=name)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2377, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/cluster/home/qiaotianwei/.conda/envs/TF2-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()
``

**Comment by centerseed** [comment]
Check or re-generate tfrecords? Maybe data is corrupt in your tfrecords file.

**Comment by qtw1998** [comment]
> Check or re-generate tfrecords? Maybe data is corrupt in your tfrecords file.

THX bro
