### ISSUE TITLE
Inference with frozen pb of d4, Key Error "The name 'image_arrays:0' refers to a Tensor which does not exist.

### ISSUE THREAD

**Issue by fishyboy** [google/automl#512]
Python version 3.6
TF version 2.2.0

with this command i successfully freezed my ckpt of D4
```
!python model_inspect.py --runmode=freeze --model_name={MODEL} \
  --ckpt_path={model_dir}/{MODEL}-finetune --saved_model_dir={model_dir}/ \
  --freeze --logdir={model_dir}/freeze/ --hparams=voc.yaml
```
then 

```
!python model_inspect.py --runmode=saved_model_infer \
  --model_name={MODEL}\
  --ckpt_path={model_dir}/efficientdet-d4-finetune/ \
  --input_image=demo12/*_detections.jpg \
  --hparams=voc.yaml  \
  --output_image_dir={output_image_dir} \
  --saved_model_dir=efficientdet-d4_frozen.pb
```
it turned out:
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3512, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3554, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'image_arrays:0' refers to a Tensor which does not exist. The operation, 'image_arrays', does not exist in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 490, in <module>
    app.run(main)
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 484, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 443, in run_model
    kwargs['output_image_dir'], **config_dict)
  File "model_inspect.py", line 179, in saved_model_inference
    detections_bs = driver.serve_images(raw_images)
  File "automl/efficientdet/inference.py", line 648, in serve_images
    feed_dict={self.signitures['image_arrays']: image_arrays})
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'image_arrays:0' refers to a Tensor which does not exist. The operation, 'image_arrays', does not exist in the graph.
```

with pycharm i saw the problem was 

```
  File "automl/efficientdet/inference.py", line 648, in serve_images
predictions = self.sess.run(
        self.signitures['prediction'],
        feed_dict={self.signitures['image_arrays']: image_arrays})
```
and
 ```
File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    e.args[0])

    if feed_dict:
      feed_dict = nest.flatten_dict_items(feed_dict)
      for feed, feed_val in feed_dict.items():
        for subfeed, subfeed_val in _feed_fn(feed, feed_val):
          try:
            subfeed_t = self.graph.as_graph_element(
                subfeed, allow_tensor=True, allow_operation=False)
#with subfeed = 'image_arrays:0'
```
subfeed_t is executed in  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py",
```
         op_name='image_arrays'
        if op_name in self._nodes_by_name:
          op = self._nodes_by_name[op_name]
        else:
          raise KeyError("The name %s refers to a Tensor which does not "
                         "exist. The operation, %s, does not exist in the "
                         "graph." % (repr(name), repr(op_name))) 
```

and i inspected self._nodes_by_name, it was a dict of d4 components, which didnt contain 'image_arrays'. so what should i do to make this frozen pb work?

**Comment by fishyboy** [comment]
![2020-06-13 20-46-17屏幕截图](https://user-images.githubusercontent.com/12840061/84569165-fbe58e80-adb6-11ea-8939-9a68d18d65f4.png)

**Comment by fishyboy** [comment]
voc.yaml
`num_classes: 5
#var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_id_mapping: {0: background, 1: x, 2: xx, 3: xxx, 4: xxxx, 5: xxxxx}
moving_average_decay: 0
precision: mixed_float16
`

**Comment by fishyboy** [comment]
Ok. 
solved with this....
```
!python model_inspect.py --runmode=saved_model --model_name={MODEL} \
  --ckpt_path={model_dir}/{MODEL}-finetune --saved_model_dir={model_dir}/saved_model/ \
  --freeze --logdir={model_dir}/freeze/ --hparams=voc.yaml
```
