### ISSUE TITLE
Follow-up on autoaugment TPU training

### ISSUE THREAD

**Issue by InfiniteLife** [google/automl#525]
@fsx950223 I've testet latest tfa-nightly with your commit merged, fixing this issue https://github.com/google/automl/issues/480 and error is gone, but now I get

```
INFO:tensorflow:Init TPU system
I0617 17:09:53.674150 140377180415808 tpu_estimator.py:574] Init TPU system
INFO:tensorflow:Initialized TPU in 32 seconds
I0617 17:10:26.114439 140377180415808 tpu_estimator.py:584] Initialized TPU in 32 seconds
INFO:tensorflow:Starting infeed thread controller.
I0617 17:10:36.958653 140375550838528 tpu_estimator.py:525] Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
I0617 17:10:36.959266 140375542445824 tpu_estimator.py:545] Starting outfeed thread controller.
I0617 17:10:37.009667 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:Enqueue next (100) batch(es) of data to infeed.
I0617 17:10:48.320188 140377180415808 tpu_estimator.py:611] Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
I0617 17:10:48.320544 140377180415808 tpu_estimator.py:615] Dequeue next (100) batch(es) of data from outfeed.
I0617 17:11:07.154403 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
I0617 17:11:37.300654 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
I0617 17:12:07.445211 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
I0617 17:12:37.599487 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
I0617 17:13:07.740534 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
I0617 17:13:37.891060 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:Outfeed finished for iteration (0, 0)
I0617 17:14:05.891885 140375542445824 tpu_estimator.py:283] Outfeed finished for iteration (0, 0)
I0617 17:14:08.031660 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
I0617 17:14:38.181715 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:Outfeed finished for iteration (0, 79)
I0617 17:15:06.407342 140375542445824 tpu_estimator.py:283] Outfeed finished for iteration (0, 79)
I0617 17:15:08.331468 140375534053120 transport.py:157] Attempting refresh to obtain initial access_token
ERROR:tensorflow:Closing session due to error From /job:worker/replica:0/task:0:
 output dimensions must be positive
         [[{{node parser/cond_33/then/_296/cond_1/then/_1089/cond/else/_1/while/body/_34/cond/then/_114/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
         [[input_pipeline_task0/while/body/_10/IteratorGetNext]]
E0617 17:15:19.121912 140375525660416 error_handling.py:95] Closing session due to error From /job:worker/replica:0/task:0:
 output dimensions must be positive
         [[{{node parser/cond_33/then/_296/cond_1/then/_1089/cond/else/_1/while/body/_34/cond/then/_114/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
         [[input_pipeline_task0/while/body/_10/IteratorGetNext]]
INFO:tensorflow:training_loop marked as finished
I0617 17:15:21.907338 140377180415808 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0617 17:15:21.907822 140377180415808 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:worker/replica:0/task:0:
{{function_node __inference_Dataset_map__dataset_parser_10729}} output dimensions must be positive
         [[{{node parser/cond_33/then/_296/cond_1/then/_1089/cond/else/_1/while/body/_34/cond/then/_114/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
         [[input_pipeline_task0/while/body/_10/IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 278, in main
    FLAGS.train_batch_size))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 123, in catch_errors
    yield
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 541, in _run_infeed
    session.run(self._enqueue_ops)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:worker/replica:0/task:0:
 output dimensions must be positive
         [[{{node parser/cond_33/then/_296/cond_1/then/_1089/cond/else/_1/while/body/_34/cond/then/_114/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
         [[input_pipeline_task0/while/body/_10/IteratorGetNext]]
```

Seem like it does a few iterations but then encounters this error. I use tf 2.2 and augmentation policy = v1. Do you have any ideas how to fix it?

**Comment by fsx950223** [comment]
You could open an issue on tensorflow community.

**Comment by Koteswara-ML** [comment]
Hey did this issue got solved , I am also facing the same issue while training it on TPU.
