### ISSUE TITLE
TensorFlow Lite currently doesn't support control flow ops: 

### ISSUE THREAD

**Issue by tiru1930** [google/automl#531]
I have trained efficientdet on custom data, i want to convert this model tf-lite

i have trained model using tensorflow=1.15.0 and when i tried to convert the forzen graph with below mentioned code

> TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ADD_N, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, DIV, EQUAL, EXP, EXPAND_DIMS, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MEAN, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, SHAPE, SQUEEZE, STRIDED_SLICE, SUB, TILE, UNPACK. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, DecodeBmp, DecodeGif, DecodeJpeg, DecodePng, IdentityN, LoopCond, Reciprocal, Substr, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
Traceback (most recent call last):
  File "/home/tiru/anaconda3/envs/edet/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ADD_N, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, DIV, EQUAL, EXP, EXPAND_DIMS, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MEAN, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, SHAPE, SQUEEZE, STRIDED_SLICE, SUB, TILE, UNPACK. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, DecodeBmp, DecodeGif, DecodeJpeg, DecodePng, IdentityN, LoopCond, Reciprocal, Substr, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.

```
import tensorflow as tf

gf = tf.GraphDef() 
m_file = open('/tmp/model/efficientdet-d0_frozen.pb','rb')
gf.ParseFromString(m_file.read())

with open('somefile.txt', 'a') as the_file:
    for n in gf.node:
        the_file.write(n.name+'\n')

file = open('somefile.txt','r')
data = file.readlines()
input_arrays = data[0].replace("\n","").strip()
output_arrays = data[-1].replace("\n","").strip()
print(input_arrays)
print(output_arrays)

model_pb_path = "/tmp/model/efficientdet-d0_frozen.pb"
converter = tf.lite.TFLiteConverter.from_frozen_graph(model_pb_path, [input_arrays], [output_arrays])
# converter.experimental_new_converter = True
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

tflite_model_path = "/tmp/model/efficientdet-d0_frozen.tflite"

with open(tflite_model_path, 'wb') as f:
	f.write(tflite_model)

```

**Comment by cam145** [comment]
maybe you can install tf-nightly for test. It worked for me.

**Comment by tiru1930** [comment]
@cam145  

I still see the issue with tf-nightly

```

Traceback (most recent call last):
  File "model_inspect.py", line 492, in <module>
    app.run(main)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 486, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 439, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 149, in export_saved_model
    driver.export(self.saved_model_dir, tflite_path=self.tflite_path)
  File "/home/tiru/Desktop/thinkdeeply/efficientdet-google/efficientdet/inference.py", line 730, in export
    tflite_model = converter.convert()
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1932, in convert
    return super(TFLiteConverter, self).convert()
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1292, in convert
    **converter_kwargs)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 560, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 188, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: Dimension size must be evenly divisible by 90 but is 73728 for '{{node Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](class_net/class-predict/BiasAdd, Reshape/shape)' with input shapes: [1,64,64,18], [3] and with input tensors computed as partial shapes: input[1] = [1,?,90]./home/tiru/anaconda3/envs/edet/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py:299:0: error: 
```

**Comment by mingxingtan** [comment]
@tiru1930 Could you try this command: https://github.com/google/automl/tree/master/efficientdet#3-export-savedmodel-frozen-graph-tensort-models-or-tflite?

**Comment by tiru1930** [comment]
@mingxingtan  

Above mentioned issue is due to number of classes which i have modified according to my custom trained model.

but after that change using below command i have other issues something like 

 <unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):

```
!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
  --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite
```

so i have again modified tf_lite converter code  to below 

```
+      supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]

```
with this change i was able to convert to tflite , but now i have some other issues while invoking with tflite_runtime

```
Traceback (most recent call last):
  File "handler_test.py", line 32, in <module>
    autodetection_model = efficientdetDetector()
  File "/home/tiru/Desktop/thinkdeeply/td-efficientdet-lambda/efficientdet/efficientdet_detector.py", line 71, in __init__
    self.model = EfficientdetGraph(model_config)
  File "/home/tiru/Desktop/thinkdeeply/td-efficientdet-lambda/efficientdet/efficientdet.py", line 20, in __init__
    self.tf_interpreter = self.load_tflite(self.saved_model_dir)
  File "/home/tiru/Desktop/thinkdeeply/td-efficientdet-lambda/efficientdet/efficientdet.py", line 25, in load_tflite
    model.allocate_tensors()
  File "/home/tiru/Desktop/thinkdeeply/td-efficientdet-lambda/tflite_runtime/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/tiru/Desktop/thinkdeeply/td-efficientdet-lambda/tflite_runtime/interpreter_wrapper.py", line 115, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 260 (FlexMul) failed to prepare.
```

**Comment by fsx950223** [comment]
You should try it with cpp interpreter.

**Comment by joepalermo** [comment]
@tiru1930 any luck with this? I am having the same issue.
