### ISSUE TITLE
i try to train with my own data ,but after i change the num_classes,i got an error : lhs shape= [1,1,64,126] rhs shape= [1,1,64,810]

### ISSUE THREAD

**Issue by ljq19940913** [google/automl#537]
I guess this error maybe need to change some output shape,but i could't find it.

python main.py --mode=train_and_eval     --training_file_pattern=tfrecord/car*.tfrecord  --validation_file_pattern=tfrecord/car*.tfrecord   --val_json=tfrecord/json_car.json   --model_name=efficientdet-d0     --model_dir=./d0voc    --backbone_ckpt=efficientnet-b0     --train_batch_size=4     --eval_batch_size=4   --eval_samples=512     --num_examples_per_epoch=12000   --num_epochs=10    --hparams="use_bfloat16=false,num_classes=14,moving_average_decay=0"    --use_tpu=False

Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,64,126] rhs shape= [1,1,64,810]
         [[{{node save/Assign_227}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,64,126] rhs shape= [1,1,64,810]
         [[node save/Assign_227 (defined at main.py:364) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_227:
 class_net/class-predict/pointwise_kernel/Momentum (defined at /home/zhangyuchen/automl-master/efficientdet/det_model_fn.py:518)

Original stack trace for 'save/Assign_227':
  File "main.py", line 396, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 364, in main
    steps=int(FLAGS.num_examples_per_epoch / FLAGS.train_batch_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2871, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1192, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1480, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 584, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)

**Comment by mingxingtan** [comment]
It is most likely your model_dir "d0voc" contains some pretrained models with 90 classes.
If you delete d0voc, and retrain them, it should be fine.

**Comment by ljq19940913** [comment]
> It is most likely your model_dir "d0voc" contains some pretrained models with 90 classes.
> If you delete d0voc, and retrain them, it should be fine.

it's work！
