### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [ERROR: please increase config.max_instances_per_image] [Condition x < y did not hold element-wise:] [x (parser/strided_slice_18:0) = ] [101] [y (parser/assert_less_1/y:0) = ] [100] 	 [[{{node parser/assert_less_1/Assert/Assert}}]] 	 [[IteratorGetNext]]

### ISSUE THREAD

**Issue by xiaoxin05** [google/automl#561]
Hello, everybody.I met some problems, I hope you can help me, thank you，the problem as follows：
**1）my environment：ubuntu18.04 + tensorlfow-gpu2.00 + run in doubel gtx1080ti（6G），but i don‘t use multi gpu mode**
**2）Detailed questions：**
ERROR:tensorflow:Error recorded from training_loop:  assertion failed: [ERROR: please increase config.max_instances_per_image] [Condition x < y did not hold element-wise:] [x (parser/strided_slice_18:0) = ] [101] [y (parser/assert_less_1/y:0) = ] [100]
	 [[{{node parser/assert_less_1/Assert/Assert}}]]
	 [[IteratorGetNext]]
E0702 19:34:30.361719 139939770799936 error_handling.py:75] Error recorded from training_loop:  assertion failed: [ERROR: please increase config.max_instances_per_image] [Condition x < y did not hold element-wise:] [x (parser/strided_slice_18:0) = ] [101] [y (parser/assert_less_1/y:0) = ] [100]
	 [[{{node parser/assert_less_1/Assert/Assert}}]]
	 [[IteratorGetNext]]
INFO:tensorflow:training_loop marked as finished
I0702 19:34:30.361928 139939770799936 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0702 19:34:30.362042 139939770799936 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map__dataset_parser_1108}} assertion failed: [ERROR: please increase config.max_instances_per_image] [Condition x < y did not hold element-wise:] [x (parser/strided_slice_18:0) = ] [101] [y (parser/assert_less_1/y:0) = ] [100]
	 [[{{node parser/assert_less_1/Assert/Assert}}]]
	 [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/automl/efficientdet/main.py", line 421, in <module>
    app.run(main)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/automl/efficientdet/main.py", line 278, in main
    FLAGS.train_batch_size))
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1194, in _train_model_default
    saving_listeners)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1493, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/anaconda3/envs/EfficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [ERROR: please increase config.max_instances_per_image] [Condition x < y did not hold element-wise:] [x (parser/strided_slice_18:0) = ] [101] [y (parser/assert_less_1/y:0) = ] [100]
	 [[{{node parser/assert_less_1/Assert/Assert}}]]
	 [[IteratorGetNext]]
**3）I run the command：** 
--mode=train --training_file_pattern=tfrecord/-*-of-00100.tfrecord  --model_name=efficientdet-d0 --model_dir="/home/automl/efficientdet/model_7_finetune"  --ckpt="/home/automl/efficientdet/model_save_7.2/efficientdet-d0"  --train_batch_size=4  --num_examples_per_epoch=2500 --num_epochs=100  --hparams="num_classes=2,moving_average_decay=0,mixed_precision=true"
4）my custom dataset
It contains 2500 training images and one class，but one image have many object（Maybe 60 to 80 objects）

**Comment by Samjith888** [comment]
Seems like u are using old repo.. clone new repo and add ‘ MAX_NUM_INSTANCE’ into the voc_config accordionists to ur dataset

https://github.com/google/automl/blob/master/efficientdet/hparams_config.py#L197

**Comment by xiaoxin05** [comment]
> Seems like u are using old repo.. clone new repo and add ‘ MAX_NUM_INSTANCE’ into the voc_config accordionists to ur dataset
> 
> https://github.com/google/automl/blob/master/efficientdet/hparams_config.py#L197

hi ,thank you , I already solve this problem, I change the parameter :(MAX_NUM_INSTANCE), because I  looked at my data set, this is contain 110 samples in one image.

**Comment by xiaoxin05** [comment]
what do you mean？ I don't know，please tell me detais ,thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Samjith888"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 凌晨4:34
收件人:&nbsp;"google/automl"<automl@noreply.github.com&gt;;
抄送:&nbsp;"张雯欣"<912650845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [google/automl] tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [ERROR: please increase config.max_instances_per_image] [Condition x < y did not hold element-wise:] [x (parser/strided_slice_18:0) = ] [101] [y (parser/assert_less_1/y:0) = ] [100]   [[{{node parser/assert_less_1/Assert/Assert}}]]   [[IteratorGetNext]] (#561)





 
Seems like u are using old repo.. clone new repo and add ‘ MAX_NUM_INSTANCE’ into the voc_config accordionists to ur dataset
 
https://github.com/google/automl/blob/master/efficientdet/hparams_config.py#L197
