### ISSUE TITLE
Get raw output from saved model

### ISSUE THREAD

**Issue by kcrumb** [google/automl#576]
I'm trying to get the raw output from a saved model. I saved the model by using following command:
```
python model_inspect.py ^
--model_name=efficientdet-d1 ^
--runmode=saved_model ^
--ckpt_path=D:\Development\projects-misc\automl-efficientnet\logs\efficientdet-d1.v2 ^
--hparams="num_classes=2,moving_average_decay=0" ^
--batch_size=1 ^
--saved_model_dir=D:\tmp\efficientdet-d1.v2
```

The loading and prediction code looks like this:
```python
import tensorflow as tf
from PIL import Image
import numpy as np

def load_model():
    with tf.compat.v1.Session() as sess:
        with tf.io.gfile.GFile('./efficientdet-d1.v2/efficientdet-d1_frozen.pb', 'rb') as f:
            graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())
        sess.graph.as_default()
        tf.import_graph_def(graph_def, name='')

def predict():
    with tf.compat.v1.Session() as sess:
        imageFile = "D:/Users/kevin/Nextcloud/polyp-datasets/CVC-EndoSceneStill/CVC-300/bbdd/72.bmp"
        image = Image.open(imageFile)
        image = image.resize((640, 640))
        image = np.array(image)

        prediction = sess.run('detections:0', feed_dict={'image_files:0': image})
        print(prediction.shape)
        print(prediction)

if __name__ == '__main__':
    load_model()
    predict()
    print("done...")
```

But I get following error:
```
Traceback (most recent call last):
  File "D:/Development/Projects/efficientdet-predict/predict.py", line 54, in <module>
    predict()
  File "D:/Development/Projects/efficientdet-predict/predict.py", line 37, in predict
    prediction = sess.run(output_layer, feed_dict={input_node: [image]})
  File "D:\Development\anaconda3\envs\automl-efficientnet\lib\site-packages\tensorflow_core\python\client\session.py", line 960, in run
    run_metadata_ptr)
  File "D:\Development\anaconda3\envs\automl-efficientnet\lib\site-packages\tensorflow_core\python\client\session.py", line 1159, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 640, 640, 3) for Tensor 'image_files:0', which has shape '(None,)'
```

What I did wrong? Is is even possible this way?
Thanks in advance!

**Comment by mingxingtan** [comment]
Hi @kcrumb , you need to change `image_files:0 `to `image_arrays:0`

**Comment by kcrumb** [comment]
@mingxingtan Thanks a lot! My bad that I didn't looked close enough. But I have one following question: What could be the reason that all my predictions are empty? I'm just getting `[]` returned, I even tried images that were used for training.

**Comment by mingxingtan** [comment]
Hmm, I am not sure.  You may need to debug it (like decrease score_thred). 
I recently added a TF2 version of inference script [here](https://github.com/google/automl/blob/master/efficientdet/keras/infer.py), which may be helpful during your debug.

**Comment by kcrumb** [comment]
Thanks for your work! Repo update solved the issue.
