### ISSUE TITLE
Exporting model with Tensorflow 1.15 broken

### ISSUE THREAD

**Issue by FamousDirector** [google/automl#586]
Hello,

I just updated the latest code (from yesterday to today) and no longer can run the following command:
`python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir`

I get the following error:
```
Traceback (most recent call last):
  File "model_inspect.py", line 491, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 485, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 438, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 146, in export_saved_model
    driver.build()
  File "/project/inference.py", line 500, in build
    detections = det_post_process(params, class_outputs, box_outputs, scales)
  File "/project/inference.py", line 269, in det_post_process
    img_ids = tf.range(0, batch_size, dtype=nms_scores.dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py", line 1411, in range
    limit = ops.convert_to_tensor(limit, dtype=dtype, name="limit")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/constant_op.py", line 338, in _dimension_tensor_conversion_function
    raise TypeError("Cannot convert a TensorShape to dtype: %s" % dtype)
TypeError: Cannot convert a TensorShape to dtype: <dtype: 'float32'>
```

I run the same command in Tensorflow 2.2 and get no error and a successful export. Please advise.

**Comment by fsx950223** [comment]
tf.enable_v2_behavior
