### ISSUE TITLE
KeyError: 'caption' while creating tfrecord

### ISSUE THREAD

**Issue by Mattis95** [google/automl#600]
I want to train on my own dataset, so I'm trying to create a TFRecord file from my data. I use the code from the example, adjusted on my data.

```
!python /content/automl/efficientdet/dataset/create_coco_tfrecord.py --logtostderr \
  --image_dir='/content/automl/efficientdet/JPEGImages' \
  --caption_annotations_file='/content/automl/efficientdet/lable.json' \
  --output_file_prefix='/content/automl/efficientdet/tfrecord_test/Spaene' \
  --num_shards=32
```

The programm writes empty TFRecord data in the folder and I get this message:
```
2020-07-15 10:36:35.920413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
I0715 10:36:38.313903 140468954613632 create_coco_tfrecord.py:283] writing to output path: /content/automl/efficientdet/tfrecord_test/Spaene
I0715 10:36:38.329210 140468954613632 create_coco_tfrecord.py:236] Building caption index.
I0715 10:36:38.330096 140468954613632 create_coco_tfrecord.py:248] 0 images are missing captions.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/content/automl/efficientdet/dataset/create_coco_tfrecord.py", line 201, in _pool_create_tf_example
    return create_tf_example(*args)
  File "/content/automl/efficientdet/dataset/create_coco_tfrecord.py", line 192, in create_tf_example
    captions.append(caption_annotation['caption'].encode('utf8'))
KeyError: 'caption'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/automl/efficientdet/dataset/create_coco_tfrecord.py", line 361, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/automl/efficientdet/dataset/create_coco_tfrecord.py", line 357, in main
    FLAGS.include_masks)
  File "/content/automl/efficientdet/dataset/create_coco_tfrecord.py", line 319, in _create_tf_record_from_coco_annotations
    for image in images])):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
KeyError: 'caption'
```

What does this error mean? Is there something wrong with my annotation file?

**Comment by mingxingtan** [comment]
You caption annotation file has some issues.
I recommend using create_pascal_tfrecord.py if your custom dataset is simple.

**Comment by HaoDreamlong** [comment]
if you are doing object detection task, you can change the " --caption_annotations_file " option to " --object_annotations_file "

**Comment by Mattis95** [comment]
> @HaoDreamlong that was the problem, thank you!
