### ISSUE TITLE
W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: file is too short to be an sstable

### ISSUE THREAD

**Issue by mhcao916** [google/automl#646]
when i finetune  the d0 model based on my own dataset, i use this command:
CUDA_VISIBLE_DEVICES=0,1 nohup python main_re_fpn_eff.py --mode=train_and_eval --training_file_pattern=tfrecord/six_train*.tfrecord --validation_file_pattern=tfrecord/six_val*.tfrecord --model_name=efficientdet-d0 --model_dir=re_fpn_eff_model --ckpt=re_fpn_model/archive --train_batch_size=8 --eval_batch_size=8 --eval_samples=5000 --num_examples_per_epoch=11000 --num_epochs=16 --hparams=voc_config_re_fpn_eff.yaml &

and in re_fpn_model/archive dir, there is a my pretrained model, it is to say, i use a model in re_fpn_model/archive instead of the model in efficiedtdet-d0,
after training on my own data, then, i get the best model in datadir: re_fpn_eff_model/archive , and then, i use this command to convert my model to savemodel:
python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 --ckpt_path=re_fpn_eff_model/archive --saved_model_dir=re_fpn_eff_model-d0 --hparams=voc_config_re_fpn_eff.yaml,
but i got this error:

2020-08-03 09:54:39.897422: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Data loss: file is too short to be an sstable
Traceback (most recent call last):
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: file is too short to be an sstable
	 [[{{node save/RestoreV2}}]]
  (1) Data loss: file is too short to be an sstable
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_725]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 503, in <module>
    app.run(main)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 496, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 447, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 157, in export_saved_model
    driver.build()
  File "/home/automl-master/efficientdet/inference.py", line 509, in build
    export_ckpt=None)
  File "/home/automl-master/efficientdet/inference.py", line 232, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/envs/efficientdet/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: file is too short to be an sstable
	 [[node save/RestoreV2 (defined at /home/automl-master/efficientdet/inference.py:226) ]]
  (1) Data loss: file is too short to be an sstable

However, when i use --ckpt_path=re_fpn_eff_model instead of --ckpt_path=re_fpn_eff_model/archive, i can get a correct savedmodel, but my best model is not in re_fpn_eff_model, it is in re_fpn_eff_model/archive, how can i get my best model into savedmodel?
anyone can help?

**Comment by mhcao916** [comment]
and my voc_config_re_fpn_eff.yaml is like this :
  num_classes: 3
  moving_average_decay: 0
  var_freeze_expr: '(efficientnet)'
  label_id_mapping: {0:background, 1:dog, 2:cat}
it is because i finetune based on my pretrained model which in re_fpn_model/archive?  but why i can train use it? however cannot convert the model in re_fpn_eff_model/archive?

**Comment by mhcao916** [comment]
oh, i have find the issue, it is because i train the two model in two defferent environment, and the tf version is defferent. i train the first model : re_fpn_model in tf 2.1, and i train the second model in tf1.5
