### ISSUE TITLE
How to convert custom dataset into TFRecord

### ISSUE THREAD

**Issue by JSGrondin** [google/automl#698]
I have a custom dataset in a Pascal VOC format, with a fixed train-val split, as such: 
I would like to know how to convert from this format to TFRecord?

**Comment by mingxingtan** [comment]
Hi @JSGrondin Please see this section on how to create TFRecord: https://github.com/google/automl/tree/master/efficientdet#8-finetune-on-pascal-voc-2012-with-detector-coco-ckpt

**Comment by Cocoalate** [comment]
> 
HI，could you tell me how to use custom TFRecord when finetuning efficientnet v2?
I have TFRecord data but I don't know how to put dataset in the model , I change the data_dir parameter but it throw out this error:
`Load TF1 graph based checkpoint from /data_x/keke/workspace/efficientnetv2-s/model.
I0424 17:23:20.725506 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_0/conv2d/kernel:0 from efficientnetv2-s/blocks_0/conv2d/kernel (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.726175 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_0/tpu_batch_normalization/gamma:0 from efficientnetv2-s/blocks_0/tpu_batch_normalization/gamma (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.726604 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_0/tpu_batch_normalization/beta:0 from efficientnetv2-s/blocks_0/tpu_batch_normalization/beta (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.727011 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_1/conv2d/kernel:0 from efficientnetv2-s/blocks_1/conv2d/kernel (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.727399 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_1/tpu_batch_normalization/gamma:0 from efficientnetv2-s/blocks_1/tpu_batch_normalization/gamma (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.727778 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_1/tpu_batch_normalization/beta:0 from efficientnetv2-s/blocks_1/tpu_batch_normalization/beta (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.758221 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_2/conv2d/kernel:0 from efficientnetv2-s/blocks_2/conv2d/kernel (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.758875 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_2/tpu_batch_normalization/gamma:0 from efficientnetv2-s/blocks_2/tpu_batch_normalization/gamma (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.759287 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_2/tpu_batch_normalization/beta:0 from efficientnetv2-s/blocks_2/tpu_batch_normalization/beta (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:20.759712 139731377256256 utils.py:578] Init efficientnetv2-s/blocks_2/conv2d_1/kernel:0 from efficientnetv2-s/blocks_2/conv2d_1/kernel (/data_x/keke/workspace/efficientnetv2-s/model)
I0424 17:23:22.062904 139731377256256 main_tf2.py:50] Using RMSProp optimizer
2022-04-24 17:23:22.131624: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2022-04-24 17:23:22.131671: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2022-04-24 17:23:22.131702: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1365] Profiler found 1 GPUs
2022-04-24 17:23:22.131899: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcupti.so.11.0'; dlerror: libcupti.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/wangym/lightlda/multiverso/third_party/bin
2022-04-24 17:23:22.139284: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcupti.so
2022-04-24 17:23:22.139960: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2022-04-24 17:23:22.140060: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1487] CUPTI activity buffer flushed
Traceback (most recent call last):
  File "main_tf2.py", line 312, in <module>
    app.run(main)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main_tf2.py", line 237, in main
    get_dataset(training=True, image_size=train_size, config=config),
  File "main_tf2.py", line 228, in get_dataset
    config.data).distribute_dataset_fn(config.train.batch_size))
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1135, in distribute_datasets_from_function
    dataset_fn, options)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 547, in _distribute_datasets_from_function
    options)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 162, in get_distributed_datasets_from_function
    input_contexts, strategy, options)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1273, in __init__
    self._input_contexts, self._input_workers, dataset_fn))
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/distribute/input_lib.py", line 1936, in _create_datasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
  File "/data_x/keke/workspace/Cover_Effnetv2/efficientnetv2/datasets.py", line 451, in dataset_fn
    input_context.input_pipeline_id, input_context.num_input_pipelines)
  File "/data_x/keke/workspace/Cover_Effnetv2/efficientnetv2/datasets.py", line 403, in _input_fn
    dataset = self.make_source_dataset(current_host, num_hosts)
  File "/data_x/keke/workspace/Cover_Effnetv2/efficientnetv2/datasets.py", line 357, in make_source_dataset
    dataset = dataset.shuffle(num_files_per_shard, seed=self.shuffle_seed)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2593, in shuffle
    buffer_size, seed, reshuffle_each_iteration))
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1350, in shuffle
    return ShuffleDataset(self, buffer_size, seed, reshuffle_each_iteration)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3836, in __init__
    **self._flat_structure)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 6294, in shuffle_dataset_v3
    _ops.raise_from_not_ok_status(e, name)
  File "/root/anaconda3/envs/keke/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero. [Op:ShuffleDatasetV3]`

**Comment by darouwan** [comment]
> 

Same error when use main_tf2. Did you fix it?
