### ISSUE TITLE
Saving keras model returns InaccessibleTensorError

### ISSUE THREAD

**Issue by robert-hardwick** [google/automl#705]
I have added

model.save('/path/to/saved_model') 

to keras/infer.py 

I am able to load weights into model and perform predictions, but i cannot save the model as per the following error.

tensorflow.python.framework.errors_impl.InaccessibleTensorError: The tensor 'Tensor("blocks_15/Identity_2:0", shape=(None, 16, 16, 320), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=efficientnet-b0_layer_call_and_return_conditional_losses, id=139902875332736); accessed from: FuncGraph(name=_layer_call_and_return_conditional_losses, id=139902877748360).

Anyone have any tips / suggestions to debug?

**Comment by robert-hardwick** [comment]
Looks like the issue is related to https://github.com/tensorflow/tensorflow/issues/37444

and the problem code is here

https://github.com/google/automl/blob/master/efficientdet/keras/efficientdet_keras.py#L820

**Comment by kartik4949** [comment]
@fsx950223

**Comment by robert-hardwick** [comment]
Just trying to export a model that I have trained for segmentation and object detection to a saved_model format, but i have this error if i use keras scripts directly. 

If i used model_main.py --run_mode saved_model i receive other errors:

```
2020-08-26 16:10:25.126783: W tensorflow/core/framework/op_kernel.cc:1774] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Not found: Key box_net/box-0-bn-3/beta not found in checkpoint
WARNING:tensorflow:Restoring an object-based checkpoint using a name-based saver. This may be somewhat fragile, and will re-build the Saver. Instead, consider loading object-based checkpoints using tf.train.Checkpoint().
W0826 16:10:25.142078 139644081489728 saver.py:1320] Restoring an object-based checkpoint using a name-based saver. This may be somewhat fragile, and will re-build the Saver. Instead, consider loading object-based checkpoints using tf.train.Checkpoint().
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key box_net/box-0-bn-3/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1299, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /storage1/automl_fresh/efficientdet/inference.py:215) ]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key box_net/box-0-bn-3/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at /storage1/automl_fresh/efficientdet/inference.py:215) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 150, in export_saved_model
    driver.build()
  File "/storage1/automl_fresh/efficientdet/inference.py", line 467, in build
    export_ckpt=None)
  File "/storage1/automl_fresh/efficientdet/inference.py", line 215, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 836, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 886, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 336, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1525, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 777, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3520, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1978, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 150, in export_saved_model
    driver.build()
  File "/storage1/automl_fresh/efficientdet/inference.py", line 467, in build
    export_ckpt=None)
  File "/storage1/automl_fresh/efficientdet/inference.py", line 224, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1329, in restore
    cached_saver=self._object_restore_saver)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1722, in saver_from_object_based_checkpoint
    sorted(extra_names)), len(intersecting_names)))
tensorflow.python.framework.errors_impl.NotFoundError: 

Existing variables not in the checkpoint: segmentation_head/bn_1/beta, segmentation_head/bn_1/gamma, segmentation_head/bn_1/moving_mean, segmentation_head/bn_1/moving_variance, segmentation_head/bn_2/beta, segmentation_head/bn_2/gamma, segmentation_head/bn_2/moving_mean, segmentation_head/bn_2/moving_variance, segmentation_head/bn_3/beta, segmentation_head/bn_3/gamma, segmentation_head/bn_3/moving_mean, segmentation_head/bn_3/moving_variance
```

which is the way to export saved_model with segmentation head?
