### ISSUE TITLE
 "list assignment index out of range" when eval trained model

### ISSUE THREAD

**Issue by williamhyin** [google/automl#718]
Hi all

I have a problem when i  eval the trained model.  "list assignment index out of range"
I have modified config.yaml.
![image](https://user-images.githubusercontent.com/51480545/91801091-d309c280-ec5c-11ea-8808-b600cfef5c20.png)

**Hope someone can help me.**

This is my eval code:

```
d="d4"
times="dfg_1"

!python main.py --mode=eval  \
--model_name=efficientdet-{d}  --model_dir=/home/code/sb/automl/efficientdet/tmp/finetune{d}_{times}  \
--validation_file_pattern=/home/code/sb/automl/efficientdet/dfg/tfrecord/dfg_val*  \
--val_json_file=/home/code/sb/automl/efficientdet/dfg/instances_modval.json \
--hparams=/home/code/sb/automl/efficientdet/dfg/dfg.yaml --eval_batch_size=1 --eval_samples=1703 \
```

This is my config.yaml.

```
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
num_classes: 201
label_map: {0: background, 1: I-1.1, .......}
moving_average_decay: 0
use_keras_model: False
image_size: 640
```

Debug log:

```
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=25.18s).
Accumulating evaluation results...
DONE (t=6.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.255
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.299
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.288
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.008
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.111
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.366
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.594
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.633
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.633
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.029
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.404
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.832
2020-09-01 14:00:47.296148: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: IndexError: list assignment index out of range
Traceback (most recent call last):

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 132, in result
    self.metric_values = self.evaluate()

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 125, in evaluate
    ap_perclass[c] = ap_c

IndexError: list assignment index out of range


INFO:tensorflow:evaluation_loop marked as finished
I0901 14:00:47.508140 139931821594432 error_handling.py:115] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0901 14:00:47.508323 139931821594432 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: IndexError: list assignment index out of range
Traceback (most recent call last):

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 132, in result
    self.metric_values = self.evaluate()

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 125, in evaluate
    ap_perclass[c] = ap_c

IndexError: list assignment index out of range


	 [[{{node coco_metric/PyFunc_1}}]]
	 [[coco_metric/PyFunc_1/_8219]]
  (1) Unknown: IndexError: list assignment index out of range
Traceback (most recent call last):

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 132, in result
    self.metric_values = self.evaluate()

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 125, in evaluate
    ap_perclass[c] = ap_c

IndexError: list assignment index out of range


	 [[{{node coco_metric/PyFunc_1}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 384, in <module>
    app.run(main)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 323, in main
    eval_results = _eval(eval_steps)
  File "main.py", line 303, in _eval
    name=FLAGS.eval_name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3110, in evaluate
    rendezvous.raise_errors()
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3105, in evaluate
    name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 467, in evaluate
    name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 499, in _evaluate
    output_dir=self.eval_dir(name))
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1644, in _evaluate_run
    config=self._session_config)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 885, in __exit__
    self._close_internal(exception_type)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 918, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 961, in end
    self._final_ops, feed_dict=self._final_ops_feed_dict)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: IndexError: list assignment index out of range
Traceback (most recent call last):

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 132, in result
    self.metric_values = self.evaluate()

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 125, in evaluate
    ap_perclass[c] = ap_c

IndexError: list assignment index out of range


	 [[node coco_metric/PyFunc_1 (defined at /home/iav/code/sb/automl/efficientdet/coco_metric.py:226) ]]
	 [[coco_metric/PyFunc_1/_8219]]
  (1) Unknown: IndexError: list assignment index out of range
Traceback (most recent call last):

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 132, in result
    self.metric_values = self.evaluate()

  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 125, in evaluate
    ap_perclass[c] = ap_c

IndexError: list assignment index out of range


	 [[node coco_metric/PyFunc_1 (defined at /home/iav/code/sb/automl/efficientdet/coco_metric.py:226) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'coco_metric/PyFunc_1':
  File "main.py", line 384, in <module>
    app.run(main)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 323, in main
    eval_results = _eval(eval_steps)
  File "main.py", line 303, in _eval
    name=FLAGS.eval_name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3105, in evaluate
    name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 467, in evaluate
    name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 492, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1528, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1564, in _call_model_fn_eval
    config)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn
    config)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2043, in _call_model_fn
    return estimator_spec.as_estimator_spec()
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 379, in as_estimator_spec
    host_call_ret = _OutfeedHostCall.create_cpu_hostcall(self._host_calls)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2119, in create_cpu_hostcall
    ret[name] = host_fn(**tensors)
  File "/home/iav/code/sb/automl/efficientdet/det_model_fn.py", line 493, in metric_fn
    detections_bs, kwargs['groundtruth_data'], params['label_map'])
  File "/home/iav/code/sb/automl/efficientdet/coco_metric.py", line 226, in estimator_metric_fn
    metrics = tf.numpy_function(self.result, [], tf.float32)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 632, in numpy_function
    return py_func_common(func, inp, Tout, stateful=True, name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 539, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 346, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 151, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/home/iav/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by mingxingtan** [comment]
The problem is from per-class AP, which assume at most 100 classes, but you have 201 classes, causing this error.
I find this per-class logging is not very useful, so I disabled that in #e03aaee   Your problem should be gone if you sync to the head.

**Comment by williamhyin** [comment]
> The problem is from per-class AP, which assume at most 100 classes, but you have 201 classes, causing this error.
> I find this per-class logging is not very useful, so I disabled that in #e03aaee Your problem should be gone if you sync to the head.

Hi,

Thank you for your reply. But actually it did not work. 
I synced to the new head, and run "eval" again. The problem is same as before.
I found this problem happend in 

```
File "/home/automl/efficientdet/coco_metric.py", line 132, in result
    self.metric_values = self.evaluate()

  File "/home/automl/efficientdet/coco_metric.py", line 125, in evaluate
    ap_perclass[c] = ap_c
```

So I changed Initialization of ap_perclasses:
from
 ap_perclass = [0] * 100  # assumeing at most 100 classes.
to 
 ap_perclass = [0] * 201  # assumeing at most 201 classes for dfg.

It seems work.
Maybe we need initialize "ap_perclass" wirh more class number ?
@mingxingtan
