### ISSUE TITLE
How to train EfficientDet for instance Segmentation?

### ISSUE THREAD

**Issue by swapnil3597** [google/automl#723]
First I created tfrecords from coco json using following command:
```bash
python -m dataset.create_coco_tfrecord \
    --image_dir=gs://path/to/img_dir/ \
    --object_annotations_file=gs://path/to/train_coco.json \
    --output_file_prefix=gs://path/to/output_dir/train \
    --num_shards=20 \
    --include_masks=True # <-- Mask included
```
After creating tfrecords I did following changes in `hparams_config.py`:
```python3
 # TODO(tanmingxing): update this to be 91 for COCO, and 21 for pascal.
  h.num_classes = 4  # 1+ actual classes, 0 is reserved for background.
  h.seg_num_classes = 3  # segmentation classes
  h.heads = ['object_detection',  'segmentation']  # 'object_detection', 'segmentation'

  h.skip_crowd_during_training = True
  h.label_map = {1: 'label1', 2: 'label2', 3: 'label3'}  # a dict or a string of 'coco'/'voc'.
```
Then after running the command for training the code I'm facing the following issue. I'm doing something wrong?
```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/automl/efficientdet/main.py", line 386, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/jupyter/automl/efficientdet/main.py", line 312, in main
    _train(total_examples // FLAGS.train_batch_size)
  File "/home/jupyter/automl/efficientdet/main.py", line 282, in _train
    max_steps=steps)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1182, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1211, in _train_model_default
    self.config)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2915, in _call_model_fn
    config)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1170, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3173, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/home/jupyter/automl/efficientdet/det_model_fn.py", line 621, in efficientdet_model_fn
    variable_filter_fn=variable_filter_fn)
  File "/home/jupyter/automl/efficientdet/det_model_fn.py", line 346, in _model_fn
    precision, model_fn, features, params['is_training_bn'])
  File "/home/jupyter/automl/efficientdet/utils.py", line 674, in build_model_with_precision
    outputs = mm(ii, *args, **kwargs)
  File "/home/jupyter/automl/efficientdet/det_model_fn.py", line 335, in model_fn
    cls_out_list, box_out_list = model(inputs, params['is_training_bn'])
ValueError: not enough values to unpack (expected 2, got 1)
```

Also in `hparams_config.py` when I only used, ` h.heads = ['object_detection']` the model is training.

This is the command which I used for training:
```bash
python3 main.py --mode=train \
    --training_file_pattern=gs://path/to/output_dir/train*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=gs://path/to/model_dir/  \
    --ckpt=gs://path/to/efficientdet_ckpt/  \
    --train_batch_size=8 \
    --num_epochs=10 \
    --num_examples_per_epoch=7985 \
```

**Comment by mingxingtan** [comment]
I think for instance segmentation, you should use the TF2 script: https://github.com/google/automl/blob/master/efficientdet/keras/train.py

**Comment by mingxingtan** [comment]
Could you give it a try and let use know whether it works well for your case?

**Comment by fsx950223** [comment]
```python keras/segmentation.py```

**Comment by Ubbi007** [comment]
@swapnil3597 i got the same issue .could you please share your code??
