### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'    

### ISSUE THREAD

**Issue by xzswater** [google/automl#726]
horovodrun -np 1 -H localhost:1 ../../pyenv/bin/python3 main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/demo_train2/*.tfrecord \
    --validation_file_pattern=tfrecord/demo_test2/*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=efficientdet-d0-finetune \
    --ckpt=efficientdet-d0 \
    --train_batch_size=2 \
    --eval_batch_size=2 --eval_samples=500 \
    --num_examples_per_epoch=5000 --num_epochs=20 \
    --hparams=aicv_config.yaml \
    --strategy=horovod

![image](https://user-images.githubusercontent.com/52267702/91982149-68d84700-ed5c-11ea-9471-0b66e5db14dd.png)

[1,0]<stderr>:Traceback (most recent call last):                                                                                                                                                                          
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                             
[1,0]<stderr>:    self.run()                                                                                                                                                                                              
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 93, in run                                                                                     
[1,0]<stderr>:    self._target(*self._args, **self._kwargs)                                                                                                                                                               
[1,0]<stderr>:  File "main.py", line 361, in run_train_and_eval                                                                                                                                                           
[1,0]<stderr>:    _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)                                                                                                                                      
[1,0]<stderr>:  File "main.py", line 277, in _train                                                                                                                                                                       
[1,0]<stderr>:    max_steps=steps)                                                                                                                                                                                        
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train                                   
[1,0]<stderr>:    rendezvous.raise_errors()                                                                                                                                                                               
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors                            
[1,0]<stderr>:    six.reraise(typ, value, traceback)                                                                                                                                                                      
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/six.py", line 703, in reraise                                                                                      
[1,0]<stderr>:    raise value                                                                                                                                                                                             
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train                                   
[1,0]<stderr>:    saving_listeners=saving_listeners)                                                                                                                                                                      
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train                                            
[1,0]<stderr>:    loss = self._train_model(input_fn, hooks, saving_listeners)                                                                                                                                             
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model                                    
[1,0]<stderr>:    return self._train_model_default(input_fn, hooks, saving_listeners)                                                                                                                                     
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default                            
[1,0]<stderr>:    self.config)                                                                                                                                                                                            
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn                          
[1,0]<stderr>:    config)                                                                                                                                                                                                 
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn                                  
[1,0]<stderr>:    model_fn_results = self._model_fn(features=features, **kwargs)                                                                                                                                          
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn                               
[1,0]<stderr>:    features, labels, is_export_mode=is_export_mode)                                                                                                                                                        
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu                        
[1,0]<stderr>:    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)                                                                                                                             
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn                          
[1,0]<stderr>:    estimator_spec = self._model_fn(features=features, **kwargs)                                                                                                                                            
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 638, in efficientdet_model_fn                                                                             
[1,0]<stderr>:    variable_filter_fn=variable_filter_fn)                                                                                                                                                                  
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 385, in _model_fn                                                                                         
[1,0]<stderr>:    cls_outputs, box_outputs, labels, params)                                                                                                                                                               
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 216, in detection_loss                                                                                    
[1,0]<stderr>:    if params.get('positives_momentum', 0) > 0:                                                                                                                                                             
[1,0]<stderr>:**TypeError: '>' not supported between instances of 'NoneType' and 'int'**

**Comment by kartik4949** [comment]
@xzswater share your config.yaml seems like positives_momentum is not found

**Comment by kartik4949** [comment]
@mingxingtan in hparams.py , positives_momentum is None

**Comment by xzswater** [comment]
> @xzswater Seems like it is a bug , None is assigned as default for positives_momentum.
> try a fix
> In hparams.py ,change positives_momentum =None to = -1

I changed to 0.9, is it ok ?

**Comment by xzswater** [comment]
@kartik4949  @mingxingtan 

I change positives_momentum to -1, but still have error.

[1,0]<stderr>:Traceback (most recent call last):                                                                                                                                                                          
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                             
[1,0]<stderr>:    self.run()                                                                                                                                                                                              
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 93, in run                                                                                     
[1,0]<stderr>:    self._target(*self._args, **self._kwargs)                                                                                                                                                               
[1,0]<stderr>:  File "main.py", line 361, in run_train_and_eval                                                                                                                                                           
[1,0]<stderr>:    _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)                                                                                                                                      
[1,0]<stderr>:  File "main.py", line 277, in _train                                                                                                                                                                       
[1,0]<stderr>:    max_steps=steps)    
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train                                   
[1,0]<stderr>:    rendezvous.raise_errors()                                                                                                                                                                               
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors                            
[1,0]<stderr>:    six.reraise(typ, value, traceback)                                                                                                                                                                      
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/six.py", line 703, in reraise                                                                                      
[1,0]<stderr>:    raise value                                                                                                                                                                                             
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train                                   
[1,0]<stderr>:    saving_listeners=saving_listeners)                                                                                                                                                                      
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train                                            
[1,0]<stderr>:    loss = self._train_model(input_fn, hooks, saving_listeners)                                                                                                                                             
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model                                    
[1,0]<stderr>:    return self._train_model_default(input_fn, hooks, saving_listeners)                                                                                                                                     
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default                            
[1,0]<stderr>:    self.config)                                                                                                                                                                                            
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn                          
[1,0]<stderr>:    config)                                                                                                                                                                                                 
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn                                  
[1,0]<stderr>:    model_fn_results = self._model_fn(features=features, **kwargs)                                                                                                                                          
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn                               
[1,0]<stderr>:    features, labels, is_export_mode=is_export_mode)                                                                                                                                                        
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu                        
[1,0]<stderr>:    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)                                                                                                                             
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn                          
[1,0]<stderr>:    estimator_spec = self._model_fn(features=features, **kwargs)                                                                                                                                            
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 638, in efficientdet_model_fn                                                                             
[1,0]<stderr>:    variable_filter_fn=variable_filter_fn)                                                                                                                                                                  
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 385, in _model_fn                                                                                         
[1,0]<stderr>:    cls_outputs, box_outputs, labels, params)                                                                                                                                                               
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 230, in detection_loss                                                                                    
[1,0]<stderr>:    num_positives_sum = utils.cross_replica_mean(num_positives_sum)                                                                                                                                         
[1,0]<stderr>:  File "/root/efficientdet/automl/efficientdet/utils.py", line 62, in cross_replica_mean                                                                                        
[1,0]<stderr>:    return tf.tpu.cross_replica_sum(t) / tf.cast(num_shards, t.dtype)                                                                                                                                       
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper                                                          
[1,0]<stderr>:    return target(*args, **kwargs)                                                                                                                                                                          
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-[1,0]<stderr>:packages/tensorflow/python/ops/math_ops.py", line 921, in cast                                                
[1,0]<stderr>:    x = ops.convert_to_tensor(x, name="x")                                                                                                                                                                  
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor                                               
[1,0]<stderr>:    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)                                                                                                                                     
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function                     
[1,0]<stderr>:    return constant(v, dtype=dtype, name=name)                                                                                                                                                              
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant                                                 
[1,0]<stderr>:    allow_broadcast=True)                                                                                                                                                                                   
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 282, in _constant_impl                                           
[1,0]<stderr>:    allow_broadcast=allow_broadcast))                                                                                                                                                                       
[1,0]<stderr>:  File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 444, in make_tensor_proto                                        
[1,0]<stderr>:    raise ValueError("None values not supported.")                                                                                                                                                          
[1,0]<stderr>:**ValueError: None values not supported.**

**Comment by kartik4949** [comment]
> @kartik4949 @mingxingtan
> 
> I change positives_momentum to -1, but still have error.
> 
> [1,0]:Traceback (most recent call last):
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> [1,0]: self.run()
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 93, in run
> [1,0]: self._target(*self._args, **self._kwargs)
> [1,0]: File "main.py", line 361, in run_train_and_eval
> [1,0]: _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
> [1,0]: File "main.py", line 277, in _train
> [1,0]: max_steps=steps)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
> [1,0]: rendezvous.raise_errors()
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
> [1,0]: six.reraise(typ, value, traceback)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/six.py", line 703, in reraise
> [1,0]: raise value
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
> [1,0]: saving_listeners=saving_listeners)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
> [1,0]: loss = self._train_model(input_fn, hooks, saving_listeners)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
> [1,0]: return self._train_model_default(input_fn, hooks, saving_listeners)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
> [1,0]: self.config)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn
> [1,0]: config)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
> [1,0]: model_fn_results = self._model_fn(features=features, **kwargs)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn
> [1,0]: features, labels, is_export_mode=is_export_mode)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
> [1,0]: return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
> [1,0]: estimator_spec = self._model_fn(features=features, **kwargs)
> [1,0]: File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 638, in efficientdet_model_fn
> [1,0]: variable_filter_fn=variable_filter_fn)
> [1,0]: File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 385, in _model_fn
> [1,0]: cls_outputs, box_outputs, labels, params)
> [1,0]: File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 230, in detection_loss
> [1,0]: num_positives_sum = utils.cross_replica_mean(num_positives_sum)
> [1,0]: File "/root/efficientdet/automl/efficientdet/utils.py", line 62, in cross_replica_mean
> [1,0]: return tf.tpu.cross_replica_sum(t) / tf.cast(num_shards, t.dtype)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
> [1,0]: return target(*args, **kwargs)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-[1,0]:packages/tensorflow/python/ops/math_ops.py", line 921, in cast
> [1,0]: x = ops.convert_to_tensor(x, name="x")
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
> [1,0]: ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
> [1,0]: return constant(v, dtype=dtype, name=name)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
> [1,0]: allow_broadcast=True)
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 282, in _constant_impl
> [1,0]: allow_broadcast=allow_broadcast))
> [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 444, in make_tensor_proto
> [1,0]: raise ValueError("None values not supported.")
> [1,0]:**ValueError: None values not supported.**

positives_momentum=0?

**Comment by xzswater** [comment]
@kartik4949    no   == 0
![image](https://user-images.githubusercontent.com/52267702/91987711-fc137b80-ed60-11ea-99fc-99f723c5f4e4.png)

**Comment by xzswater** [comment]
if set to 0.9, it will hang there.

**Comment by kartik4949** [comment]
> @kartik4949 no == 0
> ![image](https://user-images.githubusercontent.com/52267702/91987711-fc137b80-ed60-11ea-99fc-99f723c5f4e4.png)

setting it 0 will bypass two two statements

**Comment by kartik4949** [comment]
@xzswater im asking to set it as 0 because earlier there was no num_positives normalization i.e before #722

**Comment by xzswater** [comment]
> @xzswater im asking to set it as 0 because earlier there was no num_positives normalization i.e before #722

@kartik4949  set to 0, also hang there as 0.9.

**Comment by kartik4949** [comment]
@mingxingtan

**Comment by Vinodvs34** [comment]
> horovodrun -np 1 -H localhost:1 ../../pyenv/bin/python3 main.py --mode=train_and_eval --training_file_pattern=tfrecord/demo_train2/_.tfrecord --validation_file_pattern=tfrecord/demo_test2/_.tfrecord --model_name=efficientdet-d0 --model_dir=efficientdet-d0-finetune --ckpt=efficientdet-d0 --train_batch_size=2 --eval_batch_size=2 --eval_samples=500 --num_examples_per_epoch=5000 --num_epochs=20 --hparams=aicv_config.yaml --strategy=horovod
> 
> ![image](https://user-images.githubusercontent.com/52267702/91982149-68d84700-ed5c-11ea-9471-0b66e5db14dd.png)
> 
> [1,0]:Traceback (most recent call last): [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap [1,0]: self.run() [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/multiprocessing/process.py", line 93, in run [1,0]: self._target(*self._args, **self._kwargs) [1,0]: File "main.py", line 361, in run_train_and_eval [1,0]: _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size) [1,0]: File "main.py", line 277, in _train [1,0]: max_steps=steps) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train [1,0]: rendezvous.raise_errors() [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors [1,0]: six.reraise(typ, value, traceback) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/six.py", line 703, in reraise [1,0]: raise value [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train [1,0]: saving_listeners=saving_listeners) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train [1,0]: loss = self._train_model(input_fn, hooks, saving_listeners) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model [1,0]: return self._train_model_default(input_fn, hooks, saving_listeners) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default [1,0]: self.config) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn [1,0]: config) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn [1,0]: model_fn_results = self._model_fn(features=features, **kwargs) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn [1,0]: features, labels, is_export_mode=is_export_mode) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu [1,0]: return self._call_model_fn(features, labels, is_export_mode=is_export_mode) [1,0]: File "/root/efficientdet/pyenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn [1,0]: estimator_spec = self._model_fn(features=features, **kwargs) [1,0]: File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 638, in efficientdet_model_fn [1,0]: variable_filter_fn=variable_filter_fn) [1,0]: File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 385, in _model_fn [1,0]: cls_outputs, box_outputs, labels, params) [1,0]: File "/root/efficientdet/automl/efficientdet/det_model_fn.py", line 216, in detection_loss [1,0]: if params.get('positives_momentum', 0) > 0: [1,0]:**TypeError: '>' not supported between instances of 'NoneType' and 'int'**
