### ISSUE TITLE
always out of memory with telsa v 100 and d7x even with batch size=4

### ISSUE THREAD

**Issue by vxgu86** [google/automl#737]
I am training a dataset with 6000 images, each of 3000*2000 pixel
I am so exhausted.
I have tried with train_batch_size from 64 to 4, all with out of memory error 
the script is as follows:
!mkdir /tmp/d7x/
!python3 main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/pascal*.tfrecord \
    --validation_file_pattern=tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d7x \
    --model_dir=/tmp/d7x/efficientdet-d7x-finetune \
    --ckpt=efficientdet-d7x  \
    --train_batch_size=4 \
    --eval_batch_size=1 --eval_samples=100 \
    --num_examples_per_epoch=6575 --num_epochs=50  \
    --hparams=voc_config.yaml

voc_config.yaml is as follows:
num_classes: 5
label_map: {1: aaa, 2: bbb, 3: ccc, 4: ddd}.

..........
2020-09-05 00:43:11.228791: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 171954176 totalling 163.99MiB
2020-09-05 00:43:11.228798: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 215700480 totalling 205.71MiB
2020-09-05 00:43:11.228806: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 15 Chunks of size 301989888 totalling 4.22GiB
2020-09-05 00:43:11.228814: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 369098752 totalling 352.00MiB
2020-09-05 00:43:11.228822: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 3 Chunks of size 452984832 totalling 1.27GiB
2020-09-05 00:43:11.228829: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 7 Chunks of size 603979776 totalling 3.94GiB
2020-09-05 00:43:11.228837: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 18 Chunks of size 679477248 totalling 11.39GiB
2020-09-05 00:43:11.228844: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 3 Chunks of size 1811939328 totalling 5.06GiB
2020-09-05 00:43:11.228852: I tensorflow/core/common_runtime/bfc_allocator.cc:1002] Sum Total of in-use chunks: 28.80GiB
2020-09-05 00:43:11.228859: I tensorflow/core/common_runtime/bfc_allocator.cc:1004] total_region_allocated_bytes_: 31428246272 memory_limit_: 31428246272 available bytes: 0 curr_region_allocation_bytes_: 34359738368
2020-09-05 00:43:11.228873: I tensorflow/core/common_runtime/bfc_allocator.cc:1010] Stats: 
Limit:                 31428246272
InUse:                 30919377152
MaxInUse:              30919377152
NumAllocs:                    7047
MaxAllocSize:           1828716544

2020-09-05 00:43:11.229148: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ****************************************************************************************************
2020-09-05 00:43:11.229206: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at cwise_ops_common.h:312 : **Resource exhausted: OOM when allocating tensor with shape[4,288,384,384] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc**

INFO:tensorflow:training_loop marked as finished
I0905 00:43:13.519988 140156936759040 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0905 00:43:13.521363 140156936759040 error_handling.py:149] Reraising captured error
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[4,288,384,384] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node efficientnet-b7/blocks_7/Sigmoid_1}}]]

Current usage from device: /job:localhost/replica:0/task:0/device:GPU:0, allocator: GPU_0_bfc
  1.69GiB from efficientnet-b7/blocks_4/tpu_batch_normalization/FusedBatchNormV3
  1.69GiB from efficientnet-b7/blocks_4/conv2d/Conv2D
  1.69GiB from efficientnet-b7/blocks_4/Sigmoid

**Comment by kartik4949** [comment]
refer #711
