### ISSUE TITLE
Unable to train without specifying the exact num_examples_per_epoch

### ISSUE THREAD

**Issue by aocz1** [google/automl#741]
In past version while training, I was able to train using a 320 example tfrecord using the default num_examples_per_epoch (120,000). But now I need to specify the exact number with num_examples_per_epoch (in my case 320), or there is an error like below. Is there a way to avoid this error? Training with num_examples_per_epoch with 120,000 yielded more accurate models than what I can currently produce with it set at 320.

```
Error Log:
[1,0]<stderr>:I0906 16:37:19.245370 139929586890560 basic_session_run_hooks.py:260] box_loss = 0.00028466695, cls_loss = 0.30340308, det_loss = 0.31763643, step = 100 (249.467 sec)
[1,0]<stderr>:INFO:tensorflow:global_step/sec: 0.400855
[1,0]<stderr>:I0906 16:37:19.246067 139929586890560 tpu_estimator.py:2350] global_step/sec: 0.400855
[1,0]<stderr>:INFO:tensorflow:examples/sec: 1.60342
[1,0]<stderr>:I0906 16:37:19.246748 139929586890560 tpu_estimator.py:2351] examples/sec: 1.60342
[1,0]<stderr>:2020-09-06 16:38:27.846202: W tensorflow/core/framework/op_kernel.cc:1760] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,0]<stderr>:2020-09-06 16:38:27.846210: W tensorflow/core/framework/op_kernel.cc:1760] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
[1,1]<stderr>:2020-09-06 16:38:33.370220: W tensorflow/core/framework/op_kernel.cc:1760] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
[1,1]<stderr>:2020-09-06 16:38:33.371219: W tensorflow/core/framework/op_kernel.cc:1760] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,1]<stderr>:2020-09-06 16:38:40.712160: W tensorflow/core/framework/op_kernel.cc:1760] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,1]
[1,1]<stderr>:2020-09-06 16:38:40.712160: W tensorflow/core/framework/op_kernel.cc:1760] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,0]<stderr>:INFO:tensorflow:training_loop marked as finished
[1,0]<stderr>:I0906 16:38:43.647286 139929586890560 error_handling.py:115] training_loop marked as finished
[1,0]<stderr>:WARNING:tensorflow:Reraising captured error
[1,0]<stderr>:W0906 16:38:43.647466 139929586890560 error_handling.py:149] Reraising captured error
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
[1,0]<stderr>:    return fn(*args)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
[1,0]<stderr>:    target_list, run_metadata)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
[1,0]<stderr>:    run_metadata)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
[1,0]<stderr>:  (0) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,0]<stderr>:	 [[{{node parser/GatherNd_1}}]]
[1,0]<stderr>:	 [[IteratorGetNext]]
[1,0]<stderr>:  (1) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,0]<stderr>:	 [[{{node parser/GatherNd_1}}]]
[1,0]<stderr>:	 [[IteratorGetNext]]
[1,0]<stderr>:	 [[DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_efficientnet_b7_blocks_19_se_conv2d_BiasAdd_grad_tuple_control_dependency_1_0/_67987]]
[1,0]<stderr>:0 successful operations.
[1,0]<stderr>:0 derived errors ignored.
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "main.py", line 381, in <module>
[1,0]<stderr>:    app.run(main)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
[1,0]<stderr>:    _run_main(main, args)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
[1,0]<stderr>:    sys.exit(main(argv))
[1,0]<stderr>:  File "main.py", line 374, in main
[1,0]<stderr>:    run_train_and_eval(e)
[1,0]<stderr>:  File "main.py", line 361, in run_train_and_eval
[1,0]<stderr>:    _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
[1,0]<stderr>:  File "main.py", line 277, in _train
[1,0]<stderr>:    max_steps=steps)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
[1,0]<stderr>:    rendezvous.raise_errors()
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
[1,0]<stderr>:    six.reraise(typ, value, traceback)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
[1,0]<stderr>:    raise value
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
[1,0]<stderr>:    saving_listeners=saving_listeners)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
[1,0]<stderr>:    loss = self._train_model(input_fn, hooks, saving_listeners)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
[1,0]<stderr>:    return self._train_model_default(input_fn, hooks, saving_listeners)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
[1,0]<stderr>:    saving_listeners)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1511, in _train_with_estimator_spec
[1,0]<stderr>:    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 778, in run
[1,0]<stderr>:    run_metadata=run_metadata)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
[1,0]<stderr>:    run_metadata=run_metadata)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
[1,0]<stderr>:    raise six.reraise(*original_exc_info)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
[1,0]<stderr>:    raise value
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
[1,0]<stderr>:    return self._sess.run(*args, **kwargs)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
[1,0]<stderr>:    run_metadata=run_metadata)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
[1,0]<stderr>:    return self._sess.run(*args, **kwargs)
[1,0]<stderr>: [1,0]<stderr>: File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 958, in run
[1,0]<stderr>:    run_metadata_ptr)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1181, in _run
[1,0]<stderr>:    feed_dict_tensor, options, run_metadata)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
[1,0]<stderr>:    run_metadata)
[1,0]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
[1,0]<stderr>:    raise type(e)(node_def, op, message)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
[1,0]<stderr>:  (0) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,0]<stderr>:	 [[{{node parser/GatherNd_1}}]]
[1,0]<stderr>:	 [[IteratorGetNext]]
[1,0]<stderr>:  (1) Invalid argument: Requested more than 0 entries, but params is empty.  Params shape: [0,4]
[1,0]<stderr>:	 [[{{node parser/GatherNd_1}}]]
[1,0]<stderr>:	 [[IteratorGetNext]]
[1,0]<stderr>:	 [[DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_efficientnet_b7_blocks_19_se_conv2d_BiasAdd_grad_tuple_control_dependency_1_0/_67987]]
[1,0]<stderr>:0 successful operations.
[1,0]<stderr>:0 derived errors ignored.
[1,1]<stderr>:INFO:tensorflow:training_loop marked as finished
[1,1]<stderr>:I0906 16:38:46.625566 140028042282816 error_handling.py:115] training_loop marked as finished
[1,1]<stderr>:WARNING:tensorflow:Reraising captured error
[1,1]<stderr>:W0906 16:38:46.625751 140028042282816 error_handling.py:149] Reraising captured error
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
[1,1]<stderr>:    return fn(*args)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
[1,1]<stderr>:    target_list, run_metadata)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
[1,1]<stderr>:    run_metadata)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
[1,1]<stderr>:  (0) Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,1]<stderr>:	 [[{{node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0}}]]
[1,1]<stderr>:	 [[DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_efficientnet_b7_blocks_53_tpu_batch_normalization_1_batchnorm_mul_grad_tuple_control_dependency_1_0/_66231]]
[1,1]<stderr>:  (1) Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,1]<stderr>:	 [[{{node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0}}]]
[1,1]<stderr>:0 successful operations.
[1,1]<stderr>:0 derived errors ignored.
[1,1]<stderr>:
[1,1]<stderr>:During handling of the above exception, another exception occurred:
[1,1]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "main.py", line 381, in <module>
[1,1]<stderr>:    app.run(main)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
[1,1]<stderr>:    _run_main(main, args)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
[1,1]<stderr>:    sys.exit(main(argv))
[1,1]<stderr>:  File "main.py", line 374, in main
[1,1]<stderr>:    run_train_and_eval(e)
[1,1]<stderr>:  File "main.py", line 361, in run_train_and_eval
[1,1]<stderr>:    _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
[1,1]<stderr>:  File "main.py", line 277, in _train
[1,1]<stderr>:    max_steps=steps)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
[1,1]<stderr>:    rendezvous.raise_errors()
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
[1,1]<stderr>:    six.reraise(typ, value, traceback)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
[1,1]<stderr>:    raise value
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
[1,1]<stderr>:    saving_listeners=saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
[1,1]<stderr>:    loss = self._train_model(input_fn, hooks, saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
[1,1]<stderr>:    return self._train_model_default(input_fn, hooks, saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
[1,1]<stderr>:    saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1511, in _train_with_estimator_spec
[1,1]<stderr>:    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 778, in run
[1,1]<stderr>:    run_metadata=run_metadata)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
[1,1]<stderr>:    run_metadata=run_metadata)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
[1,1]<stderr>:    raise six.reraise(*original_exc_info)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/[1,1]<stderr>:six.py", line 703, in reraise
[1,1]<stderr>:    raise value
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
[1,1]<stderr>:    return self._sess.run(*args, **kwargs)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
[1,1]<stderr>:    run_metadata=run_metadata)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
[1,1]<stderr>:    return self._sess.run(*args, **kwargs)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 958, in run
[1,1]<stderr>:    run_metadata_ptr)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1181, in _run
[1,1]<stderr>:    feed_dict_tensor, options, run_metadata)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
[1,1]<stderr>:    run_metadata)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
[1,1]<stderr>:    raise type(e)(node_def, op, message)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
[1,1]<stderr>:  (0) Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,1]<stderr>:	 [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0 (defined at <string>:74) ]]
[1,1]<stderr>:	 [[DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_efficientnet_b7_blocks_53_tpu_batch_normalization_1_batchnorm_mul_grad_tuple_control_dependency_1_0/_66231]]
[1,1]<stderr>:  (1) Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,1]<stderr>:	 [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0 (defined at <string>:74) ]]
[1,1]<stderr>:0 successful operations.
[1,1]<stderr>:0 derived errors ignored.
[1,1]<stderr>:
[1,1]<stderr>:Errors may have originated from an input operation.
[1,1]<stderr>:Input Source operations connected to node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0:
[1,1]<stderr>: gradients/AddN_1302 (defined at /home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:300)
[1,1]<stderr>:
[1,1]<stderr>:Input Source operations connected to node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0:
[1,1]<stderr>: gradients/AddN_1302 (defined at /home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:300)
[1,1]<stderr>:
[1,1]<stderr>:Original stack trace for 'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_1302_0':
[1,1]<stderr>:  File "main.py", line 381, in <module>
[1,1]<stderr>:    app.run(main)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
[1,1]<stderr>:    _run_main(main, args)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
[1,1]<stderr>:    sys.exit(main(argv))
[1,1]<stderr>:  File "main.py", line 374, in main
[1,1]<stderr>:    run_train_and_eval(e)
[1,1]<stderr>:  File "main.py", line 361, in run_train_and_eval
[1,1]<stderr>:    _train(e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
[1,1]<stderr>:  File "main.py", line 277, in _train
[1,1]<stderr>:    max_steps=steps)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
[1,1]<stderr>:    saving_listeners=saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
[1,1]<stderr>:    loss = self._train_model(input_fn, hooks, saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
[1,1]<stderr>:    return self._train_model_default(input_fn, hooks, saving_listeners)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, i[1,1]<stderr>:n _train_model_default
[1,1]<stderr>:    self.config)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn
[1,1]<stderr>:    config)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
[1,1]<stderr>:    model_fn_results = self._model_fn(features=features, **kwargs)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3179, in _model_fn
[1,1]<stderr>:    features, labels, is_export_mode=is_export_mode)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1700, in call_without_tpu
[1,1]<stderr>:    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn
[1,1]<stderr>:    estimator_spec = self._model_fn(features=features, **kwargs)
[1,1]<stderr>:  File "/home/user/Desktop/Projects/efficientdet/det_model_fn.py", line 621, in efficientdet_model_fn
[1,1]<stderr>:    variable_filter_fn=variable_filter_fn)
[1,1]<stderr>:  File "/home/user/Desktop/Projects/efficientdet/det_model_fn.py", line 417, in _model_fn
[1,1]<stderr>:    grads_and_vars = optimizer.compute_gradients(total_loss, var_list)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 303, in compute_gradients
[1,1]<stderr>:    avg_grads = self._allreduce_grads(grads)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 257, in allreduce_grads
[1,1]<stderr>:    for grad in grads]
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 257, in <listcomp>
[1,1]<stderr>:    for grad in grads]
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 105, in allreduce
[1,1]<stderr>:    summed_tensor_compressed = _allreduce(tensor_compressed, op=true_op)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 107, in _allreduce
[1,1]<stderr>:    return MPI_LIB.horovod_allreduce(tensor, name=name, reduce_op=op)
[1,1]<stderr>:  File "<string>", line 74, in horovod_allreduce
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
[1,1]<stderr>:    attrs=attr_protos, op_def=op_def)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3493, in _create_op_internal
[1,1]<stderr>:    op_def=op_def)
[1,1]<stderr>:  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1957, in __init__
[1,1]<stderr>:    self._traceback = tf_stack.extract_stack()
[1,1]<stderr>:
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41428,1],0]
  Exit code:    1
```

**Comment by mingxingtan** [comment]
num_examples_per_epoch only affects how many training steps you will run, it shouldn't  cause any training error.
Could you post your command line?

**Comment by aocz1** [comment]
**Command with num_examples_per_epoch specified (equal to the number of examples in the tfrecord:**

horovodrun -np 2 -H localhost:2 python3 main.py --mode=train_and_eval \
    --training_file_pattern=models/vine-nutrition/tfrecords_split/vine-nutrition_train.record \
    --validation_file_pattern=models/vine-nutrition/tfrecords_split/vine-nutrition_val.record \
    --model_name=efficientdet-d7x \
    --model_dir=models/vine-nutrition/checkpoints-main2-d7x_b4_im300  \
    --ckpt=models/efficientdet-d7x \
    --train_batch_size=4 \
    --num_examples_per_epoch=320 \
    --eval_samples=81 \
    --num_epochs=15 \
    --hparams=models/vine-nutrition/config.yaml \
    --run_epoch_in_child_process=False \
    --strategy=horovod


****Command without num_examples_per_epoch specified (which has the error):****

horovodrun -np 2 -H localhost:2 python3 main.py --mode=train_and_eval \
    --training_file_pattern=models/vine-nutrition/tfrecords_split/vine-nutrition_train.record \
    --validation_file_pattern=models/vine-nutrition/tfrecords_split/vine-nutrition_val.record \
    --model_name=efficientdet-d7x \
    --model_dir=models/vine-nutrition/checkpoints-main-d7x_b4_im300  \
    --ckpt=models/efficientdet-d7x \
    --train_batch_size=4 \
    --num_epochs=15 \
    --hparams=models/vine-nutrition/config.yaml \
    --run_epoch_in_child_process=False \
    --strategy=horovod


**config.yaml (for both):**

image_size: 300
use_keras_model: False
skip_mismatch: False

**Comment by aocz1** [comment]
Update:

After a few tests, changing it to 400 num_examples_per_epoch had the training working fine, but going up to 640 made it have the same crash again.

**Comment by aocz1** [comment]
Another update: 

After upgrading to the latest version of the repository, the error hasn't been there, but now the training always runs out of memory. With past versions, I was able to train successfully using these settings, I'm confused as to what has made this change?

**Comment by aocz1** [comment]
Update:

Updating to the latest version of the repo and changing the command to:

python3 main.py --mode=train_and_eval \
    --training_file_pattern=models/vine-nutrition/tfrecords_split/vine-nutrition_train.record \
    --validation_file_pattern=models/vine-nutrition/tfrecords_split/vine-nutrition_val.record \
    --model_name=efficientdet-d7x \
    --model_dir=models/vine-nutrition/checkpoints-main2-d7x_b4_im300  \
    --ckpt=models/efficientdet-d7x \
    --train_batch_size=4 \
    --num_epochs=15 \
    --hparams=models/vine-nutrition/config.yaml \
    --run_epoch_in_child_process=False \
    --strategy=gpus


seems to have fixed it. It may have been an issue with horovod with one of the past versions, I'm not sure.
