### ISSUE TITLE
Error in Inference images from Colab tutorial

### ISSUE THREAD

**Issue by 1chimaruGin** [google/automl#748]
How to fix it?

```
Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 468, in run_model
    kwargs['output_image_dir'], **config_dict)
  File "model_inspect.py", line 185, in saved_model_inference
    img = driver.visualize(raw_images[j], detections_bs[j], **kwargs)
  File "/content/automl/efficientdet/inference.py", line 459, in visualize
    **kwargs)
  File "/content/automl/efficientdet/inference.py", line 316, in visualize_image_prediction
    return visualize_image(image, boxes, classes, scores, label_map, **kwargs)
  File "/content/automl/efficientdet/inference.py", line 280, in visualize_image
    category_index = {k: {'id': k, 'name': label_map[k]} for k in label_map}
TypeError: 'NoneType' object is not iterable
```

**Comment by warren30815** [comment]
You need to assign --hparams to control hparams_config.py default setting parameters (i.e. h.label_map)

**Comment by warren30815** [comment]
For example, create a config txt file which contents are like below. Assume this txt filename is coco_config.yaml

```
  num_classes: 91
  label_map: coco
```

and when you run inference, the command may seem like below:
# Step 2: do inference with saved model.
!python model_inspect.py --runmode=saved_model_infer \
  --model_name=efficientdet-d0  \
  --saved_model_dir=/tmp/saved_model  \
  --input_image=img.png --output_image_dir=/tmp/
  --hparams=coco_config.yaml
# you can visualize the output /tmp/0.jpg

**Comment by 1chimaruGin** [comment]
Thanks @warren30815
