### ISSUE TITLE
Crash on mode eval.  New in f701a0b.

### ISSUE THREAD

**Issue by nemtiax** [google/automl#758]
```I0910 21:40:54.823101 140291405330240 evaluation.py:167] Evaluation [100/100]                           
creating index...                                                                                       
index created!                                                                                          
Loading and preparing results...                                                                        
Converting ndarray to lists...                                                                          
(10000, 7)                                                                                              
0/10000                                                                                                 
DONE (t=0.14s)                                                                                          
creating index...                                                                                       
index created!                                                                                          
Running per image evaluation...                                                                         
Evaluate annotation type *bbox*                                                                         
DONE (t=0.11s).                                                                                         
Accumulating evaluation results...                                                                      
DONE (t=0.01s).                                                                                         
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.260                         
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.530                         
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.279                         
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000                        
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000                        
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.294                         
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.179                         
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.414                         
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.422                         
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000                        
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000                        
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.422                         
Traceback (most recent call last):                                                                      
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 1365, in _do_call                                                                               
    return fn(*args)                                                                                    
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 1350, in _run_fn                                                                                
    target_list, run_metadata)                                                                          
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 1443, in _call_tf_sessionrun                                                                    
    run_metadata)                                                                                       
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.                    
  (0) Invalid argument: pyfunc_2 returns 0 values, but expects to see 1 values.                         
         [[{{node coco_metric/PyFunc_1}}]]                                                              
  (1) Invalid argument: pyfunc_2 returns 0 values, but expects to see 1 values.                         
         [[{{node coco_metric/PyFunc_1}}]]                                                              
         [[coco_metric/PyFunc_1/_4349]]                                                                 
0 successful operations.                                                                                
0 derived errors ignored.

During handling of the above exception, another exception occurred:                                     
                                                                                                        
Traceback (most recent call last):                                                                      
  File "main.py", line 326, in <module>                                                                 
    app.run(main)                                                                                       
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py", line 250, in _run_ma$
n
    sys.exit(main(argv))
  File "main.py", line 297, in main
    eval_results = estimator.evaluate(eval_input_fn, steps=eval_steps)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estima$
or/estimator.py", line 467, in evaluate
    name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estima$
or/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estima$
or/estimator.py", line 499, in _evaluate
    output_dir=self.eval_dir(name))
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estima$
or/estimator.py", line 1644, in _evaluate_run
    config=self._session_config)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/training/evaluat$
on.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/training/monitor$
d_session.py", line 885, in __exit__
    self._close_internal(exception_type)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/training/monitor$
d_session.py", line 918, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/training/basic_s$
ssion_run_hooks.py", line 961, in end
    self._final_ops, feed_dict=self._final_ops_feed_dict)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 958, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 1359, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/client/session.p$
", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: pyfunc_2 returns 0 values, but expects to see 1 values.
         [[node coco_metric/PyFunc_1 (defined at /home/ubuntu/updated/automl/efficientdet/coco_metric.py
:233) ]]
  (1) Invalid argument: pyfunc_2 returns 0 values, but expects to see 1 values.
         [[node coco_metric/PyFunc_1 (defined at /home/ubuntu/updated/automl/efficientdet/coco_metric.py
:233) ]]
         [[coco_metric/PyFunc_1/_4349]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'coco_metric/PyFunc_1':
  File "main.py", line 326, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py", line 250, in _run_mai
n
    sys.exit(main(argv))
  File "main.py", line 297, in main
    eval_results = estimator.evaluate(eval_input_fn, steps=eval_steps)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estimat
or/estimator.py", line 467, in evaluate
    name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estimat
or/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estimat
or/estimator.py", line 492, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estimat
or/estimator.py", line 1528, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estimat
or/estimator.py", line 1564, in _call_model_fn_eval
    config)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_estimator/python/estimat
or/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/ubuntu/updated/automl/efficientdet/det_model_fn.py", line 647, in efficientdet_model_fn
    variable_filter_fn=variable_filter_fn)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/autograph/impl/ap
i.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/updated/automl/efficientdet/det_model_fn.py", line 626, in _model_fn
    eval_metrics[0](**eval_metrics[1]) if eval_metrics else None)
  File "/home/ubuntu/updated/automl/efficientdet/det_model_fn.py", line 508, in metric_fn
    detections_bs, kwargs['groundtruth_data'])
  File "/home/ubuntu/updated/automl/efficientdet/coco_metric.py", line 233, in estimator_metric_fn
    metrics = tf.numpy_function(self.result, [], tf.float32)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py"
, line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py
", line 632, in numpy_function
    return py_func_common(func, inp, Tout, stateful=True, name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py
", line 539, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py
", line 346, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_op
s.py", line 151, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/framework/op_def_
library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/framework/ops.py"
, line 3485, in _create_op_internal
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/python/framework/ops.py"
, line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
```

I'm running this command:

```
python main.py --mode=eval      --model_name=efficientdet-d0  --model_dir=efficientdet-d0      --validation_file_pattern=tfrecord/tamu_test*      --hparams="image_size=1600x1200" --eval_samples=100 --train_batch_size=1 --eval_batch_size=1
```

I verified that this works fine in commit 6e0cb70, but fails in f701a0b.  Maybe a new bug?  @mingxingtan

**Comment by mingxingtan** [comment]
Sorry, it was a typo. Fixed now.
