### ISSUE TITLE
Per-class AP crashes with coco label_map

### ISSUE THREAD

**Issue by nemtiax** [google/automl#762]
Per-class AP seems to work fine with my custom label_map after the latest updates.  However, it seems to crash when using a coco label map.  My hunch is that this is perhaps related to the fact that COCO category IDs are not contiguous, but I haven't been able to nail down the exact cause just yet.  The error occurs both when using the built-in coco label_map (in other words, specifying just the string "coco" as my label map) and when fully specifying the label dictionary in the hparams file. 

```
DONE (t=0.14s)                                                                  
creating index...                                                               
index created!                                                                  
Running per image evaluation...                                                 
Evaluate annotation type *bbox*                                                 
DONE (t=0.11s).                                                                 
Accumulating evaluation results...                                              
DONE (t=0.01s).                                                                 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.259 
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.530 
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.262 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.292 
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.180 
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.414 
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.421 
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.421 
2020-09-11 15:28:04.184299: W tensorflow/core/framework/op_kernel.cc:1767] OP_RE
QUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 12 of d
imension 0 out of bounds.                                                       
2020-09-11 15:28:04.184314: W tensorflow/core/framework/op_kernel.cc:1767] OP_RE
QUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 13 of d
imension 0 out of bounds.                

[SNIPPED MANY MORE INVALID ARGUMENT LINES]

2020-09-11 15:28:04.184330: W tensorflow/core/framework/op_kernel.cc:1767] OP_RE
QUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 20 of d
imension 0 out of bounds.                                                       
Traceback (most recent call last):                                              
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1365, in _do_call                               
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow$
python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow$
python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) f$
und.
  (0) Invalid argument: slice index 12 of dimension 0 out of bounds.
         [[{{node coco_metric/strided_slice_12}}]]
         [[coco_metric/strided_slice_33/_4403]]
  (1) Invalid argument: slice index 12 of dimension 0 out of bounds.
         [[{{node coco_metric/strided_slice_12}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 328, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py
", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py
", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 299, in main
    eval_results = estimator.evaluate(eval_input_fn, steps=eval_steps)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 467, in evaluate
    name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 499, in _evaluate
    output_dir=self.eval_dir(name))
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 1644, in _evaluate_run
    config=self._session_config)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/training/monitored_session.py", line 885, in __exit__
    self._close_internal(exception_type)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/training/monitored_session.py", line 918, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/training/basic_session_run_hooks.py", line 961, in end
    self._final_ops, feed_dict=self._final_ops_feed_dict)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) fo
und.
  (0) Invalid argument: slice index 12 of dimension 0 out of bounds.
         [[node coco_metric/strided_slice_12 (defined at /home/ubuntu/updated/au
toml/efficientdet/coco_metric.py:245) ]]
         [[coco_metric/strided_slice_33/_4403]]
  (1) Invalid argument: slice index 12 of dimension 0 out of bounds.
         [[node coco_metric/strided_slice_12 (defined at /home/ubuntu/updated/au
toml/efficientdet/coco_metric.py:245) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node coco_metric/strided_slice_12:
 coco_metric/PyFunc_1 (defined at /home/ubuntu/updated/automl/efficientdet/coco_
metric.py:235)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) fo
und.
  (0) Invalid argument: slice index 12 of dimension 0 out of bounds.
         [[node coco_metric/strided_slice_12 (defined at /home/ubuntu/updated/au
toml/efficientdet/coco_metric.py:245) ]]
         [[coco_metric/strided_slice_33/_4403]]
  (1) Invalid argument: slice index 12 of dimension 0 out of bounds.
         [[node coco_metric/strided_slice_12 (defined at /home/ubuntu/updated/au
toml/efficientdet/coco_metric.py:245) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node coco_metric/strided_slice_12:
 coco_metric/PyFunc_1 (defined at /home/ubuntu/updated/automl/efficientdet/coco_
metric.py:235)
Input Source operations connected to node coco_metric/strided_slice_12:
 coco_metric/PyFunc_1 (defined at /home/ubuntu/updated/automl/efficientdet/coco_
metric.py:235)

Original stack trace for 'coco_metric/strided_slice_12':
  File "main.py", line 328, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py
", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/absl/app.py
", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 299, in main
    eval_results = estimator.evaluate(eval_input_fn, steps=eval_steps)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 467, in evaluate
    name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 492, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 1528, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 1564, in _call_model_fn_eval
    config)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow_
estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/ubuntu/updated/automl/efficientdet/det_model_fn.py", line 647, in
efficientdet_model_fn
    variable_filter_fn=variable_filter_fn)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/updated/automl/efficientdet/det_model_fn.py", line 626, in
_model_fn
    eval_metrics[0](**eval_metrics[1]) if eval_metrics else None)
  File "/home/ubuntu/updated/automl/efficientdet/det_model_fn.py", line 508, in
metric_fn
    detections_bs, kwargs['groundtruth_data'])
  File "/home/ubuntu/updated/automl/efficientdet/coco_metric.py", line 245, in e
stimator_metric_fn
    metrics_dict[name] = (metrics[i + len(self.metric_names)],
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/ops/array_ops.py", line 1024, in _slice_helper
    name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/ops/array_ops.py", line 1196, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/ops/gen_array_ops.py", line 10352, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tf23/lib/python3.6/site-packages/tensorflow/
python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by nemtiax** [comment]
Interestingly, setting label_map: {1: person} seems to work (in that it gives AP for the person class), but setting it to {1: person, 2: bicycle} crashes.  I wonder if maybe the problem is that i don't have any bicycles in my eval set?

**Comment by 1345-os** [comment]
El 11 sep. 2020 12:26 p. m., "nemtiax" <notifications@github.com> escribió:

Interestingly, setting label_map: {1: person} seems to work (in that it
gives AP for the person class), but setting it to {1: person, 2: bicycle}
crashes. I wonder if maybe the problem is that i don't have any bicycles in
my eval set?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/automl/issues/762#issuecomment-691220019>, or
unsubscribe
