### ISSUE TITLE
getting     ValueError: None values not supported. when use_keras_model : Flase in recent versions of master

### ISSUE THREAD

**Issue by sadransh** [google/automl#773]
I am getting this error when using this command 
`
python main.py --mode=train_and_eval     --training_file_pattern=...    --validation_file_pattern=...     --model_name=efficientdet-d4     --model_dir=/tf/d4v2c      --backbone_ckpt=efficientdet-d4      --train_batch_size=4     --eval_batch_size=4 --eval_samples=2111     --num_examples_per_epoch=11002 --num_epochs=100      --hparams=cfg.yaml     --save_checkpoints_steps=3000     --eval_after_training=True     --run_epoch_in_child_process=True     --strategy=gpus`

and config of : 

`
mixed_precision: True
num_classes: 5
learning_rate: 0.08
lr_warmup_init: 0.008  
moving_average_decay: 0.9998
label_smoothing : 0.1
autoaugment_policy: "v2"
label_map: {1: class1, 2: class2, 3: class3, 4: calss4}
nms_configs : {'method': 'gaussian' ,'iou_thresh' : .4, 'score_thresh' : 0.001 ,'sigma': .3 ,'max_nms_inputs': 0,'max_output_size': 100}
use_keras_model: False
`

```
I0915 04:39:07.387429 139729429321472 efficientdet_arch.py:490] fnode 5 : {'feat_level': 5, 'inputs_offsets': [2, 6, 9]}
I0915 04:39:07.612767 139729429321472 efficientdet_arch.py:490] fnode 6 : {'feat_level': 6, 'inputs_offsets': [3, 5, 10]}
I0915 04:39:07.846163 139729429321472 efficientdet_arch.py:490] fnode 7 : {'feat_level': 7, 'inputs_offsets': [4, 11]}
I0915 04:39:11.314271 139729429321472 efficientdet_arch.py:570] backbone+fpn params/flops = 20.092444M, 41.806458457B
I0915 04:39:23.199624 139729429321472 efficientdet_arch.py:575] backbone+fpn+box params/flops = 20.594474M, 52.369228905B
I0915 04:39:23.200360 139729429321472 utils.py:635] use mixed precision policy name float32
I0915 04:39:23.204252 139729429321472 det_model_fn.py:77] LR schedule method: cosine
I0915 04:39:23.559708 139729429321472 utils.py:417] Adding scale summary ('lrn_rate', <tf.Tensor 'Select:0' shape=() dtype=float32>)
I0915 04:39:23.560529 139729429321472 utils.py:417] Adding scale summary ('trainloss/cls_loss', <tf.Tensor 'AddN:0' shape=() dtype=float32>)
I0915 04:39:23.561267 139729429321472 utils.py:417] Adding scale summary ('trainloss/box_loss', <tf.Tensor 'AddN_1:0' shape=() dtype=float32>)
I0915 04:39:23.562013 139729429321472 utils.py:417] Adding scale summary ('trainloss/det_loss', <tf.Tensor 'add_4:0' shape=() dtype=float32>)
I0915 04:39:23.562744 139729429321472 utils.py:417] Adding scale summary ('trainloss/reg_l2_loss', <tf.Tensor 'mul_14:0' shape=() dtype=float32>)
I0915 04:39:23.563478 139729429321472 utils.py:417] Adding scale summary ('trainloss/loss', <tf.Tensor 'add_5:0' shape=() dtype=float32>)
I0915 04:39:23.565688 139729429321472 utils.py:417] Adding scale summary ('train_epochs', <tf.Tensor 'truediv_7:0' shape=()dtype=float32>)
I0915 04:39:23.591233 139729429321472 det_model_fn.py:429] clip gradients norm by 10.000000
INFO:tensorflow:Error reported to Coordinator: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:436 _model_fn  
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /tf/automl/efficientdet/det_model_fn.py:436 <listcomp>
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapperreturn target(*args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/clip_ops.py:217 clip_by_norm
        t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1499 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:444 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:436 _model_fn  
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /tf/automl/efficientdet/det_model_fn.py:436 <listcomp>
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/clip_ops.py:217 clip_by_norm
        t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1499 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:444 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.

I0915 04:39:32.481075 139729429321472 coordinator.py:219] Error reported to Coordinator: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:436 _model_fn  
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /tf/automl/efficientdet/det_model_fn.py:436 <listcomp>
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapperreturn target(*args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/clip_ops.py:217 clip_by_norm
        t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1499 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:444 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:436 _model_fn  
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /tf/automl/efficientdet/det_model_fn.py:436 <listcomp>
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapperreturn target(*args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/clip_ops.py:217 clip_by_norm
        t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1499 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:444 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.

Traceback (most recent call last):
  File "main.py", line 330, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 324, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 505, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 646, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 747, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1173, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1235, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1319, in _actual_train_model_distributed
    self.config))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 585, in _call_for_each_replica
    self._container_strategy(), fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 96, in call_for_each_replica
    return _call_for_each_replica(strategy, fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 237, in _call_for_each_replica
    coord.join(threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:436 _model_fn  
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /tf/automl/efficientdet/det_model_fn.py:436 <listcomp>
        clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/clip_ops.py:217 clip_by_norm
        t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1499 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:444 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.
```
But with **removing** `use_keras_model: False` everything goes fine.
Can anyone help with this?

**Comment by staeff777** [comment]
Can you check what happens, if you add the var_freeze_expr: "'(efficientnet|fpn_cells|resample_p6)'" ?

**Comment by sadransh** [comment]
this is the error after that : 
```

I0915 07:54:13.842546 140511314695936 utils.py:417] Adding scale summary ('lrn_rate', <tf.Tensor 'replica_3/Select:0' shape=() dtype=float32>)
I0915 07:54:13.843340 140511314695936 utils.py:417] Adding scale summary ('trainloss/cls_loss', <tf.Tensor 'replica_3/AddN:0' shape=() dtype=float32>)
I0915 07:54:13.844067 140511314695936 utils.py:417] Adding scale summary ('trainloss/box_loss', <tf.Tensor 'replica_3/AddN_1:0' shape=() dtype=float32>)
I0915 07:54:13.844778 140511314695936 utils.py:417] Adding scale summary ('trainloss/det_loss', <tf.Tensor 'replica_3/add_4:0' shape=() dtype=float32>)
I0915 07:54:13.845489 140511314695936 utils.py:417] Adding scale summary ('trainloss/reg_l2_loss', <tf.Tensor 'replica_3/mul_14:0' shape=() dtype=float32>)
I0915 07:54:13.846198 140511314695936 utils.py:417] Adding scale summary ('trainloss/loss', <tf.Tensor 'replica_3/add_5:0' shape=() dtype=float32>)
I0915 07:54:13.848255 140511314695936 utils.py:417] Adding scale summary ('train_epochs', <tf.Tensor 'replica_3/truediv_7:0' shape=() dtype=float32>)
I0915 07:54:13.877486 140511314695936 det_model_fn.py:429] clip gradients norm by 10.000000
I0915 07:54:17.815767 140511314695936 utils.py:417] Adding scale summary ('gradient_norm', <tf.Tensor 'replica_3/clip/global_norm_1/global_norm:0' shape=() dtype=float32>)
INFO:tensorflow:batch_all_reduce: 114 all-reduces with algorithm = nccl, num_packs = 1
I0915 07:54:17.854071 140536179390272 cross_device_ops.py:702] batch_all_reduce: 114 all-reduces with algorithm = nccl, num_packs = 1
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/values.py:516: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0915 07:54:31.076457 140511331481344 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/values.py:516: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Error reported to Coordinator: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:450 _model_fn  **
        train_op = ema.apply(ema_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:460 apply
        colocate_with_primary=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/slot_creator.py:132 create_slot
        with distribution_strategy.extended.colocate_vars_with(primary):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2127 colocate_vars_with
        self._validate_colocate_with_variable(colocate_with_variable)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:454 _validate_colocate_with_variable
        colocate_with_variable, self)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_utils.py:234 validate_colocate_distributed_variable
        "tf.distribute.Strategy.scope(), not: %r" % (v,))

    ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'fpn_cells/cell_0/fnode1/WSM:0' shape=() dtype=float32>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:450 _model_fn  **
        train_op = ema.apply(ema_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:460 apply
        colocate_with_primary=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/slot_creator.py:132 create_slot
        with distribution_strategy.extended.colocate_vars_with(primary):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2127 colocate_vars_with
        self._validate_colocate_with_variable(colocate_with_variable)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:454 _validate_colocate_with_variable
        colocate_with_variable, self)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_utils.py:234 validate_colocate_distributed_variable
        "tf.distribute.Strategy.scope(), not: %r" % (v,))

    ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'fpn_cells/cell_0/fnode1/WSM:0' shape=() dtype=float32>

I0915 07:54:31.252108 140511331481344 coordinator.py:219] Error reported to Coordinator: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:450 _model_fn  **
        train_op = ema.apply(ema_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:460 apply
        colocate_with_primary=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/slot_creator.py:132 create_slot
        with distribution_strategy.extended.colocate_vars_with(primary):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2127 colocate_vars_with
        self._validate_colocate_with_variable(colocate_with_variable)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:454 _validate_colocate_with_variable
        colocate_with_variable, self)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_utils.py:234 validate_colocate_distributed_variable
        "tf.distribute.Strategy.scope(), not: %r" % (v,))

    ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'fpn_cells/cell_0/fnode1/WSM:0' shape=() dtype=float32>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:450 _model_fn  **
        train_op = ema.apply(ema_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:460 apply
        colocate_with_primary=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/slot_creator.py:132 create_slot
        with distribution_strategy.extended.colocate_vars_with(primary):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2127 colocate_vars_with
        self._validate_colocate_with_variable(colocate_with_variable)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:454 _validate_colocate_with_variable
        colocate_with_variable, self)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_utils.py:234 validate_colocate_distributed_variable
        "tf.distribute.Strategy.scope(), not: %r" % (v,))

    ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'fpn_cells/cell_0/fnode1/WSM:0' shape=() dtype=float32>

Traceback (most recent call last):
  File "main.py", line 330, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 324, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 505, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 646, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 747, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1173, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1235, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1319, in _actual_train_model_distributed
    self.config))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 585, in _call_for_each_replica
    self._container_strategy(), fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 96, in call_for_each_replica
    return _call_for_each_replica(strategy, fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 237, in _call_for_each_replica
    coord.join(threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /tf/automl/efficientdet/det_model_fn.py:645 efficientdet_model_fn  *
        params,
    /tf/automl/efficientdet/det_model_fn.py:450 _model_fn  **
        train_op = ema.apply(ema_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:460 apply
        colocate_with_primary=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/slot_creator.py:132 create_slot
        with distribution_strategy.extended.colocate_vars_with(primary):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2127 colocate_vars_with
        self._validate_colocate_with_variable(colocate_with_variable)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:454 _validate_colocate_with_variable
        colocate_with_variable, self)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_utils.py:234 validate_colocate_distributed_variable
        "tf.distribute.Strategy.scope(), not: %r" % (v,))

    ValueError: `colocate_vars_with` must only be passed a variable created in this tf.distribute.Strategy.scope(), not: <tf.Variable 'fpn_cells/cell_0/fnode1/WSM:0' shape=() dtype=float32>

```

**Comment by staeff777** [comment]
This seems to be #755 

set `moving_average_decay: 0` to prevent this error. I still don't know, why this error does occur.

If this configuration runs, try to remove the `fpn_cells` from freeze. This would be interesting for me. (Thanks in advance)

**Comment by sadransh** [comment]
Did it work for you? 

I will check that as soon as I get access to the system. However, I want to train from scratch for my purpose so freezing is not an option for me ....

**Comment by staeff777** [comment]
My configuration works with `moving_average_decay:0`  and a freeze that includes the `fpn_cells` .
I assume the `fpn_cells` are some source for the problem.. It would be interesting, if it will fail with your configuration too.

**Comment by sadransh** [comment]
I just added `moving_average_decay: 0 use_keras_model: False ` but the 1st error happened. then I added 
only `var_freeze_expr: '(fpn_cells)'` and it did not send that Nan error. Not sure whether only freezing fpn_cells is correct or not.

**Comment by staeff777** [comment]
@mingxingtan could it be that in the legacy model the `fpn_cells` are not initialized correctly?

**Comment by mingxingtan** [comment]
Could you retry your command line with the following change:

det_model_fn.py:436   comment out this line:

    # clipped_grads = [tf.clip_by_norm(g, clip_norm) for g in grads]
