### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xuxu2014** [google/automl#775]
when do "EfficientDet Tutorial: inference, eval, and training",I am getting this error when using the following command
python model_inspect.py --runmode=infer --model_name=efficientdet-d0 \
  --hparams="image_size=1920x1280"  --max_boxes_to_draw=100   --min_score_thresh=0.4 \
  --ckpt_path=efficientdet-d0 \  --input_image=img.png --output_image_dir=/tmp

the details as follows:

python model_inspect.py --runmode=infer --model_name=efficientdet-d0 \
  --hparams="image_size=1920x1280"  --max_boxes_to_draw=100   --min_score_thresh=0.4 \
  --ckpt_path=efficientdet-d0 \  --input_image=img.png --output_image_dir=/tmp
2020-09-10 10:56:05.710413: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-10 10:56:05.722022: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa266afb7f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-10 10:56:05.722059: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /Users/sunxu/anaconda2/envs/tensorflow2/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0910 10:56:06.873264 4417506752 deprecation.py:506] From /Users/sunxu/anaconda2/envs/tensorflow2/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /Users/sunxu/anaconda2/envs/tensorflow2/lib/python3.7/site-packages/tensorflow_core/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0910 10:56:15.295500 4417506752 deprecation.py:323] From /Users/sunxu/anaconda2/envs/tensorflow2/lib/python3.7/site-packages/tensorflow_core/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/Users/sunxu/anaconda2/envs/tensorflow2/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/sunxu/anaconda2/envs/tensorflow2/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 465, in run_model
    kwargs['output_image_dir'], **config_dict)
  File "model_inspect.py", line 257, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/Users/sunxu/automl/efficientdet/inference.py", line 691, in inference
    **kwargs)
  File "/Users/sunxu/automl/efficientdet/inference.py", line 316, in visualize_image_prediction
    return visualize_image(image, boxes, classes, scores, label_map, **kwargs)
  File "/Users/sunxu/automl/efficientdet/inference.py", line 280, in visualize_image
    category_index = {k: {'id': k, 'name': label_map[k]} for k in label_map}
TypeError: 'NoneType' object is not iterable

Can anyone can help with this,thank you

**Comment by mingxingtan** [comment]
Please run "git pull" to get the latest code, and your problem should be gone.
