### ISSUE TITLE
Problems in transforming coco data set？

### ISSUE THREAD

**Issue by honghande** [google/automl#80]
I use coco data set for format conversion. The command is as follows:
// convert coco data to tfrecord.
mkdir tfrecrod_train
PYTHONPATH=".:$PYTHONPATH"  python dataset/create_coco_tfrecord.py \
    --image_dir=/data/internet/AI/coco_data/val2017 \
    --caption_annotations_file=/data/internet/AI/coco_data/annotations/captions_train2017.json \
    --output_file_prefix=tfrecrod_train/train \
    --num_shards=32
The following problems occurred：
2020-03-28 11:06:22.186620: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-28 11:06:22.187701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
I0328 11:06:22.636374 140272402569024 create_coco_tfrecord.py:286] writing to output path: tfrecrod_train/train
I0328 11:06:24.055881 140272402569024 create_coco_tfrecord.py:238] Building caption index.
I0328 11:06:24.298652 140272402569024 create_coco_tfrecord.py:250] 0 images are missing captions.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "dataset/create_coco_tfrecord.py", line 203, in _pool_create_tf_example
    return create_tf_example(*args)
  File "dataset/create_coco_tfrecord.py", line 110, in create_tf_example
    encoded_jpg = fid.read()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /data/internet/AI/coco_data/val2017/000000391895.jpg; No such file or directory
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dataset/create_coco_tfrecord.py", line 364, in <module>
    tf.app.run(main)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "dataset/create_coco_tfrecord.py", line 360, in main
    FLAGS.include_masks)
  File "dataset/create_coco_tfrecord.py", line 322, in _create_tf_record_from_coco_annotations
    include_masks) for image in images])):
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
tensorflow.python.framework.errors_impl.NotFoundError: /data/internet/AI/coco_data/val2017/000000391895.jpg; No such file or directory

**Comment by CraigWang1** [comment]
Hmm, it says the file doesn't exist, maybe check your path?

Should image_dir be `/data/internet/AI/coco_data/images/val2017` instead of `/data/internet/AI/coco_data/val2017?`

**Comment by guruzen** [comment]
PYTHONPATH=".:$PYTHONPATH" python dataset/create_coco_tfrecord.py
--image_dir=/data/internet/AI/coco_data/val2017
--caption_annotations_file=/data/internet/AI/coco_data/annotations/captions_train2017.json
--output_file_prefix=tfrecrod_train/train
--num_shards=32

You are creating "train" tfrecords whereas you are passing image_dir as "val2017". It has to be "train2017". 

PYTHONPATH=".:$PYTHONPATH"  python3 dataset/create_coco_tfrecord.py \
    --image_dir=<cocopath>/train2017 \
    --caption_annotations_file=annotations/captions_train2017.json \
    --output_file_prefix=tfrecord/train \
    --num_shards=32

**Comment by honghande** [comment]
Thank you. It's settled
