### ISSUE TITLE
Can not training with efficientDet-d5

### ISSUE THREAD

**Issue by JK-Pair** [google/automl#816]
Hello, everyone

I tried to train the efficientDet-d5 model with config
```
label_smoothing: 0.1
learning_rate: 0.008
lr_warmup_init: 0.0008
max_instances_per_image: 1000
mixed_precision: true
moving_average_decay: 0
num_classes: 5
optimizer: adam
use_keras_model: false
var_freeze_expr: (efficientnet)
```

But I got an error like this below.

```
2020-10-04 08:43:08.477696: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Stats: 
Limit:                     15695549568
InUse:                     15663027712
MaxInUse:                  15663041792
NumAllocs:                        5778
MaxAllocSize:               2985641216
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2020-10-04 08:43:08.477834: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ****************************************************************************************************
2020-10-04 08:43:08.477891: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops.cc:539 : Resource exhausted: OOM when allocating tensor with shape[16,384,160,160] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[16,384,160,160] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[clip/global_norm_1/global_norm/_18373]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[16,384,160,160] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 343, in run_train_and_eval
    max_steps=e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1511, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[16,384,160,160] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d (defined at /content/automl/efficientdet/efficientdet_arch.py:525) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[clip/global_norm_1/global_norm/_18373]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[16,384,160,160] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d (defined at /content/automl/efficientdet/efficientdet_arch.py:525) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d:
 Cast_143 (defined at /content/automl/efficientdet/utils.py:566)

Input Source operations connected to node fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d:
 Cast_143 (defined at /content/automl/efficientdet/utils.py:566)

Original stack trace for 'fpn_cells/cell_5/fnode3/op_after_combine8/conv/separable_conv2d':
  File "main.py", line 365, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 353, in main
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 343, in run_train_and_eval
    max_steps=e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/content/automl/efficientdet/det_model_fn.py", line 671, in efficientdet_model_fn
    variable_filter_fn=variable_filter_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/content/automl/efficientdet/det_model_fn.py", line 369, in _model_fn
    precision, model_fn, features, params['is_training_bn'])
  File "/content/automl/efficientdet/utils.py", line 628, in build_model_with_precision
    outputs = mm(inputs, *args, **kwargs)
  File "/content/automl/efficientdet/efficientdet_arch.py", line 568, in efficientdet
    fpn_feats = build_feature_network(features, config)
  File "/content/automl/efficientdet/efficientdet_arch.py", line 400, in build_feature_network
    new_feats = build_bifpn_layer(feats, feat_sizes, config)
  File "/content/automl/efficientdet/efficientdet_arch.py", line 525, in build_bifpn_layer
    name='conv')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/legacy_tf_layers/convolutional.py", line 1096, in separable_conv2d
    return layer.apply(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1701, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 547, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 776, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 2198, in call
    data_format=conv_utils.convert_data_format(self.data_format, ndim=4))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py", line 1067, in separable_conv2d
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 2274, in conv2d
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 979, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
```

Thank you for your help.

**Comment by kartik4949** [comment]
@JK-Pair You have three options 
1. Enable Gradient Checkpointing - more training time.
2. Lower batch-size - slightly worst result
3. freeze more layers. - can effect results in bad way (not sure.)
Thanks

**Comment by JK-Pair** [comment]
> @JK-Pair You have three options
> 
> 1. Enable Gradient Checkpointing - more training time. (recommended )
> 2. Lower batch-size - slightly worst result
> 3. freeze more layers. - can effect results in bad way (not sure.)
>    Thanks

Thank you for you help.

1. What do you mean enable gradient checkpointing?
2. Lower bath-size can't help, I already try it.
3. Right!, If freeze more layers the result is bad.

**Comment by Steve-2040** [comment]
If you see 'Resource exhausted: OOM' it indicates out of memory (e.g. GPU or CPU memory insufficient). You can reduce the batch size  --train_batch_size=64 to e.g. --train_batch_size=1. There is also the grad_ckpting if set to true like:
```
device: [grad_ckpting: True]
```
that will reduce memory usage. This was recently added so you need the latest master commit for grad_ckpting (I have not used it my self). Also it is good to close other programs sometimes even restart PC before training to reduce memory usage from other programs. I was a bit slow I see kartik4949 already commented.

**Comment by JK-Pair** [comment]
> If you see 'Resource exhausted: OOM' it indicates out of memory (e.g. GPU or CPU memory insufficient). You can reduce the batch size --train_batch_size=64 to e.g. --train_batch_size=1. There is also the grad_ckpting if set to true like:
> 
> ```
> device: {grad_ckpting: True}
> ```
> 
> that will reduce memory usage. This was recently added so you need the latest master commit for grad_ckpting (I have not used it myself). Also, it is good to close other programs sometimes even restart the PC before training to reduce memory usage from other programs. I was a bit slow I see kartik4949 already commented.

Yes! Now, I can run, It's useful.
Thank you!
