### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_model_optimization'

### ISSUE THREAD

**Issue by fitoule** [google/automl#847]
latest code (this mornning) gives me ModuleNotFoundError: No module named 'tensorflow_model_optimization'

**Comment by fitoule** [comment]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 10:55:44.683771: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 10:55:46.494393: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 10:55:48.320991: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 10:55:50.165405: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
(tfn) obs@obs-System-Product-Name:~/EfficientDet/automl/efficientdet$ sh montrain.sh
2020-10-31 11:00:43.679463: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 11:00:45.291407: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 11:00:46.878601: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 11:00:48.488035: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'
2020-10-31 11:00:50.061905: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    import det_model_fn
  File "/home/obs/EfficientDet/automl/efficientdet/det_model_fn.py", line 28, in <module>
    from keras import efficientdet_keras
  File "/home/obs/EfficientDet/automl/efficientdet/keras/efficientdet_keras.py", line 29, in <module>
    from keras import model_optimization
  File "/home/obs/EfficientDet/automl/efficientdet/keras/model_optimization.py", line 18, in <module>
    import tensorflow_model_optimization as tfmot
ModuleNotFoundError: No module named 'tensorflow_model_optimization'

**Comment by fitoule** [comment]
python3 -m pip install tensorflow-model-optimization
