### ISSUE TITLE
AttributeError: module 'tensorflow.keras.initializers' has no attribute 'variance_scaling'

### ISSUE THREAD

**Issue by azhar-autocanvas** [google/automl#884]
I get the above error after running the command `python model_inspect.py --runmode=bm --model_name=efficientdet-d0` to measure network latency.

I have tensorflow 2.2.0

Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/home/azhar/anaconda3/envs/effdet/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/azhar/anaconda3/envs/effdet/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 501, in main
    inspector.run_model(
  File "model_inspect.py", line 473, in run_model
    self.benchmark_model(
  File "model_inspect.py", line 373, in benchmark_model
    output = self.build_model(inputs)
  File "model_inspect.py", line 127, in build_model
    cls_outputs, box_outputs = inference.build_model(
  File "/media/azhar/ai_data/Azhar/automl/efficientdet/inference.py", line 161, in build_model
    cls_outputs, box_outputs = utils.build_model_with_precision(
  File "/media/azhar/ai_data/Azhar/automl/efficientdet/utils.py", line 630, in build_model_with_precision
    outputs = mm(ii, *args, **kwargs)
  File "/media/azhar/ai_data/Azhar/automl/efficientdet/inference.py", line 147, in model_arch
    model = efficientdet_keras.EfficientDetNet(config=config)
  File "/media/azhar/ai_data/Azhar/automl/efficientdet/keras/efficientdet_keras.py", line 806, in __init__
    self.class_net = ClassNet(
  File "/media/azhar/ai_data/Azhar/automl/efficientdet/keras/efficientdet_keras.py", line 394, in __init__
    pointwise_initializer=tf.initializers.variance_scaling(),
AttributeError: module 'tensorflow.keras.initializers' has no attribute 'variance_scaling'

**Comment by Ted678Wu** [comment]
I met this issue too, we need to update TensorFlow to 2.3.0, they just update the requirements.txt. hope it helps
