### ISSUE TITLE
Issue using grad_checkpoint

### ISSUE THREAD

**Issue by aocz1** [google/automl#886]
I've been unable to use the grad_checkpoint hparam while training. The following error occurs:

**Error log**
```
INFO:tensorflow:Error reported to Coordinator: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:616 efficientdet_model_fn  *
        params,
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:341 _model_fn  **
        precision, model_fn, features, params['is_training_bn'])
    /home/user/Desktop/Projects/efficientdet/utils.py:630 build_model_with_precision
        outputs = mm(ii, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:330 model_fn
        cls_out_list, box_out_list = model(inputs, params['is_training_bn'])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/keras/efficientdet_keras.py:856 call  **
        all_feats = self.backbone(inputs, training=training, features_only=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:757 call  **
        outputs = block(outputs, training=training, survival_prob=survival_prob)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:417 call  **
        return _call(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:264 __call__
        return self._d(self._f, a, k)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:220 decorated
        return _graph_mode_decorator(wrapped, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:347 _graph_mode_decorator
        for v in get_dependent_variables(input_ops=inputs, output_ops=result)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 get_dependent_variables
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 <listcomp>
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:302 <genexpr>
        tf_vars = (get_variable_by_name(var_name) for var_name in var_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:276 get_variable_by_name
        raise ValueError("Unsuccessful at finding variable {}.".format(var_name))

    ValueError: Unsuccessful at finding variable efficientnet-b7/blocks_0/tpu_batch_normalization_1/moving_variance/replica_1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:616 efficientdet_model_fn  *
        params,
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:341 _model_fn  **
        precision, model_fn, features, params['is_training_bn'])
    /home/user/Desktop/Projects/efficientdet/utils.py:630 build_model_with_precision
        outputs = mm(ii, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:330 model_fn
        cls_out_list, box_out_list = model(inputs, params['is_training_bn'])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/keras/efficientdet_keras.py:856 call  **
        all_feats = self.backbone(inputs, training=training, features_only=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:757 call  **
        outputs = block(outputs, training=training, survival_prob=survival_prob)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:417 call  **
        return _call(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:264 __call__
        return self._d(self._f, a, k)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:220 decorated
        return _graph_mode_decorator(wrapped, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:347 _graph_mode_decorator
        for v in get_dependent_variables(input_ops=inputs, output_ops=result)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 get_dependent_variables
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 <listcomp>
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:302 <genexpr>
        tf_vars = (get_variable_by_name(var_name) for var_name in var_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:276 get_variable_by_name
        raise ValueError("Unsuccessful at finding variable {}.".format(var_name))

    ValueError: Unsuccessful at finding variable efficientnet-b7/blocks_0/tpu_batch_normalization_1/moving_variance/replica_1.

I1125 15:21:24.640780 140470898374400 coordinator.py:219] Error reported to Coordinator: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:616 efficientdet_model_fn  *
        params,
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:341 _model_fn  **
        precision, model_fn, features, params['is_training_bn'])
    /home/user/Desktop/Projects/efficientdet/utils.py:630 build_model_with_precision
        outputs = mm(ii, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:330 model_fn
        cls_out_list, box_out_list = model(inputs, params['is_training_bn'])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/keras/efficientdet_keras.py:856 call  **
        all_feats = self.backbone(inputs, training=training, features_only=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:757 call  **
        outputs = block(outputs, training=training, survival_prob=survival_prob)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:417 call  **
        return _call(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:264 __call__
        return self._d(self._f, a, k)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:220 decorated
        return _graph_mode_decorator(wrapped, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:347 _graph_mode_decorator
        for v in get_dependent_variables(input_ops=inputs, output_ops=result)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 get_dependent_variables
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 <listcomp>
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:302 <genexpr>
        tf_vars = (get_variable_by_name(var_name) for var_name in var_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:276 get_variable_by_name
        raise ValueError("Unsuccessful at finding variable {}.".format(var_name))

    ValueError: Unsuccessful at finding variable efficientnet-b7/blocks_0/tpu_batch_normalization_1/moving_variance/replica_1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:616 efficientdet_model_fn  *
        params,
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:341 _model_fn  **
        precision, model_fn, features, params['is_training_bn'])
    /home/user/Desktop/Projects/efficientdet/utils.py:630 build_model_with_precision
        outputs = mm(ii, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:330 model_fn
        cls_out_list, box_out_list = model(inputs, params['is_training_bn'])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/keras/efficientdet_keras.py:856 call  **
        all_feats = self.backbone(inputs, training=training, features_only=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:757 call  **
        outputs = block(outputs, training=training, survival_prob=survival_prob)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:417 call  **
        return _call(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:264 __call__
        return self._d(self._f, a, k)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:220 decorated
        return _graph_mode_decorator(wrapped, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:347 _graph_mode_decorator
        for v in get_dependent_variables(input_ops=inputs, output_ops=result)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 get_dependent_variables
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 <listcomp>
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:302 <genexpr>
        tf_vars = (get_variable_by_name(var_name) for var_name in var_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:276 get_variable_by_name
        raise ValueError("Unsuccessful at finding variable {}.".format(var_name))

    ValueError: Unsuccessful at finding variable efficientnet-b7/blocks_0/tpu_batch_normalization_1/moving_variance/replica_1.

Traceback (most recent call last):
  File "main.py", line 367, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 360, in main
    run_train_and_eval(e)
  File "main.py", line 345, in run_train_and_eval
    max_steps=e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1173, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1235, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1319, in _actual_train_model_distributed
    self.config))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 585, in _call_for_each_replica
    self._container_strategy(), fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 96, in call_for_each_replica
    return _call_for_each_replica(strategy, fn, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 237, in _call_for_each_replica
    coord.join(threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1163 _call_model_fn  *
        model_fn_results = self._model_fn(features=features, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:616 efficientdet_model_fn  *
        params,
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:341 _model_fn  **
        precision, model_fn, features, params['is_training_bn'])
    /home/user/Desktop/Projects/efficientdet/utils.py:630 build_model_with_precision
        outputs = mm(ii, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/det_model_fn.py:330 model_fn
        cls_out_list, box_out_list = model(inputs, params['is_training_bn'])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/keras/efficientdet_keras.py:856 call  **
        all_feats = self.backbone(inputs, training=training, features_only=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:757 call  **
        outputs = block(outputs, training=training, survival_prob=survival_prob)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/user/Desktop/Projects/efficientdet/backbone/efficientnet_model.py:417 call  **
        return _call(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:264 __call__
        return self._d(self._f, a, k)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:220 decorated
        return _graph_mode_decorator(wrapped, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:347 _graph_mode_decorator
        for v in get_dependent_variables(input_ops=inputs, output_ops=result)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 get_dependent_variables
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:303 <listcomp>
        tf_vars = [v for v in tf_vars if v is not None]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:302 <genexpr>
        tf_vars = (get_variable_by_name(var_name) for var_name in var_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/custom_gradient.py:276 get_variable_by_name
        raise ValueError("Unsuccessful at finding variable {}.".format(var_name))

    ValueError: Unsuccessful at finding variable efficientnet-b7/blocks_0/tpu_batch_normalization_1/moving_variance/replica_1.
```

The training command and config.yaml file are below:

**Training cmd**
python3 main.py --mode=train_and_eval \
    --training_file_pattern=path/to/tfrecord \
    --validation_file_pattern=path/to/tfrecord \
    --model_name=efficientdet-d7x \
    --model_dir=savedir \
    --ckpt=models/efficientdet-d7x \
    --train_batch_size=64 \
    --num_epochs=4 \
    --hparams=path/to/config.yaml\
    --run_epoch_in_child_process=False \
    --strategy=gpus

**config.yaml**
autoaugment_policy: "v0"
grad_checkpoint: True
image_size: 300

The training works as normal with grad_checkpoint being false.

**Comment by fsx950223** [comment]
It's a bug when using mirrored strategy and custom gradient together in graph mode. Could you let tensorflow team take a look?

**Comment by Nicerova7** [comment]
Same problem here , some ideas ? 
`ValueError: Unsuccessful at finding variable efficientnet-b4/blocks_0/tpu_batch_normalization_1/beta/replica_1.
`

**Comment by fsx950223** [comment]
Use keras model.

**Comment by Nicerova7** [comment]
For the moment , it's a option but I'd like to use the oficial efficientdet approach...

**Comment by fsx950223** [comment]
> For the moment , it's a option but I'd like to use the oficial efficientdet approach...

Disable use_keras_model, multi gpus training and grad_checkpoint, then you could get pure official approach.

**Comment by aocz1** [comment]
Are there any work-arounds for this bug? I would love to be able to use this feature as our team is operating with limited computing resources.

**Comment by fsx950223** [comment]
You have 2 choices:
1. Use Keras model
2. Use other multi GPUs strategy such as k8s operator, horovod, etc.

**Comment by aocz1** [comment]
@fsx950223 Changing the strategy to being blank seems to have allowed grad_checkpoint to work. Does that mean there is some issue with the gpu strategy with grad_checkpoint in particular?

**Comment by fsx950223** [comment]
Yes, current approach has some bugs.

**Comment by fsx950223** [comment]
I fix the bug by add following script:
```python
from tensorflow.python.ops import custom_gradient
from tensorflow.python import ops
def get_variable_by_name(var_name):
  """Given a variable name, retrieves a handle on the tensorflow Variable."""

  global_vars = ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES)

  def _filter_fn(item):
      try:
        return var_name == item.op.name
      except AttributeError:
        # Collection items without operation are ignored.
        return False

  candidate_vars = filter(_filter_fn, global_vars)
  
  if len(candidate_vars) >= 1:
    # Filter out non-trainable variables.
    candidate_vars = [v for v in candidate_vars if v.trainable]
  else:
    raise ValueError("Unsuccessful at finding variable {}.".format(var_name))

  if len(candidate_vars) == 1:
    return candidate_vars[0]
  elif len(candidate_vars) > 1:
    raise ValueError(
        "Unsuccessful at finding trainable variable {}. "
        "Number of candidates: {}. "
        "Candidates: {}".format(var_name, len(candidate_vars), candidate_vars))
  else:
    # The variable is not trainable.
    return None
custom_gradient.get_variable_by_name = get_variable_by_name
import tensorflow.compat.v1 as tf
```
before import tensorflow

**Comment by aocz1** [comment]
@fsx950223 Awesome! Will this be added as an update soon?

**Comment by fsx950223** [comment]
> @fsx950223 Awesome! Will this be added as an update soon?

I prefer to fix it in tensorflow.
