### ISSUE TITLE
Export .h5 model failed for segmentation

### ISSUE THREAD

**Issue by chenghuige** [google/automl#897]
I tried to use the segmentation model jus using like keras/segmentation.py but the model could not model.save_weights or model.save to .h5, complaining layer no name. (Might due to keras/efficientdet_keras.py EfficientDetNet(tf.keras.Model) init with name=='' ? seems could not set to non empty value).
Unlike saving to .h5, saving to checkpoint and reload works well.

      model_name = 'efficientdet-d0'
      NUM_CLASSES = 15
      import hparams_config
      from keras import efficientdet_keras
      config = hparams_config.get_efficientdet_config(model_name)
      config.heads = ['segmentation']
      config.seg_num_classes = NUM_CLASSES
      model = efficientdet_keras.EfficientDetNet(config=config)
      model.build((1, 512, 512, 3))
      model.save_weights('model.h5) # wil fail 'layer not name'   

TF 2.30 tried model.save model.save_weights with error below

  File "/home/featurize/data/pikachu/utils/husky/callbacks/callbacks.py", line 437, in save
    model.save(f'{FLAGS.model_dir}/model.h5')
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1979, in save
    signatures, options)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 131, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 109, in save_model_to_hdf5
    model_metadata = saving_utils.model_metadata(model, include_optimizer)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 157, in model_metadata
    raise e
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 154, in model_metadata
    model_config['config'] = model.get_config()
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 598, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1278, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 250, in serialize_keras_object
    raise e
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2231, in get_config
    raise NotImplementedError
NotImplementedError

2020-12-07 12:32:48 0:00:16 WARNING: saved ../working/v6/sm-unet-eff0/model.h5 weights only at step 0 fail
2020-12-07 12:32:48 0:00:16 WARNING: No name (no name)
2020-12-07 12:32:48 0:00:16 WARNING: Traceback (most recent call last):
  File "/home/featurize/data/pikachu/utils/husky/callbacks/callbacks.py", line 461, in save
    self.model.save_weights(f'{FLAGS.model_dir}/model.h5')
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2085, in save_weights
    hdf5_format.save_weights_to_hdf5_group(f, self.layers)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 634, in save_weights_to_hdf5_group
    g = f.create_group(layer.name)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/h5py/_hl/group.py", line 68, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 161, in h5py.h5g.create
ValueError: No name (no name)

**Comment by mingxingtan** [comment]
This is very strange.

Your code works well if config.heads = ['object_detection'], then it works well.  But if you set it to ['segmentation'], then it failed.

@fsx950223 Do you happen to know what's the issue?

**Comment by fsx950223** [comment]
You were exporting a hdf5 model by ```model.save(f'{FLAGS.model_dir}/model.h5')``` which is not support in the current approach, but the sample code could run without any bug.
