### ISSUE TITLE
Error when using autoaugment_policy

### ISSUE THREAD

**Issue by patrickESM** [google/automl#904]
Hello all,

I'm currently training EfficientDet on a custom dataset.
Everything is working as expected when training on the dataset, but when I include any of the autoaugment features like autoaugment_policy: 'v1' I get a strange error. The error is given below.
I'm using following setup:

- Windows 10
- Tf-2.3.1- gpu installed via pip
- cuda 10.1 installed via conda cudatoolkit
- cudnn 7.6.5 for cuda 10.1 installed via conda cudnn
- the rest is installed from requirements.txt

using the following custom config training a efficientdet-d2:

- num_classes: 9
- max_instances_per_image: 100
- input_rand_hflip: False
- optimizer: 'adam'
- weight_decay: 0.0
- lr_decay_method: 'cosine'
- lr_warmup_epoch: 0.25
- jitter_min: 0.9
- jitter_max: 1.3
- num_scales: 3
- min_level: 3
- max_level: 7
- anchor_scale: 4.0
- per_class_nms: True
- autoaugment_policy: 'v1'
- is_training_bn: True
- use_keras_model: True

Thanks for your help in advance.

`Traceback (most recent call last):
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: output dimensions must be positive
	 [[{{node parser/cond_33/then/_296/cond_1/then/_10/cond/else/_1/while/body/_34/cond/then/_0/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: output dimensions must be positive
	 [[{{node parser/cond_33/then/_296/cond_1/then/_10/cond/else/_1/while/body/_34/cond/then/_0/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_24281]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/.linux/projects_hs/m2de2plearning/software/apps/automl/efficientdet/main.py", line 377, in <module>
    app.run(main)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "D:/.linux/projects_hs/m2de2plearning/software/apps/automl/efficientdet/main.py", line 309, in main
    train_est.train(input_fn=train_input_fn, max_steps=train_steps)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1208, in _train_model_default
    saving_listeners)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1511, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\training\monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\pschuelein\Anaconda3\envs\effdet\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: output dimensions must be positive
	 [[{{node parser/cond_33/then/_296/cond_1/then/_10/cond/else/_1/while/body/_34/cond/then/_0/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: output dimensions must be positive
	 [[{{node parser/cond_33/then/_296/cond_1/then/_10/cond/else/_1/while/body/_34/cond/then/_0/PartitionedCall/translate/transform/ImageProjectiveTransformV2}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_24281]]
0 successful operations.
0 derived errors ignored.`

**Comment by patrickESM** [comment]
Custom Input bbx where partially wrong
