### ISSUE TITLE
Issues after tf2.4 update

### ISSUE THREAD

**Issue by Chianugoogidi** [google/automl#916]
I have run into several issues, mostly involving memory usage, while training with the code from the recent tf2.4 update.

1. Although the code from the tf2.4 update is faster, it frequently runs into memory issues when it runs. It does not give an OOM message but something related to cublas, like so:
```
2020-12-30 12:10:47.711563: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-12-30 12:10:47.937204: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-12-30 12:10:48.009065: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-12-30 12:10:48.030106: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-12-30 12:10:48.030140: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "/home/franklinogidi/miniconda3/envs/efficientdet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/franklinogidi/miniconda3/envs/efficientdet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/home/franklinogidi/miniconda3/envs/efficientdet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas SGEMM launch failed : m=4, n=12, k=48
         [[{{node efficientnet-b5/blocks_0/se/conv2d/Conv2D}}]]
         [[add_3/_25125]]
  (1) Internal: Blas SGEMM launch failed : m=4, n=12, k=48
         [[{{node efficientnet-b5/blocks_0/se/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.
```

I used to be able to train on a 2080Ti with a batch size of 16 (with ```grad_checkpoint: true```), now I have to reduce the batch size. If I allow gpu growth, I can get it to run at a batch size of 8 (with ```grad_checkpoint: true```), but that leads to a second problem.

2. The evaluation results are a lot lower than expected. For example:
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.014
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.007
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.067
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.061
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.078
INFO:tensorflow:Inference Time : 247.67111s
```

The above results were produced with the following configurations (NOTE: the problem persists even with ```mixed_precision: false```):
```
python main.py --mode=train_and_eval --train_file_pattern=tfrecord/gwhd-train*.tfrecord --val_file_pattern=tfrecord/gwhd-test*.tfrecord --model_name=efficientdet-d5 --model_dir=experiments/baseline --ckpt=efficientdet-d5 --train_batch_size=4 --eval_samples=1276 --eval_batch_size=4 --num_examples_per_epoch=3422 --num_epochs=200 --save_checkpoints_steps=427 --hparams=global-wheat/configs/baseline.yaml
```

```
num_classes: 2
max_instances_per_image: 200
image_size: 1024
anchor_scale: 4
nms_configs:
    max_output_size: 400
var_freeze_expr: '(efficientnet|fpn_cells|resample_p6)'
label_map: {
    1: wheat_head,
}
input_rand_hflip: false
jitter_min: 1.0
jitter_max: 1.0
grad_checkpoint: true
mixed_precision: true
first_lr_drop_epoch: 100
second_lr_drop_epoch: 150
optimizer: adam
learning_rate: 0.008
lr_warmup_init: 0.0008
```

For comparison, here are the evaluation results while using the previous tf2.3 code, with similar configurations (except a batch_size of 16):
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.188
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.452
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.116
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.146
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.260
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.016
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.127
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.324
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.312
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.362
INFO:tensorflow:Inference Time : 494.27663s
```

And this is the command i ran to get that:
```
python main.py --mode=train_and_eval     --training_file_pattern=tfrecord/gwhd-train*.tfrecord     --validation_file_pattern=tfrecord/gwhd-test*.tfrecord     --model_name=efficientdet-d5     --model_dir=experiments/baseline      --ckpt=efficientdet-d5      --train_batch_size=16     --eval_samples=1276     --eval_batch_size=16     --num_examples_per_epoch=3422     --num_epochs=200      --save_checkpoints_steps=213     --hparams=global-wheat/configs/baseline.yaml
```
Can someone help me understand what's going on?

**Comment by fsx950223** [comment]
I revert some changes and you could pull the latest code and have a try.

**Comment by Chianugoogidi** [comment]
@fsx950223 I have tried with the latest code. The memory issue seems to have been resolved (I can now train with a batch size of 16 as before). But the evaluation results are still not as good as expected, especially when mixed_precision is on.

For example, here is the evaluation results using similar configurations as above (except ```mixed_precision: false```):
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.053
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.168
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.035
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.197
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.042
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.222
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.008
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.214
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.246
INFO:tensorflow:Inference Time : 218.31775s
```

And here are the evaluation results if ```mixed_precision: true```:
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
INFO:tensorflow:Inference Time : 201.17040s
```

**Comment by fsx950223** [comment]
It's fixed in the latest codebase.
