### ISSUE TITLE
NaN loss

### ISSUE THREAD

**Issue by drahmad89** [google/automl#921]
I was perfectly running the training on a gpu nvidia 1080. I switched to a new machine using Nvidia RTX 3090 with CUDA 11.1.
The training on the new gpu using the same configurations is not working due to this error:

ERROR:tensorflow:Model diverged with loss = NaN.
E0108 05:21:32.499725 139877310977856 basic_session_run_hooks.py:770] Model diverged with loss = NaN.

I changed the learning rate and the initial learning based on other issues recommendation #404 #203 #212  but did not work. One of the reasons mentioned in other issues was related to the ground truth bouding boxes ( it could contain zeros or negative values). Therefore, instead of training on a custom dataset, I followed the section 8 (Finetune on PASCAL VOC 2012 with detector COCO ckpt.) from scratch and used the PASCAL VOC dataset. However, I kept having the same error. I also tried different learning rate and different batch size. 
The full command is used:
python main.py --mode=train_and_eval \
    --train_file_pattern=tfrecord/pascal*.tfrecord \
    --val_file_pattern=tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=/tmp/efficientdet-d0-finetune  \
    --ckpt=efficientdet-d0  \
    --train_batch_size=64 \
    --eval_batch_size=64 --eval_samples=1024 \
    --num_examples_per_epoch=5717 --num_epochs=50  \
    --hparams=voc_config.yaml

Below, the complete Traceback:

ERROR:tensorflow:Model diverged with loss = NaN.
E0108 05:52:51.478977 140202646972224 basic_session_run_hooks.py:770] Model diverged with loss = NaN.
Traceback (most recent call last):
  File "main.py", line 403, in <module>
    app.run(main)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 396, in main
    run_train_and_eval(e)
  File "main.py", line 380, in run_train_and_eval
    max_steps=e * FLAGS.num_examples_per_epoch // FLAGS.train_batch_size)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
    saving_listeners)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1514, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1450, in run
    run_metadata=run_metadata))
  File "/home/ahmad/tensor_env/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 771, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by drahmad89** [comment]
Did anyone face a similar problem?

**Comment by staeff777** [comment]
How does the train.py behave with equal hyperparameters?

**Comment by drahmad89** [comment]
I had exactly the same error with --mode=train

**Comment by staeff777** [comment]
I ment the keras/train.py training script.

**Comment by drahmad89** [comment]
I am not able to find any documentation on how to run the script keras/train.py so trying now to running it directly!

**Comment by drahmad89** [comment]
It is skipping the error but giving a nan loss 

  137/30000 [..............................] - ETA: 1:54:24 - det_loss: nan - cls_loss: nan - box_loss: nan - reg_l2_loss: nan - loss: nan - learning_rate: 9.9915e-05 - gradient_norm: nan

**Comment by landskris** [comment]
See if this might help.
https://github.com/google/automl/issues/404#issuecomment-831376156
