### ISSUE TITLE
Use your own data to train the following problems?

### ISSUE THREAD

**Issue by honghande** [google/automl#93]
I0329 18:56:10.857985 140296584976192 tpu_estimator.py:2307] global_step/sec: 2.36818
INFO:tensorflow:examples/sec: 18.9454
I0329 18:56:10.858107 140296584976192 tpu_estimator.py:2308] examples/sec: 18.9454
INFO:tensorflow:training_loop marked as finished
I0329 18:56:11.605264 140296584976192 error_handling.py:108] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0329 18:56:11.605408 140296584976192 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [108]
         [[{{node parser/Assert/Assert}}]]
         [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 385, in <module>
    tf.app.run(main)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 251, in main
    FLAGS.train_batch_size))
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [108]
         [[{{node parser/Assert/Assert}}]]
         [[IteratorGetNext]]

**Comment by CraigWang1** [comment]
Can I see your training command? Are you on the latest version of this github?

**Comment by YangZhang-mizzou** [comment]
Similar problem. For me command is python main.py --training_file_pattern=./tfrecord/train* -validation_file_pattern=./tfrecord/val* --model_dir=/tmp/efficientnet/ --hparams="use_bfloat16=false" --use_tpu=False

**Comment by honghande** [comment]
> Can I see your training command? Are you on the latest version of this github?

python main.py --training_file_pattern=tfrecrod_gstrain/train* \
    --model_name=efficientdet-d0 \
    --model_dir=ckpt/gs \
    --hparams="use_bfloat16=false" --use_tpu=False

**Comment by honghande** [comment]
INFO:tensorflow:examples/sec: 19.6631
I0330 13:06:16.538740 140431403173696 tpu_estimator.py:2308] examples/sec: 19.6631
INFO:tensorflow:global_step/sec: 2.45887
I0330 13:06:16.945310 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.45887
INFO:tensorflow:examples/sec: 19.671
I0330 13:06:16.945435 140431403173696 tpu_estimator.py:2308] examples/sec: 19.671
INFO:tensorflow:global_step/sec: 2.46149
I0330 13:06:17.351580 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.46149
INFO:tensorflow:examples/sec: 19.6919
I0330 13:06:17.351782 140431403173696 tpu_estimator.py:2308] examples/sec: 19.6919
INFO:tensorflow:global_step/sec: 2.56634
I0330 13:06:17.741225 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.56634
INFO:tensorflow:examples/sec: 20.5308
I0330 13:06:17.741344 140431403173696 tpu_estimator.py:2308] examples/sec: 20.5308
INFO:tensorflow:global_step/sec: 2.42574
I0330 13:06:18.153471 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.42574
INFO:tensorflow:examples/sec: 19.4059
I0330 13:06:18.153591 140431403173696 tpu_estimator.py:2308] examples/sec: 19.4059
INFO:tensorflow:global_step/sec: 2.3946
I0330 13:06:18.571078 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.3946
INFO:tensorflow:examples/sec: 19.1568
I0330 13:06:18.571285 140431403173696 tpu_estimator.py:2308] examples/sec: 19.1568
INFO:tensorflow:global_step/sec: 2.57115
I0330 13:06:18.960008 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.57115
INFO:tensorflow:examples/sec: 20.5692
I0330 13:06:18.960128 140431403173696 tpu_estimator.py:2308] examples/sec: 20.5692
INFO:tensorflow:global_step/sec: 2.55611
I0330 13:06:19.351225 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.55611
INFO:tensorflow:examples/sec: 20.4489
I0330 13:06:19.351342 140431403173696 tpu_estimator.py:2308] examples/sec: 20.4489
INFO:tensorflow:global_step/sec: 2.53067
I0330 13:06:19.746378 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.53067
INFO:tensorflow:examples/sec: 20.2454
I0330 13:06:19.746496 140431403173696 tpu_estimator.py:2308] examples/sec: 20.2454
INFO:tensorflow:global_step/sec: 2.466
I0330 13:06:20.151908 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.466
INFO:tensorflow:examples/sec: 19.728
I0330 13:06:20.152028 140431403173696 tpu_estimator.py:2308] examples/sec: 19.728
ERROR:tensorflow:Model diverged with loss = NaN.
E0330 13:06:20.545515 140431403173696 basic_session_run_hooks.py:768] Model diverged with loss = NaN.
INFO:tensorflow:training_loop marked as finished
I0330 13:06:21.215882 140431403173696 error_handling.py:108] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0330 13:06:21.216023 140431403173696 error_handling.py:142] Reraising captured error
Traceback (most recent call last):
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3032, in train
    rendezvous.record_error('training_loop', sys.exc_info())
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 81, in record_error
    if value and value.op and value.op.type == _CHECK_NUMERIC_OP_NAME:
AttributeError: 'NanLossDuringTrainingError' object has no attribute 'op'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 390, in <module>
    tf.app.run(main)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 255, in main
    FLAGS.train_batch_size))
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1450, in run
    run_metadata=run_metadata))
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 769, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by Guzaiwang** [comment]
> INFO:tensorflow:examples/sec: 19.6631
> I0330 13:06:16.538740 140431403173696 tpu_estimator.py:2308] examples/sec: 19.6631
> INFO:tensorflow:global_step/sec: 2.45887
> I0330 13:06:16.945310 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.45887
> INFO:tensorflow:examples/sec: 19.671
> I0330 13:06:16.945435 140431403173696 tpu_estimator.py:2308] examples/sec: 19.671
> INFO:tensorflow:global_step/sec: 2.46149
> I0330 13:06:17.351580 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.46149
> INFO:tensorflow:examples/sec: 19.6919
> I0330 13:06:17.351782 140431403173696 tpu_estimator.py:2308] examples/sec: 19.6919
> INFO:tensorflow:global_step/sec: 2.56634
> I0330 13:06:17.741225 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.56634
> INFO:tensorflow:examples/sec: 20.5308
> I0330 13:06:17.741344 140431403173696 tpu_estimator.py:2308] examples/sec: 20.5308
> INFO:tensorflow:global_step/sec: 2.42574
> I0330 13:06:18.153471 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.42574
> INFO:tensorflow:examples/sec: 19.4059
> I0330 13:06:18.153591 140431403173696 tpu_estimator.py:2308] examples/sec: 19.4059
> INFO:tensorflow:global_step/sec: 2.3946
> I0330 13:06:18.571078 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.3946
> INFO:tensorflow:examples/sec: 19.1568
> I0330 13:06:18.571285 140431403173696 tpu_estimator.py:2308] examples/sec: 19.1568
> INFO:tensorflow:global_step/sec: 2.57115
> I0330 13:06:18.960008 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.57115
> INFO:tensorflow:examples/sec: 20.5692
> I0330 13:06:18.960128 140431403173696 tpu_estimator.py:2308] examples/sec: 20.5692
> INFO:tensorflow:global_step/sec: 2.55611
> I0330 13:06:19.351225 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.55611
> INFO:tensorflow:examples/sec: 20.4489
> I0330 13:06:19.351342 140431403173696 tpu_estimator.py:2308] examples/sec: 20.4489
> INFO:tensorflow:global_step/sec: 2.53067
> I0330 13:06:19.746378 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.53067
> INFO:tensorflow:examples/sec: 20.2454
> I0330 13:06:19.746496 140431403173696 tpu_estimator.py:2308] examples/sec: 20.2454
> INFO:tensorflow:global_step/sec: 2.466
> I0330 13:06:20.151908 140431403173696 tpu_estimator.py:2307] global_step/sec: 2.466
> INFO:tensorflow:examples/sec: 19.728
> I0330 13:06:20.152028 140431403173696 tpu_estimator.py:2308] examples/sec: 19.728
> ERROR:tensorflow:Model diverged with loss = NaN.
> E0330 13:06:20.545515 140431403173696 basic_session_run_hooks.py:768] Model diverged with loss = NaN.
> INFO:tensorflow:training_loop marked as finished
> I0330 13:06:21.215882 140431403173696 error_handling.py:108] training_loop marked as finished
> WARNING:tensorflow:Reraising captured error
> W0330 13:06:21.216023 140431403173696 error_handling.py:142] Reraising captured error
> Traceback (most recent call last):
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3032, in train
> rendezvous.record_error('training_loop', sys.exc_info())
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 81, in record_error
> if value and value.op and value.op.type == _CHECK_NUMERIC_OP_NAME:
> AttributeError: 'NanLossDuringTrainingError' object has no attribute 'op'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "main.py", line 390, in
> tf.app.run(main)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
> _run_main(main, args)
> File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "main.py", line 255, in main
> FLAGS.train_batch_size))
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
> rendezvous.raise_errors()
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
> six.reraise(typ, value, traceback)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
> raise value
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
> saving_listeners=saving_listeners)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
> loss = self._train_model(input_fn, hooks, saving_listeners)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
> return self._train_model_default(input_fn, hooks, saving_listeners)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
> saving_listeners)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_spec
> _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
> run_metadata=run_metadata)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
> run_metadata=run_metadata)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
> raise six.reraise(*original_exc_info)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
> raise value
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
> return self._sess.run(*args, **kwargs)
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1450, in run
> run_metadata=run_metadata))
> File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 769, in after_run
> raise NanLossDuringTrainingError
> tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

I met the same issue about NaN loss. I decrease the learning rate from 0.08---> 0.01, and it can train without this error.

**Comment by emaniac** [comment]
I get the same error training on my own data.
```
...
[[{{node parser/Assert/Assert}}]]
[[IteratorGetNext]]
```

**Comment by mingxingtan** [comment]
Hi @emaniac your problem is most likely from the wrong input data format.

I updated the README and tutorial to show how to convert pascal datasets to COCO format and use it in train/eval.

**Comment by mingxingtan** [comment]
Since it is a little similar to https://github.com/google/automl/issues/94, I am going to close this issue and keep that one open. Thanks!

**Comment by KaqiKaqi** [comment]
> I get the same error training on my own data.
> 
> ```
> ...
> [[{{node parser/Assert/Assert}}]]
> [[IteratorGetNext]]
> ```

Hi, did you solve this problem?

**Comment by emaniac** [comment]
> > I get the same error training on my own data.
> > ```
> > ...
> > [[{{node parser/Assert/Assert}}]]
> > [[IteratorGetNext]]
> > ```
> 
> Hi, did you solve this problem?

Yes, it took me a while. The problem was that some of my data contained more than 100 objects in one image. I changed the constant [MAX_NUM_INSTANCES](https://github.com/google/automl/blob/master/efficientdet/dataloader.py#L27) and it works fine now.

**Comment by KaqiKaqi** [comment]
> > > I get the same error training on my own data.
> > > ```
> > > ...
> > > [[{{node parser/Assert/Assert}}]]
> > > [[IteratorGetNext]]
> > > ```
> > 
> > 
> > Hi, did you solve this problem?
> 
> Yes, it took me a while. The problem was that some of my data contained more than 100 objects in one image. I changed the constant [MAX_NUM_INSTANCES](https://github.com/google/automl/blob/master/efficientdet/dataloader.py#L27) and it works fine now.

Thank you very much! I'll try your suggestion right now.

**Comment by Jucjiaswiss** [comment]
> > > I get the same error training on my own data.
> > > ```
> > > ...
> > > [[{{node parser/Assert/Assert}}]]
> > > [[IteratorGetNext]]
> > > ```
> > 
> > 
> > Hi, did you solve this problem?
> 
> Yes, it took me a while. The problem was that some of my data contained more than 100 objects in one image. I changed the constant [MAX_NUM_INSTANCES](https://github.com/google/automl/blob/master/efficientdet/dataloader.py#L27) and it works fine now.

Thank you! This error has been bothering me since the begining, and tried several ways to generate tfrecords. I 'll try it now.

**Comment by elesun2018** [comment]
I met the same issue about NaN loss. I decrease the learning rate from 0.08---> 0.01, and also same error.

**Comment by anciubotaru** [comment]
Thanks!

**Comment by elv-xuwen** [comment]
> I met the same issue about NaN loss. I decrease the learning rate from 0.08---> 0.01, and also same error.

Me, too. Have you solved the issue?

**Comment by mingxingtan** [comment]
Hi @emaniac  and @KaqiKaqi 

Sorry I did not fully understand about "MAX_NUM_INSTANCES". Why you need to change that and how to change that?

**Comment by aaronrmm** [comment]
@elv-xuwen and @elesun2018 
That's still a relatively high learning rate. Try something specifically small, e.g. 0.00001 and see if you still get NaN.

@mingxingtan 
Increase this if you have image(s) with more than 100 objects.
https://github.com/google/automl/blob/master/efficientdet/dataloader.py#L27
or it will break here
https://github.com/google/automl/blob/master/efficientdet/dataloader.py#L197

**Comment by Li505358678** [comment]
> I get the same error training on my own data.
> 
> ```
> ...
> [[{{node parser/Assert/Assert}}]]
> [[IteratorGetNext]]
> ```

Do you solve the problem?I have the same problem ,too. My custom data to coco.I found my json file have no problem.Is the segment is necessary？

**Comment by KaqiKaqi** [comment]
@mingxingtan MAX_NUM_INSTANCES = 100 is in dataloader.py line 27

**Comment by KaqiKaqi** [comment]
> > I get the same error training on my own data.
> > ```
> > ...
> > [[{{node parser/Assert/Assert}}]]
> > [[IteratorGetNext]]
> > ```
> 
> Do you solve the problem?I have the same problem ,too. My custom data to coco.I found my json file have no problem.Is the segment is necessary？

@Li505358678 I deleted the pictures with too many objects.
I wrote a script to transform csv format labeled data to tfrecord and there is no segmentation in my labeled data. So I think segment is not necessary.

Btw, I got quite satisfying result with D0 using the default learning rate with batch_size = 8.

**Comment by Li505358678** [comment]
> > > I get the same error training on my own data.
> > > ```
> > > ...
> > > [[{{node parser/Assert/Assert}}]]
> > > [[IteratorGetNext]]
> > > ```
> > 
> > 
> > Do you solve the problem?I have the same problem ,too. My custom data to coco.I found my json file have no problem.Is the segment is necessary？
> 
> @Li505358678 I deleted the pictures with too many objects.
> I wrote a script to transform csv format labeled data to tfrecord and there is no segmentation in my labeled data. So I think segment is not necessary.
> 
> Btw, I got quite satisfying result with D0 using the default learning rate with batch_size = 8.

When you trained. What command did you use for your custom data

**Comment by mingxingtan** [comment]
Thanks @emaniac @aaronrmm @KaqiKaqi and everyone.

I have made max_instances_per_image configurable in https://github.com/google/automl/commit/57621e8f3eaddd2c0b421c65c0bbd323ebcf8f2d
