### ISSUE TITLE
tfLite model conversion error (tf.StridedSlice)

### ISSUE THREAD

**Issue by ameyparanjape** [google/automl#966]
I am trying to convert my best checkpoint after training model on custom data using following command

`python model_inspect.py --runmode=saved_model --model_name=efficientdet-d3 --ckpt_path=path/to/archived/checkpoint --saved_model_dir=path/to/savedmodeldir --tensorrt=FP32  --tflite_path=path/to/savedmodeldir/efficientdet-d3.tflite --hparams=path/to/config/file`

In the tflite conversion, I am getting following error,
`error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}`

**_Full error log_**:
```
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py", line 213, in toco_convert_protos
    enable_mlir_converter)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: /usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 151, in export_saved_model
    driver.export(self.saved_model_dir, self.tflite_path, self.tensorrt)
  File "/content/gdrive/My Drive/automl/efficientdet/inference.py", line 605, in export
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py", line 1947, in convert
    return super(TFLiteConverter, self).convert()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py", line 1304, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py", line 613, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: /usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py:300:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:340:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert_saved_model.py:198:0: note: called from
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py:1898:0: note: called from
/content/gdrive/My Drive/automl/efficientdet/inference.py:603:0: note: called from
model_inspect.py:151:0: note: called from
model_inspect.py:462:0: note: called from
model_inspect.py:513:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:251:0: note: called from
/usr/local/lib/python3.7/dist-packages/absl/app.py:300:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
```

**Comment by ameyparanjape** [comment]
I had to add an additional flag in the script `inference.py` to make this work.

Original code, `inference.py` line 606,
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]`

Changed to,
```
# enable TensorFlow ops along with enable TensorFlow Lite ops
converter.target_spec.supported_ops = [ tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS ]
```

Not sure, if it was a general issue or specific to my environment

**Comment by yankee624** [comment]
@ameyparanjape I got the same error and fixed it with your solution. However, when I run the generated tflite model with the `run_tflite.py` file, I got the error `Fatal Python error: Segmentation fault` .. Didn't you encounter this error?
