### ISSUE TITLE
Training failes: RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

### ISSUE THREAD

**Issue by ardraeger** [google/automl#980]
Hi I'm trying to retrain the efficientdet-d1 on a custom dataset.
However, when I run the main.py as follows I get an error. 
The training command I use is:
python3 main.py --mode=train_and_eval --train_file_pattern=train/* --val_file_pattern=test/* --model_name=efficientdet-d1 --model_dir efficientdet-d1/ --ckpt=efficientdet-d1 --train_batch_size=2 --eval_batch_size=2 --num_epochs=10 --num_examples_per_epoch=5000 --eval_samples=100 --hparams=configs/default.yaml

I run the script on Ubuntu 18.04
python 3.6.9
with 
tensorflow 2.5.0-dev20201224'

The error:
Traceback (most recent call last):
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_4891]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1303, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/acaris/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py:1510) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/acaris/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py:1510) ]]
	 [[save/RestoreV2/_4891]]
0 successful operations.
0 derived errors ignored.

...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1313, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1631, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 74, in get_tensor
    error_translator(e)
  File "/home/acaris/.local/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

...

tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/acaris/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py:1510) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/Momentum not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/acaris/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py:1510) ]]
	 [[save/RestoreV2/_4891]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "main.py", line 402, in <module>

Looks like a mismatch of some sort. Any idea how to fix this?

**Comment by mingxingtan** [comment]
Hi, based on your command line, it is problematic to set "--model_dir=efficientdet-d1 --ckpt=efficientdet-d1". Because  efficientdet-d1 folder is not empty, it will skip --ckpt and tried to load all variables from efficientdet-d1, causing this issue.

Please use a different value for model_dir such as efficientdet-d1-finetune. Let me know if it still doesn't work.

**Comment by drahmad89** [comment]
what about this case too?
python -model_inspect.py --runmode=saved_model --model_name=efficientdet-d3   --ckpt_path=efficientdet-lite3 --saved_model_dir=lite3_savedmodel

I am getting :L

2 root error(s) found.
  (0) Not found: Key efficientnet-b3/blocks_0/conv2d/kernel not found in checkpoint
         [[node save/RestoreV2 (defined at /home/chaahm/automl_newest/efficientdet/inference.py:217) ]]
         [[save/RestoreV2/_301]]
  (1) Not found: Key efficientnet-b3/blocks_0/conv2d/kernel not found in checkpoint
         [[node save/RestoreV2 (defined at /home/chaahm/automl_newest/efficientdet/inference.py:217) ]]
