### ISSUE TITLE
[efficietndet] finetune on voc error, metric error

### ISSUE THREAD

**Issue by gdy2021** [google/automl#987]
I follow the instruction of "8. Finetune on PASCAL VOC 2012 with detector COCO ckpt." and encounter errors like this
```shell
2021-05-11 12:30:14.771597: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO:tensorflow:Restoring parameters from ./model/efficientdet-d0-finetune-voc/model.ckpt-0
I0511 12:30:14.771730 140500869998336 saver.py:1292] Restoring parameters from ./model/efficientdet-d0-finetune-voc/model.ckpt-0
INFO:tensorflow:Running local_init_op.
I0511 12:30:16.816297 140500869998336 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0511 12:30:16.979402 140500869998336 session_manager.py:508] Done running local_init_op.
creating index...
index created!
2021-05-11 12:30:32.279483: W tensorflow/core/framework/op_kernel.cc:1751] Unknown: IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
Traceback (most recent call last):

  File "/data/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/data/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/data/proj/detection/automl/efficientdet/coco_metric.py", line 174, in result
    self.metric_values = self.evaluate(log_level)

  File "/data/proj/detection/automl/efficientdet/coco_metric.py", line 142, in evaluate
    image_ids = list(set(detections[:, 0]))

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
it seems that the `EvaluationMetric.update_state` is not called, which makes `EvaluationMetric.detections` empty.
anyone knows why and how to solve this?
thank you very much.

**Comment by achukhrov-ffr-team** [comment]
@gdy2021, have you solved your problem? I have the same issue

**Comment by danielTobon43** [comment]
I have the same!

**Comment by danielTobon43** [comment]
@gdy2021 @achukhrov-ffr-team I found out that the problem was with the batch size. I still don know why is this happening, but I tested with:
```
--backbone_ref=efficientdet-d0
--num_epochs=15
--num_examples_per_epoch=500
--batch_size=6
--eval_samples=1024
```

And the problem was solved!

Before that, I was using batch size=8.
